### ISSUE TITLE
tzcode-2017.b-1-x86_64.pkg.tar.xz not found

### ISSUE THREAD

**Issue by krasnovu** [Alexpux/MSYS2-packages#1007]
Hello!
`$ pacman -Syuu
:: Обновление баз данных пакетов...
 mingw32                                     357,4 KiB   349M/s 00:00 [#####################################] 100%
 mingw32.sig                                  96,0   B  0,00B/s 00:00 [#####################################] 100%
 mingw64                                     357,1 KiB   153K/s 00:02 [#####################################] 100%
 mingw64.sig                                  96,0   B  0,00B/s 00:00 [#####################################] 100%
 msys                                        154,6 KiB   151M/s 00:00 [#####################################] 100%
 msys.sig                                     96,0   B  0,00B/s 00:00 [#####################################] 100%
:: Starting core system upgrade...
 делать больше нечего
:: Запускается полное обновление системы...
разрешение зависимостей...
проверка конфликтов...

Пакеты (58) bash-completion-2.5-1  bsdcpio-3.3.2-1  bsdtar-3.3.2-1  ca-certificates-20170717-2  coreutils-8.26-1
            curl-7.55.1-2  file-5.32-1  flex-2.6.4-1  gawk-4.1.4-2  gcc-libs-6.3.0-1  gettext-0.19.8.1-1
            gmp-6.1.2-1  gnupg-1.4.22-1  grep-3.0-1  icu-59.1-1  inetutils-1.9.4-1  info-6.3-1  libarchive-3.3.2-1
            libasprintf-0.19.8.1-1  libassuan-2.4.3-1  libcrypt-2.1-1  libcurl-7.55.1-2  libedit-3.1-20170329
            libexpat-2.2.4-1  libgettextpo-0.19.8.1-1  libgpg-error-1.27-1  libidn2-2.0.4-2  libintl-0.19.8.1-1
            liblzma-5.2.3-1  liblzo2-2.10-1  libmetalink-0.1.3-1  libnghttp2-1.24.0-1  libopenssl-1.0.2.l-1
            libp11-kit-0.23.8-1  libpcre-8.40-2  libpcre16-8.40-2  libpcre32-8.40-2  libpcrecpp-8.40-2
            libpcreposix-8.40-2  libreadline-7.0.003-1  libsqlite-3.19.3.0-1  libssh2-1.8.0-1  libtasn1-4.12-1
            libunistring-0.9.7-1  libxml2-2.9.2-3  m4-1.4.18-1  mpfr-3.1.5.1-3  ncurses-6.0.20170708-2
            openssl-1.0.2.l-1  p11-kit-0.23.8-1  pax-git-20161104.2-1  pcre-8.40-2  pkgfile-17-1  sed-4.4-2
            tzcode-2017.b-1  wget-1.19.1-1  xz-5.2.3-1  zlib-1.2.11-1

Будет загружено:   28,73 MiB
Будет установлено:  132,86 MiB
Изменение размера:    8,44 MiB

:: Приступить к установке? [Y/n]
:: Получение пакетов...
 bash-completion-2.5-1-any                   188,1 KiB   184M/s 00:00 [#####################################] 100%
 gcc-libs-6.3.0-1-x86_64                     819,1 KiB   267M/s 00:00 [#####################################] 100%
 libintl-0.19.8.1-1-x86_64                    30,8 KiB  0,00B/s 00:00 [#####################################] 100%
 libgettextpo-0.19.8.1-1-x86_64              117,7 KiB   115M/s 00:00 [#####################################] 100%
 libasprintf-0.19.8.1-1-x86_64                16,1 KiB  0,00B/s 00:00 [#####################################] 100%
 gettext-0.19.8.1-1-x86_64                  1542,1 KiB   321K/s 00:05 [#####################################] 100%
 liblzma-5.2.3-1-x86_64                       78,3 KiB  0,00B/s 00:00 [#####################################] 100%
 liblzo2-2.10-1-x86_64                        68,8 KiB  67,1M/s 00:00 [#####################################] 100%
 gmp-6.1.2-1-x86_64                          371,3 KiB   363M/s 00:00 [#####################################] 100%
 coreutils-8.26-1-x86_64                       2,2 MiB   638K/s 00:04 [#####################################] 100%
 ncurses-6.0.20170708-2-x86_64              1167,4 KiB   590K/s 00:02 [#####################################] 100%
 libreadline-7.0.003-1-x86_64                266,8 KiB   261M/s 00:00 [#####################################] 100%
 zlib-1.2.11-1-x86_64                         55,1 KiB  53,8M/s 00:00 [#####################################] 100%
 libxml2-2.9.2-3-x86_64                      497,0 KiB   485M/s 00:00 [#####################################] 100%
 bsdcpio-3.3.2-1-x86_64                      817,3 KiB   399M/s 00:00 [#####################################] 100%
 bsdtar-3.3.2-1-x86_64                       861,4 KiB   421M/s 00:00 [#####################################] 100%
 libopenssl-1.0.2.l-1-x86_64                 812,8 KiB   397M/s 00:00 [#####################################] 100%
 openssl-1.0.2.l-1-x86_64                   1353,6 KiB   695K/s 00:02 [#####################################] 100%
 sed-4.4-2-x86_64                            213,2 KiB   208M/s 00:00 [#####################################] 100%
 libpcre-8.40-2-x86_64                        94,2 KiB  92,0M/s 00:00 [#####################################] 100%
 info-6.3-1-x86_64                           178,8 KiB   175M/s 00:00 [#####################################] 100%
 libtasn1-4.12-1-x86_64                      105,6 KiB  0,00B/s 00:00 [#####################################] 100%
 libp11-kit-0.23.8-1-x86_64                  148,9 KiB   145M/s 00:00 [#####################################] 100%
 p11-kit-0.23.8-1-x86_64                     229,7 KiB   224M/s 00:00 [#####################################] 100%
 ca-certificates-20170717-2-any              419,8 KiB   410M/s 00:00 [#####################################] 100%
 libcrypt-2.1-1-x86_64                        32,1 KiB  0,00B/s 00:00 [#####################################] 100%
 libunistring-0.9.7-1-x86_64                 504,7 KiB   493M/s 00:00 [#####################################] 100%
 libidn2-2.0.4-2-x86_64                       76,7 KiB  74,9M/s 00:00 [#####################################] 100%
 libexpat-2.2.4-1-x86_64                      62,7 KiB  0,00B/s 00:00 [#####################################] 100%
 libmetalink-0.1.3-1-x86_64                   32,8 KiB  0,00B/s 00:00 [#####################################] 100%
 libnghttp2-1.24.0-1-x86_64                   63,7 KiB  0,00B/s 00:00 [#####################################] 100%
 libssh2-1.8.0-1-x86_64                      173,4 KiB  0,00B/s 00:00 [#####################################] 100%
 libedit-3.1-20170329-x86_64                  96,9 KiB  0,00B/s 00:00 [#####################################] 100%
 icu-59.1-1-x86_64                             7,3 MiB   685K/s 00:11 [#####################################] 100%
 libsqlite-3.19.3.0-1-x86_64                 563,5 KiB   275M/s 00:00 [#####################################] 100%
 libcurl-7.55.1-2-x86_64                     212,4 KiB   207M/s 00:00 [#####################################] 100%
 curl-7.55.1-2-x86_64                        699,3 KiB   341M/s 00:00 [#####################################] 100%
 file-5.32-1-x86_64                          469,3 KiB   458M/s 00:00 [#####################################] 100%
 m4-1.4.18-1-x86_64                          213,6 KiB   209M/s 00:00 [#####################################] 100%
 flex-2.6.4-1-x86_64                         294,6 KiB   144M/s 00:00 [#####################################] 100%
 mpfr-3.1.5.1-3-x86_64                       242,0 KiB   236M/s 00:00 [#####################################] 100%
 gawk-4.1.4-2-x86_64                         986,4 KiB   482M/s 00:00 [#####################################] 100%
 gnupg-1.4.22-1-x86_64                      1037,0 KiB   588K/s 00:02 [#####################################] 100%
 grep-3.0-1-x86_64                           239,9 KiB   234M/s 00:00 [#####################################] 100%
 inetutils-1.9.4-1-x86_64                    194,6 KiB   190M/s 00:00 [#####################################] 100%
 libarchive-3.3.2-1-x86_64                   816,4 KiB   399M/s 00:00 [#####################################] 100%
 libgpg-error-1.27-1-x86_64                  115,9 KiB  0,00B/s 00:00 [#####################################] 100%
 libassuan-2.4.3-1-x86_64                     97,2 KiB  94,9M/s 00:00 [#####################################] 100%
 libpcre16-8.40-2-x86_64                      92,6 KiB  0,00B/s 00:00 [#####################################] 100%
 libpcre32-8.40-2-x86_64                      86,6 KiB  0,00B/s 00:00 [#####################################] 100%
 libpcrecpp-8.40-2-x86_64                     22,7 KiB  0,00B/s 00:00 [#####################################] 100%
 libpcreposix-8.40-2-x86_64                   16,2 KiB  0,00B/s 00:00 [#####################################] 100%
 pax-git-20161104.2-1-x86_64                  84,7 KiB  82,7M/s 00:00 [#####################################] 100%
 pcre-8.40-2-x86_64                          589,2 KiB   288M/s 00:00 [#####################################] 100%
 xz-5.2.3-1-x86_64                           145,4 KiB   142M/s 00:00 [#####################################] 100%
 pkgfile-17-1-x86_64                          35,1 KiB  0,00B/s 00:00 [#####################################] 100%
ошибка: не удалось получить файл 'tzcode-2017.b-1-x86_64.pkg.tar.xz' из repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
ошибка: не удалось получить файл 'tzcode-2017.b-1-x86_64.pkg.tar.xz' из downloads.sourceforge.net : Operation timed out after 10000 milliseconds with 0 out of 0 bytes received
ошибка: не удалось получить файл 'tzcode-2017.b-1-x86_64.pkg.tar.xz' из www2.futureware.at : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
предупреждение: не удалось получить некоторые файлы
 wget-1.19.1-1-x86_64                        637,9 KiB   623M/s 00:00 [#####################################] 100%
ошибка: не удалось завершить транзакцию (непредвиденная ошибка)
Обнаружены ошибки, пакеты не обновлены.`
What can i do to resolve this problem?

**Comment by Alexpux** [comment]
File present on servers. Try rerun pacman

**Comment by krasnovu** [comment]
Second try
`$ pacman -Syuu
:: Обновление баз данных пакетов...
 mingw32                                     357,4 KiB   349M/s 00:00 [#####################################] 100%
 mingw32.sig                                  96,0   B  0,00B/s 00:00 [#####################################] 100%
 mingw64                                     357,1 KiB   349M/s 00:00 [#####################################] 100%
 mingw64.sig                                  96,0   B  0,00B/s 00:00 [#####################################] 100%
 msys                                        154,6 KiB   151M/s 00:00 [#####################################] 100%
 msys.sig                                     96,0   B  0,00B/s 00:00 [#####################################] 100%
:: Starting core system upgrade...
 делать больше нечего
:: Запускается полное обновление системы...
разрешение зависимостей...
проверка конфликтов...

Пакеты (58) bash-completion-2.5-1  bsdcpio-3.3.2-1  bsdtar-3.3.2-1  ca-certificates-20170717-2  coreutils-8.26-1
            curl-7.55.1-2  file-5.32-1  flex-2.6.4-1  gawk-4.1.4-2  gcc-libs-6.3.0-1  gettext-0.19.8.1-1
            gmp-6.1.2-1  gnupg-1.4.22-1  grep-3.0-1  icu-59.1-1  inetutils-1.9.4-1  info-6.3-1  libarchive-3.3.2-1
            libasprintf-0.19.8.1-1  libassuan-2.4.3-1  libcrypt-2.1-1  libcurl-7.55.1-2  libedit-3.1-20170329
            libexpat-2.2.4-1  libgettextpo-0.19.8.1-1  libgpg-error-1.27-1  libidn2-2.0.4-2  libintl-0.19.8.1-1
            liblzma-5.2.3-1  liblzo2-2.10-1  libmetalink-0.1.3-1  libnghttp2-1.24.0-1  libopenssl-1.0.2.l-1
            libp11-kit-0.23.8-1  libpcre-8.40-2  libpcre16-8.40-2  libpcre32-8.40-2  libpcrecpp-8.40-2
            libpcreposix-8.40-2  libreadline-7.0.003-1  libsqlite-3.19.3.0-1  libssh2-1.8.0-1  libtasn1-4.12-1
            libunistring-0.9.7-1  libxml2-2.9.2-3  m4-1.4.18-1  mpfr-3.1.5.1-3  ncurses-6.0.20170708-2
            openssl-1.0.2.l-1  p11-kit-0.23.8-1  pax-git-20161104.2-1  pcre-8.40-2  pkgfile-17-1  sed-4.4-2
            tzcode-2017.b-1  wget-1.19.1-1  xz-5.2.3-1  zlib-1.2.11-1

Будет загружено:    0,29 MiB
Будет установлено:  132,86 MiB
Изменение размера:    8,44 MiB

:: Приступить к установке? [Y/n]
:: Получение пакетов...
ошибка: не удалось получить файл 'tzcode-2017.b-1-x86_64.pkg.tar.xz' из repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
ошибка: не удалось получить файл 'tzcode-2017.b-1-x86_64.pkg.tar.xz' из downloads.sourceforge.net : Operation timed out after 10000 milliseconds with 0 out of 0 bytes received
ошибка: не удалось получить файл 'tzcode-2017.b-1-x86_64.pkg.tar.xz' из www2.futureware.at : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
предупреждение: не удалось получить некоторые файлы
ошибка: не удалось завершить транзакцию (ошибка в библиотеке загрузки)
Обнаружены ошибки, пакеты не обновлены.
`

**Comment by Alexpux** [comment]
download file manually and place into /var/cache/pacman/pkg

**Comment by krasnovu** [comment]
Thanks a lot! Update works fine now.
