### ISSUE TITLE
pacman -Syu getopt replacement prompt

### ISSUE THREAD

**Issue by orcmid** [Alexpux/MSYS2-packages#101]
On a fresh install of msys2-x86_64-20141003.exe, running pacman -Syu raises the prompt

:: Replace getopt with msys/util-linux? [Y/n]

What are the consequences of the choice here.  I let it default, but I have no idea what I am choosing.

**Comment by elieux** [comment]
MSYS2 is not too user-friendly, but that's IMO fine given its status of a developer tool.

**Comment by yashpalgoyal1304** [comment]
> MSYS2 is not too user-friendly

but it is lol, certainly more user friendly than MOST all other developer or even non-developer tools i have used so far.
