### ISSUE TITLE
Simplest Meson example does not work: Native dependency not found for any library

### ISSUE THREAD

**Issue by db0451** [Alexpux/MSYS2-packages#1011]
Trying to find any dependency with pkg-config fails...

`project('test', 'c')

zdep = dependency('zlib', version : '>=1.2.8')`

gives this

`MINGW64 ~/src
$ meson /tmp
The Meson build system
Version: 0.42.1
Source dir: C:/msys64/home/daniel.boles/src
Build dir: C:/msys64/tmp
Build type: native build
Project name: test
Native C compiler: cc (gcc 7.2.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: C:\msys64\usr\bin/pkg-config.EXE (0.29.2)

Meson encountered an error in file meson.build, line 3, column 0:
Native dependency 'zlib' not found`

I suspect the path to pkg-config is the problem; trying to run that fails, unless it's wrapped in quotes, so I suspect the backslashes to be the issue.

So much for moving to the great new build system... if it can't even find any libraries. Hopefully this one is easy to fix!

Thanks in advance and please let me know of any other info wanted.

**Comment by db0451** [comment]
Not sure, but a guess is that the backslashed path comes from here:

`WD='C:\msys64\usr\bin\'`

**Comment by db0451** [comment]
...hm, obviously not, because (A) that's already quoted and (B) changing and exporting it before running meson made no difference.

**Comment by db0451** [comment]
I guess it's not the backslashes, because exporting a path without then doesn't make any difference.

Sadly Meson appears to lack a verbose mode that I could use to see what it passes to that binary.

Installing mingw-w64-x86_64-pkg-config-0.29.2-1 made no difference either.


$ export PKG_CONFIG=/usr/bin/pkg-config.exe

$ meson /tmp
The Meson build system
Version: 0.42.1
Source dir: C:/msys64/home/daniel.boles/src
Build dir: C:/msys64/tmp
Build type: native build
Project name: test
Native C compiler: cc (gcc 7.2.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: C:/msys64/usr/bin/pkg-config.exe (0.29.2)

Meson encountered an error in file meson.build, line 3, column 0:
Native dependency 'zlib' not found

**Comment by jtanx** [comment]
Try

```
export PKG_CONFIG=/mingw64/bin/pkg-config.exe
```

?

**Comment by db0451** [comment]
Thanks! That works. So it seems to be because Meson picks up the MSYS2 pkg-config by default?

It feels like this should just work out of the box, rather than requiring this? Maybe the msys2 shell needs to set something more specifically (WD, perhaps?)

**Comment by db0451** [comment]
I've now gotten forward to this point:

Meson encountered an error in file meson.build, line 115, column 1:
File /mingw64/bin/librsvg-2-2.dll does not exist.

Yet if I copy and paste that path, and ls it, it exists just fine and has normal permissions. Why would Meson be unable to find it?

It doesn't like  /c/msys64/mingw64/bin/librsvg-2-2.dll either.

**Comment by jtanx** [comment]
If you're building for mingw then have you tried using the mingw packaged meson (mingw-w64-x86_64-meson) instead?

**Comment by db0451** [comment]
I should've been clear; that is what I'm using:

mingw64/mingw-w64-x86_64-meson 0.42.1-1 [installed]
    High-productivity build system (mingw-w64)

$ which meson
/mingw64/bin/meson

**Comment by jtanx** [comment]
Ah yeah, I mistakenly thought there was an msys meson.

What are you using that has librsvg(?)? My meson worked out of the box without having to mess around with pkg-config by the way.

```
$meson /tmp
The Meson build system
Version: 0.42.1
Source dir: C:/msys64/home/jtanx/tmp/meson
Build dir: C:/msys64/tmp
Build type: native build
Project name: test
Native C compiler: cc (gcc 7.2.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: C:\msys64\mingw64\bin/pkg-config.EXE (0.29.2)
Native dependency zlib found: YES 1.2.11
Build targets in project: 0
```

**Comment by db0451** [comment]
In brief, I'm writing some rules to bundle everything my app needs to run, so I need to invoke ldd on it and any DLLs that it loads at runtime, in this case librsvg for GTK+/gdk-pixbuf loading SVG images. Then I chop up the result of ldd and copy it to a folder for zipping up.

libsrvg exists there, and my script happily runs ldd on it, but Meson refuses to see it, which is baffling to me.

**Comment by jtanx** [comment]
Ok, so the question then is how is it getting that path? Since meson here is a native (mingw) binary, it requires actual paths to work, e.g. `c:/msys64/mingw64/bin/librsvg-2-2.dll` not `c/msys64/mingw64/bin/librsvg-2-2.dll`. 

I believe there's some path translation magic that happens when you pass paths to the executable when running in the msys shell, but I don't really know the specifics of it. 

At a guess, if you're parsing the path from the output of ldd, you could try transforming the path via cygpath, e.g.:

```
cygpath -w /mingw64/bin/librsvg-2-2.dll
```

Or you could use ntldd instead (I find this works better than ldd anyway)

**Comment by db0451** [comment]
Excellent - right on the mark again. Thanks! Seems I need to do cygpath -w $MINGW_PREFIX when building the filenames to be installed, and likewise use ntldd to get paths in the right format. That at least gets me compiling, just need to fix all the other issues with my build file now...

I'll check on another Windows machine later if it has the same problem with pkg-config out of the box; if so, that'd be worth resolving. If not, I'll chalk it up to a blip!

**Comment by db0451** [comment]
closing assuming outdated
