### ISSUE TITLE
svn

### ISSUE THREAD

**Issue by adepumeena** [Alexpux/MSYS2-packages#1033]
Problem occurred when installing svn on Ubuntu 16.04.

After installing the apache2 server and Creation of repository, after that I got this error while connecting to repository by the following command:

sudo svn co file:///svn/repository/

svn: E170013: Unable to connect to a repository at URL 'file:///svn/repository'
svn: E180001: Unable to open repository 'file:///svn/repository'
please help me on this issue.

Thanks in Advance, Meena.

**Comment by mati865** [comment]
How is it related to MSYS2?

**Comment by ErichDonGubler** [comment]
You seem to have filed two issues for this problem -- could we get one closed, so we can keep the thread in one place?

**Comment by lazka** [comment]
Duplicate of #1034
