### ISSUE TITLE
gpg is broken after pacman -Syy  && pacman -S libreadline-devel

### ISSUE THREAD

**Issue by cupen** [Alexpux/MSYS2-packages#1035]
Reproduction:
Install from <http://repo.msys2.org/distrib/x86_64/msys2-x86_64-20161025.exe>
```bash
$ pacman -Ss libreadline
msys/libreadline 7.0.003-1 (libraries) [已安装: 6.3.008-7]
    GNU readline library
msys/libreadline-devel 7.0.003-1 (development) [已安装: 6.3.008-7]
    readline headers and libraries
$ pacman -Syy  
$ pacman -S libreadline-devel
$ pacman
error: GPGME error: Invalid crypto engine
error: GPGME error: Invalid crypto engine
error: GPGME error: Invalid crypto engine
error: no operation specified (use -h for help)
$ gpg
D:/msys64/usr/bin/gpg.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory

$ strace gpg  # Then it show me missing the msys-libreadline6.dll
......
```
It looks like `gpg.exe` is depend on  `/usr/bin/msys-readline6.dll`, not `/usr/bin/msys-readline7.dll`.
And `pacman`,`makepkg` cannot work fine without gpg. 

So I download `http://repo.msys2.org/msys/x86_64/libreadline-6.3.008-6-x86_64.pkg.tar.xz` and extract the `msys-readline6.dll` to the `/usr/bin/msys-readline6.dll` manually, then it works fine.

**Comment by Alexpux** [comment]
You must update all packages, not only some of thems. MSYS2 not support partial upgrades.

**Comment by cupen** [comment]
@Alexpux  ok.
