### ISSUE TITLE
L.A.M.E. 3.100

### ISSUE THREAD

**Issue by Barough** [Alexpux/MSYS2-packages#1039]
Please update so that L.A.M.E. v3.100 gets compiled

**Comment by lazka** [comment]
It already is: http://quodlibet.duckdns.org/msys2/base/mingw-w64-lame

**Comment by ErichDonGubler** [comment]
@Barough: Does @lazka's comment help you with this issue? Is there anything else you need in order to get your problem solved?

**Comment by lazka** [comment]
Since there hasn't been a response I assume this is solved.
