### ISSUE TITLE
autogen missing dependency

### ISSUE THREAD

**Issue by kuh3h3** [Alexpux/MSYS2-packages#1070]
recently guile updated to version 2.2.
but autogen still need guile 2.0.
Please recompile autogen whith guile 2.2.

$ pacman -Ss autogen
msys/autogen 5.18.12-1 (base-devel)
    A tool designed to simplify the creation and maintenance of programs that contain large amounts of repetitious text
kuh3h3@DESKTOP-R0PM5LB /trunk/build/autogen/autogen-5.18.12
$ pacman -S autogen
resolving dependencies...
looking for conflicting packages...

Packages (1) autogen-5.18.12-1

Total Installed Size:  1.42 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                    [##############################################] 100%
(1/1) checking package integrity                                                  [##############################################] 100%
(1/1) loading package files                                                       [##############################################] 100%
(1/1) checking for file conflicts                                                 [##############################################] 100%
(1/1) checking available disk space                                               [##############################################] 100%
:: Processing package changes...
(1/1) installing autogen                                                          [##############################################] 100%
kuh3h3@DESKTOP-R0PM5LB /trunk/build/autogen/autogen-5.18.12
$ pacman -Ss guile
msys/guile 2.2.2-1 [installed]
    a portable, embeddable Scheme implementation written in C
msys/libguile 2.2.2-1 (libraries) [installed]
    a portable, embeddable Scheme implementation written in C
msys/libguile-devel 2.2.2-1 (development) [installed]
    a portable, embeddable Scheme implementation written in C
kuh3h3@DESKTOP-R0PM5LB /trunk/build/autogen/autogen-5.18.12
$ autogen
C:/Users/kuh3h/Downloads/media-autobuild_suite/msys64/usr/bin/autogen.exe: error while loading shared libraries: msys-guile-2.0-22.dll: cannot open shared object file: No such file or directory
kuh3h3@DESKTOP-R0PM5LB /trunk/build/autogen/autogen-5.18.12

**Comment by Adsun701** [comment]
I fixed this in a pull request. autogen had to be patched to be able to use guile version 2.2. #1075
