### ISSUE TITLE
Remake broken (expects an old msys-guile version?)

### ISSUE THREAD

**Issue by radioflash** [Alexpux/MSYS2-packages#1080]
Remake says:
`remake.exe: error while loading shared libraries: msys-guile-2.0-22.dll: cannot open shared object file: No such file or directory`

The guile DLL that is actuallly installed by MSYS is msys-guile-2.2-1.dll, so this seems to be a version mismatch. Everything is up-to-date ("pacman -Syu" does nothing).

I can not see any guile dependency in the remake-git PKGBUILD, but my understanding is very limited.

How could this be fixed?

**Comment by ErichDonGubler** [comment]
There is actually a `guile` dependency for `remake-git` -- see [this line](https://github.com/Alexpux/MSYS2-packages/blob/master/remake-git/PKGBUILD#L14) in the latest PKGBUILD -- so, maybe you missed it?

To your point, though:
* @h-c-mueller submitted a PR to update `guile` to 2.2 (https://github.com/Alexpux/MSYS2-packages/pull/1047), which then was merged about 3 weeks ago. MSYS2 repo updates happened more recently (within the last 2 weeks?).
* [The PKGBUILD for `remake-git`](https://github.com/Alexpux/MSYS2-packages/blob/c91ce230df43049aa832ac0bac9a55c4a1c69f22/remake-git/PKGBUILD#L6) shows that we use `remake` version 4.1.
* `remake` 4.1 [seems to support at most `guile` 2.0](https://github.com/rocky/remake/blob/remake-4-1/configure.ac#L175), while [4.2 includes `guile` 2.2](https://github.com/rocky/remake/blob/remake-4-2/configure.ac#L181).

**Given the above facts, it seems that a resolution for this issue can be as straightforward as simply bumping the version on the `remake-git` package. Could you submit a PR to fix it?**

I've much more experience with Arch Linux repositories than MSYS2 ones, so I have a separate question for @Alexpux: why is the `remake-git` package labeled as `-git`, if it has a firm version associated? AFAIU, `-git` is usually a suffix reserved for packages that only point to the latest upstream changes.

**Comment by radioflash** [comment]
Just noticed that this was fixed by @Alexpux two weeks ago, by patching remake 4.1 to allow linking to guile 2.2.

I believe upgrading to remake 4.2 as alternative solution is not trivial-- in my attempts the whole thing failed a lot of tests after building, making me give up.

Many thanks!
