### ISSUE TITLE
Would it be possible to release an updated installer?

### ISSUE THREAD

**Issue by jrmoore** [Alexpux/MSYS2-packages#1105]
Hi, right now the installer on the website dates from the 25th of October 2016 and after installing MSYS2 a `pacman -Syu` pulls up quite a lot of changes, including core ones to the environment.

Would it be possible to build and release an updated MSYS2 installer? I think it would ease up deployment since some of the updates require the shell to be externally terminated.

**Comment by niklasholm** [comment]
The installer on [sourceforge.net](https://sourceforge.net/projects/msys2/files/) dates September 18, 2017. Strange that the different channels aren't in sync.

**Comment by jrmoore** [comment]
I just realized there's a new version of the installer in the main website dated barely a month ago, so thank your for your work.

I'm closing this ticket now as it's resolved ;).
