### ISSUE TITLE
[tmux] Working directory is always $HOME

### ISSUE THREAD

**Issue by niklasholm** [Alexpux/MSYS2-packages#1133]
**Command:**
```shell
$ tmux new-session -c "/etc"
```

**Expected result:**
tmux launches a new session with `/etc` set as the working directory

**Actual result:**
tmux launches a new session with `$HOME` with working directory.

---

**Command:**
```shell
$ tmux new-session
```

**Expected result:**
tmux launches a new session with the current directory set as the working directory

**Actual result:**
tmux launches a new session with `$HOME` with working directory.

---

**Additional info:**
```shell
$ tmux -V
tmux 2.6

$ env LANG=en_US.UTF-8 pacman -Qi tmux
Name            : tmux
Version         : 2.6-1
Description     : A terminal multiplexer
Architecture    : x86_64
URL             : https://tmux.github.io/
Licenses        : BSD
Groups          : None
Provides        : None
Depends On      : ncurses  libevent
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : tmux-git
Installed Size  : 504.00 KiB
Packager        : Alexey Pavlov <alexpux@gmail.com>
Build Date      : Thu, Jan 11, 2018 5:39:15 AM
Install Date    : Thu, Feb 01, 2018 3:13:37 PM
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by eromoe** [comment]
I know the problem is from profile , but I don't familiar with msys2 code and bash.  If you have time you can look into https://github.com/Alexpux/MSYS2-packages/issues/1107

**Comment by niklasholm** [comment]
@eromoe, you're right, sorry for the dupe. Closing.
