### ISSUE TITLE
gawk 4.2.0 failure with dos line endings

### ISSUE THREAD

**Issue by ssbssa** [Alexpux/MSYS2-packages#1138]
[input-crlf.txt](https://github.com/Alexpux/MSYS2-packages/files/1708223/input-crlf.txt)
[input-lf.txt](https://github.com/Alexpux/MSYS2-packages/files/1708224/input-lf.txt)
[output-crlf-4.1.txt](https://github.com/Alexpux/MSYS2-packages/files/1708225/output-crlf-4.1.txt)
[output-crlf-4.2.txt](https://github.com/Alexpux/MSYS2-packages/files/1708226/output-crlf-4.2.txt)
[output-lf-4.1.txt](https://github.com/Alexpux/MSYS2-packages/files/1708227/output-lf-4.1.txt)
[output-lf-4.2.txt](https://github.com/Alexpux/MSYS2-packages/files/1708228/output-lf-4.2.txt)
[empty.awk.txt](https://github.com/Alexpux/MSYS2-packages/files/1708243/empty.awk.txt)
The new gawk version has some problems when reading files with dos line endings.
The previous version worked fine, see attachments for comparison.
```
$ gawk -f empty.awk.txt <input-crlf.txt >output-crlf-4.2.txt
$ gawk -f empty.awk.txt <input-lf.txt >output-lf-4.2.txt
$ pacman -U /var/cache/pacman/pkg/gawk-4.1.4-2-x86_64.pkg.tar.xz
$ gawk -f empty.awk.txt <input-crlf.txt >output-crlf-4.1.txt
$ gawk -f empty.awk.txt <input-lf.txt >output-lf-4.1.txt
```

**Comment by orgads** [comment]
Fixed by https://github.com/Alexpux/MSYS2-packages/pull/1180 (some disagree this is a fix...)

**Comment by ssbssa** [comment]
I was hit by this problem when I built a cross-compiler.
In gcc/libgcc/Makefile.in is this:
```
# Map-file generation.
ifneq ($(SHLIB_MKMAP),)
libgcc.map.in: $(SHLIB_MAPFILES)
	{ cat $(SHLIB_MAPFILES) \
	    | sed -e '/^[ 	]*#/d' \
		  -e 's/^%\(if\|else\|elif\|endif\|define\)/#\1/' \
	    | $(gcc_compile_bare) -E -xassembler-with-cpp -; \
	} > tmp-$@
	mv tmp-$@ $@
libgcc.map: $(SHLIB_MKMAP) libgcc.map.in $(libgcc-s-objects)
	{ $(NM) $(SHLIB_NM_FLAGS) $(libgcc-s-objects); echo %%; \
	  cat libgcc.map.in; \
	} | $(AWK) -f $(SHLIB_MKMAP) $(SHLIB_MKMAP_OPTS) > tmp-$@
	mv tmp-$@ $@
libgcc_s$(SHLIB_EXT): libgcc.map
mapfile = libgcc.map
endif
```
And when SHLIB_MKMAP=mkmap-symver.awk, the script failed to create the libgcc.map when gawk 4.2.0 was used.

**Comment by svnpenn** [comment]
This change is intentional and necessary for portable Awk scripts.

http://cygwin.com/ml/cygwin/2017-08/msg00033.html

**Comment by svnpenn** [comment]
https://github.com/git-for-windows/git/issues/1524

**Comment by ssbssa** [comment]
@svnpenn I would consider that gcc makefile & the used awk script to be portable, but suddenly it didn't work any more.

**Comment by BudiKusasi** [comment]
open it on notepad++  look at bottom right to mid of status bar for linux/windows/mac newline mode, and click to get desired one and save it back your file

**Comment by ssbssa** [comment]
It works again with 4.2.1, so I'm closing this.
