### ISSUE TITLE
msys2-runtime conflicts with catgets on recent update

### ISSUE THREAD

**Issue by StarWolf3000** [Alexpux/MSYS2-packages#1147]
Trying to update `msys2-runtime` `2.9.0-2` to `2.10.0-2` and pacman wants to remove `catgets`, because its in conflict with `msys2-runtime`:
```
$ pacman -S mintty msys2-runtime{,-devel}
resolving dependencies...
looking for conflicting packages...
:: msys2-runtime and catgets are in conflict. Remove catgets? [y/N]
```
Is it safe to remove catgets, because
`$ pacman -Qi catgets`
returns:
```
Name            : catgets
Version         : 1.1-2
Description     : catgets message catalog API
Architecture    : x86_64
URL             : http://www.gnu.org/software/libc/
Licenses        : custom
Groups          : base
Provides        : None
Depends On      : libiconv  libintl  libcatgets
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 61,00 KiB
Packager        : Alexey Pavlov <alexpux@gmail.com>
Build Date      : Di, 4. Nov 2014 20:22:49
Install Date    : Mi, 16. Sep 2015 08:34:20
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```
?

**Comment by donkopotamus** [comment]
I wouldn't recommend it.  While doing an update today I removed `catgets` before updating the remainder of the package and was left with a very dysfunctional system.  Don't do it.

**Comment by lazka** [comment]
See #1141

**Comment by metiscus** [comment]
To distill this into something useful in case someone else ends up looking at this, it would appear that you need to run pacman --ask=20 at least the first time.

**Comment by letmaik** [comment]
Not working for me, removing libcatgets is not working if tcsh is installed:
```
$ pacman -Syu
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
:: Starting core system upgrade...
warning: terminate other MSYS2 programs before proceeding
resolving dependencies...
looking for conflicting packages...
:: msys2-runtime and catgets are in conflict. Remove catgets? [y/N] y
:: msys2-runtime and libcatgets are in conflict. Remove libcatgets? [y/N] y
error: failed to prepare transaction (could not satisfy dependencies)
:: tcsh: removing libcatgets breaks dependency 'libcatgets'
```

**Comment by letmaik** [comment]
The suggestion in https://github.com/Alexpux/MSYS2-packages/issues/1166#issuecomment-366511826 works...

**Comment by jay** [comment]
I also received this message today, "msys2-runtime and catgets are in conflict". I don't understand how #1141 addresses this and #1166 doesn't apply because I don't have tcsh installed. What is the solution, remove catgets?

**Comment by StarWolf3000** [comment]
I did remove it on update, did not break anything in my case (I broke my environment afterwards, but the cause is a different one and not related to this one).

**Comment by jay** [comment]
Thanks, I did pacman -R catgets and libcatgets and then the update finished successfully. As far as I can tell this only breaks old tcsh, the updated tcsh no longer uses libcatgets.

**Comment by silvioprog** [comment]
Same problem here. I fixed it using:

```bash
pacman -R libcatgets
```
