### ISSUE TITLE
ssh and ssh-keygen default directories

### ISSUE THREAD

**Issue by WscriChy** [Alexpux/MSYS2-packages#115]
When I create a key with ssh-keygen a new key is writren to C:\Users<UserName>.ssh.

But when I use ssh I always get an error

```
Could not create directory '/home/<UserName>/.ssh'.
```

Seems like it tries to access <msys-installation-directory>/home/<UserName/.ssh path.

How to deal with this confusing behavior?

**Comment by elieux** [comment]
Edit `/etc/nsswitch.conf` and insert `windows` between `db_home:` and `cygwin`. References:
https://cygwin.com/cygwin-ug-net/ntsec.html#ntsec-mapping-nsswitch
https://cygwin.com/faq/faq.html#faq.setup.home
