### ISSUE TITLE
Upgrading filesystem stops MSys2 from starting in $HOME

### ISSUE THREAD

**Issue by agkozak** [Alexpux/MSYS2-packages#1155]
This morning I ran `pacman -Syu`. As soon as I upgraded to `filesystem-2018.02-1-x86_64.pkg.tar.xz`, MSys2 stopped opening in the `$HOME` directory. `$HOME` was set to the right directory; I could `cd $HOME`, and it worked.

I fiddled around with `/etc` files for a while but couldn't identify what had changed. Downgrading to `filesystem-2017.05-1-x86_64.pkg.tar.xz` fixed the problem.

Any ideas? Thanks.

**Comment by agkozak** [comment]
I should note that my `$HOME` directory is mounted in `fstab`, which has

    C:/Users /home ntfs binary,noacl,auto 1 1

so that my Windows user directory can also be my MSys2 user directory. This always worked before. I suspect that issue #1162 may point to the same problem.

**Comment by elieux** [comment]
Try this:

1. close every MSYS2 process
2. open a command prompt in `usr\bin`
3. run `strace -o C:\trace.txt bash`
4. look for "mount_info" in `trace.txt`, maybe even post the file

**Comment by agkozak** [comment]
Thanks, @elieux. Everything mounts correctly.

I figured out what is going on.

I see that in `msys2_shell.cmd` we have `set CD_HOME=yes`. But I always launch MSys2 using a shortcut that has `C:\tools\msys64\usr\bin\mintty.exe /bin/zsh --login -i`, so CD_HOME presumably isn't getting set.

If I set the Windows environment variable `CD_HOME` to `yes` before launching `mintty`, everything works properly.

What do you think changed?

**Comment by elieux** [comment]
> What do you think changed?

I guess this happened: https://github.com/Alexpux/MSYS2-packages/pull/1151

Then this happened:https://github.com/Alexpux/MSYS2-packages/pull/1154

Maybe it's fixed now.

-- 
David Macek

**Comment by agkozak** [comment]
Thanks, @elieux. It would appear to be fixed now. I'll close this issue.
