### ISSUE TITLE
Cannot recognize fstab file after upgrading

### ISSUE THREAD

**Issue by michaelHL** [Alexpux/MSYS2-packages#1162]
Here's my `fstab` file:

```
# For a description of the file format, see the Users Guide
# http://cygwin.com/cygwin-ug-net/using.html#mount-table

# DO NOT REMOVE NEXT LINE. It remove cygdrive prefix from path
none / cygdrive binary,posix=0,noacl,user 0 0
C:\Users\Michael\Desktop /desktop
F:\WorkingDirectory\Work\__current /current
```

After upgrading MSYS2 by `pacman -Syu`, there's no word about `desktop` or `current` after typing `cd /<tab>`, that is, the `fstab` file would not work after upgrading. (maybe due to `filesystem-2018.02-1`, but it's still no use downgrading this package to `filesystem-2017.05-1`)

**Comment by elieux** [comment]
Try following the defined `fstab` format<https://cygwin.com/cygwin-ug-net/using.html#mount-table>.  If impatient, scroll a bit to "Example entries".  Your 2 entries should be:

```
C:/Users/Michael/Desktop /desktop ntfs binary,noacl 0,0
F:/WorkingDirectory/Work/__current /current ntfs binary,noacl 0,0
```

-- 
David Macek

**Comment by michaelHL** [comment]
@elieux Thanks! But the problem is still there after updating my `fstab` file...
And this issue is something like #1155

**Comment by elieux** [comment]
Try this:

1. close every MSYS2 process
2. open a command prompt in `usr\bin`
3. run `strace -o C:\trace.txt bash`
4. look for "mount_info" in `trace.txt`, maybe even post the file

**Comment by michaelHL** [comment]
@elieux Here's the [gist](https://gist.github.com/anonymous/0d99a3aa21ba5fa4a65bfa9cbc3756fe).
And I found it's alright after upgrading the `filesystem` package again :sweat_smile:
But there's another problem: the directory after entering bash is `/` instead of `~` (`$HOME`) (same as #1155 ), so this issue should be closed. Thanks! 😄
