### ISSUE TITLE
Synchronize -Sy issue

### ISSUE THREAD

**Issue by BudiKusasi** [Alexpux/MSYS2-packages#1166]
I synchronized with pacman -Sy just hours from now, then when i typed:

`$ pacman -Ss sort`
it did nothing, and back to prompt.
So I Install the MSYS2 standalone installer again now to a new location and named a dir. say M2, and compare each usr/bin dir. of theirs (old dir is, say, MSYS)
In MSYS dir, all are as the same timestamp or newer than M2, one of that newer is pacman.exe which is in trouble said above. So I copy pacman from M2 to MSYS overwriting it... right was fixing as good pacman before and uninstall the M2 and clear it, but...
I run the fixed pacman in MSYS;
```
$ pacman -Syu
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
:: Starting core system upgrade...
warning: terminate other MSYS2 programs before proceeding
resolving dependencies...
looking for conflicting packages...
:: msys2-runtime and catgets are in conflict. Remove catgets? [y/N] y
:: msys2-runtime and libcatgets are in conflict. Remove libcatgets? [y/N] y
error: failed to prepare transaction (could not satisfy dependencies)
:: tcsh: removing libcatgets breaks dependency 'libcatgets'

```

Have you experienced this and How to solve it ?
For the sincere help will be really appreciated.. Thanks so much in advance

**Comment by Ede123** [comment]
You should be able to fix it by removing tcsh first, then doing the upgrade and then re-installing tcsh if required.
