### ISSUE TITLE
`db_home: windows` have to effect

### ISSUE THREAD

**Issue by kflu** [Alexpux/MSYS2-packages#1167]
I specified `db_home: windows` in `/etc/nsswitch.conf`. However, msys2.exe insists to create and use `/home/<username>`. 

What may matter is that it is a domain-joined machine. I don't know how this will affect it but if it does matter, please let me know what additional info you need for diagnosis.

uname: `MSYS_NT-10.0 foobar 2.10.0(0.325/5/3) 2018-02-09 15:25 x86_64 Msys`

Here's my `nsswitch.conf`:

```
# Begin /etc/nsswitch.conf

passwd: files db
group: files db

db_enum: cache builtin

#db_home: env windows cygwin desc
db_home: windows
db_shell: cygwin desc
db_gecos: cygwin desc

# End /etc/nsswitch.conf
```

**Comment by kflu** [comment]
FWIW I used the below as a work around and it works OK:

    db_home: windows /c/Users/%U

But I really prefer not to use any workaround.

**Comment by elieux** [comment]
Are you sure the cited `nsswitch.conf` didn't work?  I just tested mine and while it seems the parser could be improved, a `db_home: windows` line should unambiguously work. Can you check what strace(*) says?

*) close all MSYS2 processes, open command line, navigate to `...\usr\bin`, run `strace -o _trace cat` and look for `db_home` in `_trace`.

**Comment by kflu** [comment]
Thanks for the pointer. I’ll try to get the trace tonight.

**Comment by kflu** [comment]
OK this is strange. I can't seem to reproduce this issue now. I tried with `db_home: windows` and it gives me the desired home path.

**Comment by elieux** [comment]
Well, at least it works. :)  Thanks for reporting back.

**Comment by Geoffrey-A** [comment]
I had the same issue. I don’t think I had any match for `db_home` in the `_trace` file produced with the above method.
However I found a solution by looking at  https://github.com/Alexpux/Cygwin/pull/6/commits/5543a0a:
```
db_home: env

**Comment by nopeless** [comment]
> FWIW I used the below as a work around and it works OK:
> 
> ```
> db_home: windows /c/Users/%U
> ```
> 
> I was inspired by [this SO answer](https://stackoverflow.com/questions/10087151/make-cygwin-home-directory-to-windows-user-profile/31839331#31839331). But I really prefer not to use any workaround.

Interestingly, setting `db_home: windows` for me didn't work either, and only worked after i set `db_home: windows /c/Users/%U`. Then, after reverting it back to `db_home: windows`, it still works

So... thanks for saying this? I have no idea why it happens but I'm leaving my experience too

---

Edit: I came  back to this exact github issue because it wasn't working. I accidentally deleted `db` from `group`, `group: files db` is correct
