### ISSUE TITLE
tools get so slow outside MSYS2 shell

### ISSUE THREAD

**Issue by kelvinh** [Alexpux/MSYS2-packages#117]
Hi,

I am sorry if this is not the proper place for this question.

The tools (like `cp`, `mv`, `cat`, etc.) work smoothly under the MSYS2 shell, but when I try to launch them under Windows *cmd*, they will take too long to response. For example, open Windows cmd console and cd to **%MSYS2_ROOT%\usr\bin**, input `mv` and hit enter, it takes almost 10 seconds to output the help info of mv...

I am new to MSYS2 and it is really great, I just want to use it everywhere, not only under MSYS2 shell, is it possible? Or, is there any workaround to achieve this?

Thanks,
Kelvin

**Comment by juergenpf** [comment]
I see the same problem for a few weeks now on my work machine in our corporate network where we have an Active Directory with a very elaborated group membership structure, which means I'm a member in tons of groups and to start a MSYS2 shell takes minutes (5-10 min), which makes it unusable in such an environment. To be honest, this is a weak design/implementation by the cygwin folks.

**Comment by maoueh** [comment]
@juergenpf Checkout this issue https://github.com/Alexpux/MSYS2-packages/issues/138 where users seems to have workaround the problem by commenting `db` in their `nsswitch.conf` file.

Not sure if this will work on your case, good luck.

**Comment by legends2k** [comment]
@maoueh Thanks for the tip, it did solve the issue for me, but with a small tweak, which I'd written on #138's page.

**Comment by kelvinh** [comment]
Yeah, after disable `db` in `nsswitch.conf`, those commands work great also in Windows cmd! Also, there is a great article describes this problem and gives a solution: http://bjg.io/guide/cygwin-ad/.

Thanks for all of you, closing the long live issue now.

**Comment by vnluc** [comment]
@kelvinh 
Thank you, the article saved me. I also got issue and after comment the db option. It works again

**Comment by kelvinh** [comment]
@vnluc Glad it works. :)

**Comment by lanzkron** [comment]
@kelvinh excuse the stupid question... where is nsswitch.conf located on Windows?

**Comment by vnluc** [comment]
@kelvinh :
It is in  "etc" folder in your installation.

**Comment by kelvinh** [comment]
@lanzkron **/etc/nsswitch.conf** under MSYS2 installation folder.
