### ISSUE TITLE
bsdtar extraction failure

### ISSUE THREAD

**Issue by okhlybov** [Alexpux/MSYS2-packages#1174]
Bsdtar fails to unpack tarballs with symlinks.

For an example of the offending file refer to http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.8.3.tar.gz

```shell
$ bsdtar xzf petsc-lite-3.8.3.tar.gz
petsc-3.8.3/src/mat/impls/aij/seq/seqviennaclcuda/aijviennaclcuda.cu: Can't create 'petsc-3.8.3/src/mat/impls/aij/seq/seqviennaclcuda/aijviennaclcuda.cu'
....
bsdtar: Error exit delayed from previous errors.
```

**Comment by Alexpux** [comment]
As workaround unpack sources in prepare function. You can look into qt-creator package for example.
MSYS2 by default not support symlinkls
