### ISSUE TITLE
irssi: missing library

### ISSUE THREAD

**Issue by djdv** [Alexpux/MSYS2-packages#1189]
```
$ irssi
C:/msys64/usr/bin/irssi.exe: error while loading shared libraries: msys-ssp-0.dll: cannot open shared object file: No such file or directory
```
It looks like `gcc-libs` originally had this dll but no longer provides it, I'm not sure if `gcc-libs` was ever a dependency of `irssi` or not to begin with though, so I'm not sure when this became a problem or which package change caused it.

**Comment by djdv** [comment]
The package builds and runs fine with `makepkg`, it may just have to be rebuilt for the repository.

**Comment by lazka** [comment]
A rebuild is in the repo, can you test it?

**Comment by djdv** [comment]
@lazka 
Works on my machine. Thanks.
