### ISSUE TITLE
Msys2.exe don't open inside ConEmu; no text selection running mintty

### ISSUE THREAD

**Issue by KrullBorg** [Alexpux/MSYS2-packages#1215]
- msys.exe, mingw32.exe and mingw64.exe setted as conemu tasks don't open inside the conemu window
- so i'm using the old method "set MSYSTEM=MINGW64 & set MSYSCON=mintty.exe & C:\msys64\usr\bin\mintty -i /msys2.ico /usr/bin/bash --login" but in this way it's not longer possibile to select text with mouse drag but only with double click

**Comment by elieux** [comment]
This should work: https://superuser.com/a/1297072

The .exe launchers are not supposed to be used *inside* other emulators.  At least not yet.

-- 
David Macek

**Comment by KrullBorg** [comment]
thanks it works
