### ISSUE TITLE
msys/filesystem 2018.04-1 breaks autoconf

### ISSUE THREAD

**Issue by JPeterMugaas** [Alexpux/MSYS2-packages#1231]
One issue I've noticed with the new file system update is that it breaks some configure scripts like the one in ISL.

I noted this in config.guess

src/isl-0.19/config.guess:850:  echo ${UNAME_MACHINE}-pc-mingw64

 I get this:

configure: loading site script /etc/config.site
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/jpmugaas/exp/mingw-w64-isl/src/build-x86_64-w64-mingw32':
configure: error: C compiler cannot create executables
See `config.log' for more details
====

log output:
====
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by isl configure 0.19, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ../isl-0.19/configure --prefix=/mingw64 --build=x86_64-w64-mingw32 --enable-static --disable-shared --with-gmp-prefix=/mingw64

## --------- ##

hostname = agnus2
uname -m = x86_64
uname -r = 2.10.0(0.325/5/3)
uname -s = MINGW64_NT-10.0
uname -v = 2018-02-09 15:25

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = x86_64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /mingw64/bin
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /bin
PATH: /c/Windows/System32
PATH: /c/Windows
PATH: /c/Windows/System32/Wbem
PATH: /c/Windows/System32/WindowsPowerShell/v1.0/
PATH: /usr/share/java/gradle/bin
PATH: /usr/bin/site_perl
PATH: /usr/bin/vendor_perl
PATH: /usr/bin/core_perl

## ----------- ##

configure:2727: loading site script /etc/config.site
| # This file is in public domain.
| # Original author: Karlson2k (Evgeny Grin)
| # Written for MSys2 to help running 'configure' scripts
| 
| # Use correct config.site even if CONFIG_SITE is not set
| if test "x$MSYSTEM" = "xMINGW64"; then
|   if test -r "${MINGW_PREFIX-/mingw64}/etc/config.site"; then
|     . "${MINGW_PREFIX-/mingw64}/etc/config.site"
|   fi
| elif test "x$MSYSTEM" = "xMINGW32"; then
|   if test -r "${MINGW_PREFIX-/mingw32}/etc/config.site"; then
|     . "${MINGW_PREFIX-/mingw32}/etc/config.site"
|   fi
| else
|   # Defaults for MSys2-targeted programs
| 
|   # Set proper selfname on bash and fallback to default name on other shells
|   test -n "${BASH_SOURCE}" 2>/dev/null && config_site_me="${BASH_SOURCE[0]##*/}" || config_site_me=config.site
| 
|   # Set default 'host' to speedup configure
|   if test -z "$build_alias"; then
|     build_alias="${MSYSTEM_CARCH-x86_64}-pc-msys"  && \
|       $as_echo "$config_site_me:${as_lineno-$LINENO}: default build_alias set to $build_alias" >&5 
|   fi
| 
|   # Set default 'prefix' to "/usr"
|   if ( test -z "$prefix" || test "x$prefix" = "xNONE" ) && \
|      ( test -z "$exec_prefix" || test "x$exec_prefix" = "xNONE" ); then
|     prefix="${MSYSTEM_PREFIX-/usr}" && \
|       $as_echo "$config_site_me:${as_lineno-$LINENO}: default prefix set to $prefix" >&5
|   fi
| 
| fi
configure:2869: checking for a BSD-compatible install
configure:2937: result: /usr/bin/install -c
configure:2948: checking whether build environment is sane
configure:3003: result: yes
configure:3154: checking for a thread-safe mkdir -p
configure:3193: result: /usr/bin/mkdir -p
configure:3200: checking for gawk
configure:3216: found /usr/bin/gawk
configure:3227: result: gawk
configure:3238: checking whether make sets $(MAKE)
configure:3260: result: yes
configure:3289: checking whether make supports nested variables
configure:3306: result: yes
configure:3443: checking whether make supports nested variables
configure:3460: result: yes
configure:3534: checking for gcc
configure:3550: found /mingw64/bin/gcc
configure:3561: result: gcc
configure:3790: checking for C compiler version
configure:3799: gcc --version >&5
gcc.exe (Rev2, Built by MSYS2 project) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:3810: $? = 0
configure:3799: gcc -v >&5
Using built-in specs.
COLLECT_GCC=D:\msys64\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-7.3.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-time=yes --enable-libstdcxx-filesystem-ts=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev2, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 7.3.0 (Rev2, Built by MSYS2 project) 
configure:3810: $? = 0
configure:3799: gcc -V >&5
gcc.exe: error: unrecognized command line option '-V'
gcc.exe: fatal error: no input files
compilation terminated.
configure:3810: $? = 1
configure:3799: gcc -qversion >&5
gcc.exe: error: unrecognized command line option '-qversion'; did you mean '--version'?
gcc.exe: fatal error: no input files
compilation terminated.
configure:3810: $? = 1
configure:3830: checking whether the C compiler works
configure:3852: gcc -march=x86-64 -mtune=generic -O2 -pipe -D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 -pipe conftest.c  >&5
gcc.exe: error: CreateProcess: No such file or directory
configure:3856: $? = 1
configure:3894: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "isl"
| #define PACKAGE_TARNAME "isl"
| #define PACKAGE_VERSION "0.19"
| #define PACKAGE_STRING "isl 0.19"
| #define PACKAGE_BUGREPORT "isl-development@googlegroups.com"
| #define PACKAGE_URL ""
| #define PACKAGE "isl"
| #define VERSION "0.19"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3899: error: in `/home/jpmugaas/exp/mingw-w64-isl/src/build-x86_64-w64-mingw32':
configure:3901: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##

ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value='-march=x86-64 -mtune=generic -O2 -pipe'
ac_cv_env_CPPFLAGS_set=set
ac_cv_env_CPPFLAGS_value='-D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1'
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXCPP_set=
ac_cv_env_CXXCPP_value=
ac_cv_env_CXXFLAGS_set=set
ac_cv_env_CXXFLAGS_value='-march=x86-64 -mtune=generic -O2 -pipe'
ac_cv_env_CXX_set=
ac_cv_env_CXX_value=
ac_cv_env_LDFLAGS_set=set
ac_cv_env_LDFLAGS_value=-pipe
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_LT_SYS_LIBRARY_PATH_set=
ac_cv_env_LT_SYS_LIBRARY_PATH_value=
ac_cv_env_PYTHON_set=
ac_cv_env_PYTHON_value=
ac_cv_env_build_alias_set=set
ac_cv_env_build_alias_value=x86_64-w64-mingw32
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/usr/bin/mkdir
ac_cv_prog_AWK=gawk
ac_cv_prog_ac_ct_CC=gcc
ac_cv_prog_make_make_set=yes
am_cv_make_support_nested_variables=yes

## ----------------- ##

ACLOCAL='${SHELL} /home/jpmugaas/exp/mingw-w64-isl/src/isl-0.19/missing aclocal-1.15'
AMDEPBACKSLASH=''
AMDEP_FALSE=''
AMDEP_TRUE=''
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='0'
AM_V='$(V)'
AR=''
AUTOCONF='${SHELL} /home/jpmugaas/exp/mingw-w64-isl/src/isl-0.19/missing autoconf'
AUTOHEADER='${SHELL} /home/jpmugaas/exp/mingw-w64-isl/src/isl-0.19/missing autoheader'
AUTOMAKE='${SHELL} /home/jpmugaas/exp/mingw-w64-isl/src/isl-0.19/missing automake-1.15'
AWK='gawk'
CC='gcc'
CCDEPMODE=''
CFLAGS='-march=x86-64 -mtune=generic -O2 -pipe'
CLANG_CXXFLAGS=''
CLANG_LDFLAGS=''
CLANG_LIBS=''
CPP=''
CPPFLAGS='-D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1'
CXX=''
CXXCPP=''
CXXDEPMODE=''
CXXFLAGS='-march=x86-64 -mtune=generic -O2 -pipe'
CYGPATH_W='cygpath -w'
DEFS=''
DEPDIR=''
DLLTOOL=''
DSYMUTIL=''
DUMPBIN=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
EXEEXT=''
FGREP=''
GENERATE_DOC_FALSE=''
GENERATE_DOC_TRUE=''
GIT_HEAD=''
GIT_HEAD_ID=''
GIT_HEAD_VERSION=''
GMP_FOR_MP_FALSE=''
GMP_FOR_MP_TRUE=''
GREP=''
HAVE_CLANG_FALSE=''
HAVE_CLANG_TRUE=''
HAVE_PYTHON_FALSE=''
HAVE_PYTHON_TRUE=''
IMATH_FOR_MP_FALSE=''
IMATH_FOR_MP_TRUE=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LD=''
LDFLAGS='-pipe'
LIBOBJS=''
LIBS=''
LIBTOOL=''
LIB_CLANG_EDIT=''
LIPO=''
LN_S=''
LTLIBOBJS=''
LT_SYS_LIBRARY_PATH=''
MAKEINFO='${SHELL} /home/jpmugaas/exp/mingw-w64-isl/src/isl-0.19/missing makeinfo'
MANIFEST_TOOL=''
MKDIR_P='/usr/bin/mkdir -p'
MP_CPPFLAGS=''
MP_LDFLAGS=''
MP_LIBS=''
NEED_GET_MEMORY_FUNCTIONS_FALSE=''
NEED_GET_MEMORY_FUNCTIONS_TRUE=''
NM=''
NMEDIT=''
OBJDUMP=''
OBJEXT=''
OTOOL64=''
OTOOL=''
PACKAGE='isl'
PACKAGE_BUGREPORT='isl-development@googlegroups.com'
PACKAGE_NAME='isl'
PACKAGE_STRING='isl 0.19'
PACKAGE_TARNAME='isl'
PACKAGE_URL=''
PACKAGE_VERSION='0.19'
PATH_SEPARATOR=':'
PDFLATEX=''
PERL=''
POD2HTML=''
PRTDIAG=''
PYTHON=''
PYTHON_EXEC_PREFIX=''
PYTHON_PLATFORM=''
PYTHON_PREFIX=''
PYTHON_VERSION=''
RANLIB=''
SED=''
SET_MAKE=''
SHELL='/bin/sh'
SMALL_INT_OPT_FALSE=''
SMALL_INT_OPT_TRUE=''
STRIP=''
VERSION='0.19'
WARNING_FLAGS=''
ac_ct_AR=''
ac_ct_CC='gcc'
ac_ct_CXX=''
ac_ct_DUMPBIN=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__fastdepCXX_FALSE=''
am__fastdepCXX_TRUE=''
am__include=''
am__isrc=' -I$(srcdir)'
am__leading_dot='.'
am__nodep=''
am__quote=''
am__tar='$${TAR-tar} chof - "$$tardir"'
am__untar='$${TAR-tar} xf -'
bindir='${exec_prefix}/bin'
build='x86_64-w64-mingw32'
build_alias='x86_64-w64-mingw32'
build_cpu=''
build_os=''
build_vendor=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host=''
host_alias=''
host_cpu=''
host_os=''
host_vendor=''
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /home/jpmugaas/exp/mingw-w64-isl/src/isl-0.19/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
llvm_config_found=''
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(MKDIR_P)'
oldincludedir='/usr/include'
pdfdir='${docdir}'
pkgconfig_libdir=''
pkgconfig_libfile=''
pkgpyexecdir=''
pkgpythondir=''
prefix='/mingw64'
program_transform_name='s,x,x,'
psdir='${docdir}'
pyexecdir=''
pythondir=''
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''
versioninfo='19:0:0'

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "isl"
#define PACKAGE_TARNAME "isl"
#define PACKAGE_VERSION "0.19"
#define PACKAGE_STRING "isl 0.19"
#define PACKAGE_BUGREPORT "isl-development@googlegroups.com"
#define PACKAGE_URL ""
#define PACKAGE "isl"
#define VERSION "0.19"

configure: exit 77
====

**Comment by mati865** [comment]
Please put code in ` ``` ` to make it readable.

**Comment by JPeterMugaas** [comment]
Alright, I think the change in the most recent filesystem package broke some build systems that relied on the old "pc" value but now I'm not so completely sure because there was some other screw up and it seems have to cleared after a reboot.
