### ISSUE TITLE
libgfortran-3.dll missing but libgfortran-4.dll is present

### ISSUE THREAD

**Issue by prechtl** [Alexpux/MSYS2-packages#1241]
I'm trying to implement the LAPACK libraries in a Visual Studio project on Windows 10.  As part of the process, I first installed MSYS2 and, within that shell, used pacman to install a number of packages.  One package in particular needed to run the LAPACK code is the gfortran library.  Within Msys2 I have used commands like:
`pacman -S mingw-w64-x86_64_toolchain`

and, more specifically
`pacman -S mingw-w64-x86_64-gcc-fortran`

in addition to a number of other package installations.  The result of these operations is that within my C:\msys64\mingw64\bin\ folder is a libgfortran-4.dll library but no libgfortran-3.dll.

With this bin folder in my system path, I go to run my Visual Studio C++ code that calls the LAPACK commands like `dgesv_`.  However, upon running it, I get the runtime error:

> The code execution cannot proceed because libgfortran-3.dll was not found.  

I presume that I need to run the appropriate pacman command to install the '-3' version of the libgfortran library.  Can anyone tell me what package to install (or set of steps I should perform) within the MSYS2 shell (or MSYS MinGW 64-bit shell) to get this library to install?

**Comment by mati865** [comment]
There is no `libgfortran-3.dll` available, some dependency has to be rebuilt to use `libgfortran-4.dll`.

**Comment by prechtl** [comment]
But I'm referencing a pre-packaged library (LAPACK)...  What dependency?  And how would I rebuild it?

**Comment by Alexpux** [comment]
Laps k not builded for a long time because openblas superseedes it
