### ISSUE TITLE
please add httpie

### ISSUE THREAD

**Issue by eromoe** [Alexpux/MSYS2-packages#1246]
https://github.com/jakubroztocil/httpie

I don't find this package, have to install by pip.

**Comment by StarWolf3000** [comment]
Don't think that will be provided here as MSYS2 package, as httpie IS a PIP package, not some source package. According to its Makefile, it utilises PIP to install itself even on Linux and mac OS.

The prebuilt packages for several Linux distributions and mac OS just install it using PIP.
