### ISSUE TITLE
Update python3-pyopenssl

### ISSUE THREAD

**Issue by lovetox** [Alexpux/MSYS2-packages#1259]
The version is more than a year old, please update it

**Comment by Alexpux** [comment]
@lovetox issues creating for problems with programs, not for request updates

**Comment by lovetox** [comment]
So where should we then request updates?

**Comment by lovetox** [comment]
i dont find any files related to python3-openssl or python3-cryptography

where are the PKGBUILD files for these packages? or does the process work differently for these packages

**Comment by Alexpux** [comment]
Usually we have one PKGBUILD for both python 2 & 3, so you need find folder python-openssl

**Comment by Alexpux** [comment]
Read package name carefully and you will find folder:
https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-python-pyopenssl
