### ISSUE TITLE
Ghostscript error while loading shared libraries

### ISSUE THREAD

**Issue by jambonmcyeah** [Alexpux/MSYS2-packages#1261]
```
jambon@MYCOMPUTER MINGW64 /mingw64/bin
$ gs
C:/msys64/mingw64/bin/gs.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

**Comment by StarWolf3000** [comment]
Run the Ghostscript binary outside of the MSYS2 terminal (in cmd.exe for example) to see which libraries are actually missing for you.

**Comment by jambonmcyeah** [comment]
libidn-11.dll is missing

**Comment by StarWolf3000** [comment]
Is your mingw64/mingw-w64-x86_64-ghostscript up to date? There's a mismatch between the latest mingw64/mingw-w64-x86_64-libidn (1.35-1 provides libidn-12.dll) and your Ghostscript (requires libidn-11.dll).
mingw64/mingw-w64-x86_64-libidn version 1.34-1 provides libidn-11.dll.

**Comment by jambonmcyeah** [comment]
Yeah, I did a pacman -Syu and everything is up to date

**Comment by StarWolf3000** [comment]
Looks like Ghostscript is linked against the older libidn, and a dependency for the package is missing. pacman should not allow an update, if it breaks dependecies in this case.

(Also, next time you should post this in Alexpux/MINGW-Packages, its a MINGW issue, not MSYS2.)

**Comment by jambonmcyeah** [comment]
Sorry, I didn't know there's a separate git repo for mingw packages

**Comment by jambonmcyeah** [comment]
I built the package myself and it worked
