### ISSUE TITLE
MSYS2 philosophy

### ISSUE THREAD

**Issue by d3vv** [Alexpux/MSYS2-packages#1264]
Why msys2  has no <conio.h> but mingw has?
Why we can't recompile only needed functions from msys2.dll into one exe binary with -static build?
Why we can't to use screen against tmux but cygwin can?

**Comment by Alexpux** [comment]
1. MSYS2 is similar t oCygwin
2. Cygwin dont officially support static linking with its dll
3. MSYS2 dont support XServer
