### ISSUE TITLE
MSYS2 ruby is stalled at 2.4.0-2

### ISSUE THREAD

**Issue by OTLabs** [Alexpux/MSYS2-packages#1266]
I have installed ruby in MSYS2 some time ago, it was at version 2.4.0-2. I see that at https://github.com/Alexpux/MSYS2-packages/tree/master/ruby version 2.5.0 is avalable. I am unable to update to this version with pacman:
`$ pacman -Q ruby
ruby 2.4.0-2

$ pacman -S ruby
warning: ruby-2.4.0-2 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) ruby-2.4.0-2

Total Installed Size:  16.16 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n]`

It would be nice to get ruby updated to version 2.5.1 too. Thank you!

**Comment by Alexpux** [comment]
@OTLabs 32-bit ruby on MSYS/Cygwin crashing:
https://bugs.ruby-lang.org/issues/13999

**Comment by Alexpux** [comment]
Ruby 2.6.0 in repo now
