### ISSUE TITLE
Tab completion causing syntax error

### ISSUE THREAD

**Issue by wolf99** [Alexpux/MSYS2-packages#1273]
- I have installed MSYS2 recently on a fresh MS Windows 7 (64-bit) machine. 
- I followed this up with an install of Python - on Windows via an executable installer from python.org rather than via pacman (have tried an install to the MinGW64 system with pacman also, but nothing changes). 
- I ensure python is available on the windows PATH.
- I make the Windows PATH available in MSYS by un-commenting the set `MSYS2_PATH_TYPE=inherit` line in the `msys2_shell.cmd` file.

- I create a test python file `test.py`:

    ```python
    #! /usr/bin/env python

    print("Hello, world!")
    ```

I can run this with the following at the MSYS2 MinGW64 prompt (though the problem seems to occur in MSYS bash too) like so:

```bash
$ ./test.py
Hello, world!
```

However, if I attempt to pass a path argument to the script and try to use tab completion while constructing that path, the shell outputs an odd syntax error:

```bash
$ ./test.py ./te<tab>bash: test.py: syntax error: invalid arithmetic operator (error token is ".py")
$
```
Obviously the expected behavior is that hitting the tab key causes the path to be completed, rather than any error being printed on the line.

I had a similar (not confident it's exactly the same) setup on a machine only a couple months ago that worked just fine.

Have I configured something incorrectly or is this a bug?

**Comment by MirKml** [comment]
It seems it's related to new msys2 build  - 052018 - with upgraded bash_completion #1282
