### ISSUE TITLE
new msys2 distribution - error in bash completion

### ISSUE THREAD

**Issue by MirKml** [Alexpux/MSYS2-packages#1282]
There is some problem with new msys2 distribution - msys2-x86_64-20180531.exe.
After clean install, when I trying to make bash completion for e.g. `cmd`, I write

    $ cmd

then TAB - I see `$ cmd.exe`, then next TAB, I expect completion for current directory files, but I see some error message like `Bash : expression recursion level exceeded (error token is …)` ...

There is no such problem with previous msys - msys2-x86_64-20161025.exe.

Same problem is with completion for many more commands.

Note: old msys2-x86_64-20161025.exe can be executed without manually raised administration privilege, msys2-x86_64-20180531.exe requires manually "run as administrator". Call msys2-x86_64-20180531.exe without elevated privilege makes nothing.

**Comment by MirKml** [comment]
If old msys (msys2-x86_64-20161025.exe) is installed and you upgrade system later (pacman -Syuu). Problem is raised too.
Simpler reproducible step then in previous comment

Type `$cmd<space>` then press TAB and you will see

    $ cmd bash: cmd: expression recursion level exceeded (error token is "cmd")

Also `git gui` is broken, maybe it's related this issue. I will wait for fix for this one and tried later.

**Comment by Alexpux** [comment]
@MirKml git-gui problem is not related. Git-gui need tcl/to package that not present in msys2 and will not be.
About bash problem try to downgrade bash-completion package to 2.5

**Comment by MirKml** [comment]
@Alexpux thank you for tip for downgrade I will try.

git-gui - I know, I run git-gui under mingw shell, and there was no error before upgrade whole msys2 and all packages. But it works fine under old mingw shell with tcl/tk which were installed in old msys2-x86_64-20161025, so maybe it's also related to upgrade. Nowadays it returns this error message box and doesn't work at all.

```
fatal: Invalid path '/c/repos/src': No such file or directory
fatal: Invalid path '/c/repos/src': No such file or directory
    while executing
"close $fd"
    (procedure "git" line 5)
    invoked from within
"git mktree << {}"
    (procedure "PARENT" line 9)
    invoked from within
"PARENT"
    (procedure "rescan_stage2" line 30)
    invoked from within
"rescan_stage2 file3eea110 ui_ready"
```

**Comment by MirKml** [comment]
Downgrade bash_completion to 2.5 solves the issue. But maybe try to fix in upstream or try to patch.

For git-gui it's definitely for another own issue. I'll make later if necessry. 

So you can close this one.
Thanks

**Comment by Alexpux** [comment]
@MirKml git-gui is broken for a long time because of changes in git itself. You can try to fix it yourself and send us a solution

**Comment by Alexpux** [comment]
@MirKml you can try to find issue with bash-completion and create patch for it

**Comment by Alexpux** [comment]
@MirKml I hope this https://github.com/Alexpux/MSYS2-packages/commit/20e6465ceade353305b9d5b699337cd94943b430 solve problems

**Comment by MirKml** [comment]
new bash_completion package (2.8.2) works good, thank you alex

**Comment by jpmaterial** [comment]
Works for me too, but why is 20180531 still the default version on msys2.org?

**Comment by StarWolf3000** [comment]
@jpmaterial Because nobody has updated the website so far.

**Comment by jpmaterial** [comment]
Well, let me just share that I downloaded the version linked on the website, ran into this problem and had to google to find this issue. That makes msys2 look unnecessarily bad which is vexing since the bulk of work is already done.

**Comment by dlwlb** [comment]
FYI: I installed msys2-x86_64-20190524.exe and got bash-completion 2.9-1.
