### ISSUE TITLE
mingw-w64-x86_64-mpv is missing dep on mingw-w64-x86_64-zimg

### ISSUE THREAD

**Issue by Diablo-D3** [Alexpux/MSYS2-packages#1290]
mpv complains that libzimg-2.dll is missing until the package is installed.

**Comment by Alexpux** [comment]
````vapoursynth```` package denends on ````zimg```` package that contains ````libzimg-2.dll````.
````mpv```` package depends on ````vapoursynth```` so all need to be ok.

**Comment by Diablo-D3** [comment]
Yet I had a brand new install, installed mpv, dep was still missing. Maybe wrong package blamed?

**Comment by Diablo-D3** [comment]
@mati865 Yes, this is how I discovered which library was missing in the first place.

**Comment by mati865** [comment]
I think I misunderstood, it still shows the same dep missing?

**Comment by Diablo-D3** [comment]
@mati865 pacman seems to be convinced it is not a dep, because `pacman -Qi mingw-w64-x86_64-vapoursynth` or `mingw-w64-x86_64-mpv` does not list zimg as a dep.

**Comment by mati865** [comment]
https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-vapoursynth/PKGBUILD has only `makedepends` provided. It definitely depends on `ffmpeg`, `libass`, `libzimg` and something more.

**Comment by Alexpux** [comment]
Fixed by https://github.com/Alexpux/MINGW-packages/commit/7209102cffd79389b4cca391793d57171c8b12dc
