### ISSUE TITLE
How to use windows APIs in msys packages

### ISSUE THREAD

**Issue by jeroen** [Alexpux/MSYS2-packages#1293]
For my personal repository I would like to rebuild the msys2 package [curl](https://github.com/Alexpux/MSYS2-packages/blob/master/curl/PKGBUILD) (not the mingw package) using `--with-winssl` instead of openssl. Using native Windows TLS makes it easier for users in corporate networks that have custom certs in their windows cert store.

However I found that even though this worked perfectly fine for `mingw-w64-curl`, the configure script for the msys2 package curl is unable to find any windows apis for ssl and ldap. 

Is there some way to make msys2 packages use windows native apis? Or will these by definition conflict with the msys2 runtime api?

**Comment by Alexpux** [comment]
@jeroen MSYS2 is Cygwin so it use only general Windows API inside runtime but not for other programs. You can't simply use Win32 API for programs buildied with msys toolchain.
