### ISSUE TITLE
Start mintty bash in current working directory

### ISSUE THREAD

**Issue by Konfekt** [Alexpux/MSYS2-packages#130]
How about starting mintty in the current working directory instead of the home dir?

This is convenient for spawning msys2 for example in a GIT repo from the cmd line or external programs such as (g)Vim.

This can be achieved by modifying the following line in `c:\msys64\msys2_shell.bat` 

```
start %WD%mintty -i /msys2.ico /usr/bin/env CHERE_INVOKING=1 /usr/bin/bash --login %*
```

to

```
start %WD%mintty -i /msys2.ico /usr/bin/bash --login %*
```

If this is to intrusive, there are two other possibilities:
- How about pulling %\* forward, that is

```
start %WD%mintty -i /msys2.ico %* /usr/bin/bash --login
```

instead of

```
start %WD%mintty -i /msys2.ico /usr/bin/bash --login %*
```

so that the user can pass on /usr/bin/env CHERE_INVOKING=1 to msys2?
- How about an argument, say `-here`, that can be passed to `msys2_shell.bat` and then only in this case spawns `msys2_shell.bat` in the current working directory?

**Comment by elieux** [comment]
Both `msys2-launcher` launchers and `msys2_shell.cmd` support starting in current directory.
