### ISSUE TITLE
pacman updates

### ISSUE THREAD

**Issue by jeroen** [Alexpux/MSYS2-packages#1304]
Review changes in 5.1.0: https://git.archlinux.org/pacman.git/tree/NEWS

Also I was wondering if we can remove the runtime dependency on `curl`. Pacman by default uses the [libalpm C downloader](https://github.com/gtmanfred/pacman/blob/master/lib/libalpm/dload.cv) based on libcurl. Because pacman statically links to libcurl, there is no runtime dependency on curl.

However our [makepkg.conf](https://github.com/Alexpux/MSYS2-packages/blob/master/pacman/makepkg.conf#L11-L13) overrides this and uses the command line curl. Why is this? The pacman C downloader seems to be more reliable.

**Comment by Alexpux** [comment]
You mix pacman and makepkg.
Makepkg is build system that use many third party programs
