### ISSUE TITLE
Pacman has problems with architecture recognition? Libraries libgpg-error.

### ISSUE THREAD

**Issue by piotrvv** [Alexpux/MSYS2-packages#1318]
/usr/lib/libgpg-error.a(libgpg_error_la-argparse.o):(.text+0x3c4): undefined reference to `libintl_gettext'
/usr/lib/libgpg-error.a(libgpg_error_la-argparse.o):(.text+0x3c4): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `libintl_gettext'
/usr/lib/libgpg-error.a(libgpg_error_la-argparse.o):(.text+0x50b): undefined reference to `libintl_gettext'
/usr/lib/libgpg-error.a(libgpg_error_la-argparse.o):(.text+0x50b): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `libintl_gettext'
/usr/lib/libgpg-error.a(libgpg_error_la-argparse.o):(.text+0x6eb): undefined reference to `libintl_gettext'
/usr/lib/libgpg-error.a(libgpg_error_la-argparse.o):(.text+0x6eb): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `libintl_gettext'
/usr/lib/libgpg-error.a(libgpg_error_la-argparse.o):(.text+0x738): undefined reference to `libintl_gettext'
/usr/lib/libgpg-error.a(libgpg_error_la-argparse.o):(.text+0x738): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `libintl_gettext'
/usr/lib/libgpg-error.a(libgpg_error_la-argparse.o):(.text+0x778): undefined reference to `libintl_gettext'
/usr/lib/libgpg-error.a(libgpg_error_la-argparse.o):(.text+0x778): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `libintl_gettext'
/usr/lib/libgpg-error.a(libgpg_error_la-argparse.o):(.text+0x78c): more undefined references to `libintl_gettext' follow
/usr/lib/libgpg-error.a(libgpg_error_la-argparse.o):(.text+0x78c): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `libintl_gettext'
/usr/lib/libgpg-error.a(libgpg_error_la-argparse.o):(.text+0x7a0): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `libintl_gettext'
/usr/lib/libgpg-error.a(libgpg_error_la-argparse.o):(.text+0x7c8): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `libintl_gettext'
/usr/lib/libgpg-error.a(libgpg_error_la-argparse.o):(.text+0x7dc): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `libintl_gettext'
/usr/lib/libgpg-error.a(libgpg_error_la-argparse.o):(.text+0x7f8): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `libintl_gettext'
/usr/lib/libgpg-error.a(libgpg_error_la-argparse.o):(.text+0x80c): additional relocation overflows omitted from the output
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:474: cleanupdelta.exe] Error 1

**Comment by piotrvv** [comment]
I forgot about the libgpg 1.31-1 and pacman 5.1.0-2 versions.

**Comment by Alexpux** [comment]
I cant reproduce this because I already upload this packaes

**Comment by piotrvv** [comment]
I have this problem because I just loaded a new version of pacman. And I was debugging pacman myself with the newly found errors from the repository. The problem is the new libgpg-error library.

**Comment by Alexpux** [comment]
What the problem?
This https://github.com/Alexpux/MSYS2-packages/commit/0a181ce4a084bb0192137f789a86c5234ca76c68 fix the linking errors

**Comment by piotrvv** [comment]
My version of mingw-w64-cross-gcc-arm has problems with pacman and I had to add a patch but in the new version libgpg-error-1.31 pacman had given problems with the compilation. I checked pacman from your repository but now I see clearly that this is my mistake. I added an old patch file.
