### ISSUE TITLE
msys2-x86_64-20180531 after pacman -Syu, git package is broken.

### ISSUE THREAD

**Issue by wuhanck** [Alexpux/MSYS2-packages#1329]
Win10
install using msys2-x86_64-20180531.exe

Under msys2:

$ pacman -Syu
upgrade:
filesystem-2018.06-1  pacman-5.1.0-2  pacman-mirrors-20180604-2

Then:
$ pacman -S git

Result:
Can't create '/usr/bin/git-upload-archive.exe'
Can't create '/usr/bin/git.exe'
etc... etc...

Running git:
$ git
bash: git: command not found

I have tried Win7, it is the same result with additional warning when start msys2(cann't... drivers/etc/hosts).

**Comment by StarWolf3000** [comment]
Do you have write access to where MSYS2 has been installed to?

**Comment by wuhanck** [comment]
It works now. ...
I close it.
