### ISSUE TITLE
Irssi: unable to link perl with irssi on Windows 10

### ISSUE THREAD

**Issue by tsaulic** [Alexpux/MSYS2-packages#1330]
Hello, just wanted to ask - and I apologise if there is a simple solution, but I'm not an expert for sure.

I've done a `pacman -Syu` followed by exit and another `pacman -Syu` to fully update MSYS2 environment.

I then tried to build irssi from source, both 1.0.7 and 1.1.1 versions, with perl.
I've used all permutations of `--with-perl=yes` and `--with-perl-staticlib` and provided `LDFLAGS=-L/path/to/libperl528.a/libperl528.dll`

It looks like no matter how I specify the LDFLAGS it cannot find the library.

Also, simply using `pacman -S irssi` installs it, but I cannot run it, as it says the perl library is missing (when I've installed all versions, including the ones with mingw prefixes. I'm lost. Thank you for your hard work. I just came back to Windows from macOS after around 8 years, and I really love this project, but I'm a noob and need help! 🤣 

Can someone please help?

**Comment by Alexpux** [comment]
Dont see any issue linking with perl. Will upload irssi 1.1.1 when have time
