### ISSUE TITLE
`pacman -Fs man` doesn't find package

### ISSUE THREAD

**Issue by borekb** [Alexpux/MSYS2-packages#1332]
I wanted to install `man` and wanted to look it up. `pacman -Ss man` finds a lot of unrelated packages but the correct way should be (I believe; I'm new to MSYS2 & Pacman):

```
# Update repository databases
pacman -Fy

# Should find man-db-2.8.3-2 but doesn't
pacman -Fs man
```

This gives me these results, missing `man-db-2.8.3-2`:

```
$ pacman -Fs man
msys/bash-completion 2.8-2
    usr/share/bash-completion/completions/man
msys/xmlto 0.0.28-1
    usr/share/xmlto/format/docbook/man
```

**Comment by mati865** [comment]
`-F` is used for searching files.
If you want to search in the repository for exact name you could try with regex: `pacman -Ss ^man$`.
For searching only in installed packages there is `-Q` option.

More info: https://www.archlinux.org/pacman/pacman.8.html

**Comment by borekb** [comment]
I probably still don't understand, `man` is a file, specifically, `man-db-2.8.3-2` package [contains](https://www.archlinux.org/packages/core/x86_64/man-db/) the file `usr/bin/man` so I'm not sure why `-Fs` doesn't find it. I tried both `pacman -Fs man` and `pacman -Fs usr/bin/man`.

**Comment by Alexpux** [comment]
@borekb you need write full file name with extension - man.exe

**Comment by borekb** [comment]
Oh, it's so obvious now :) Thanks!
