### ISSUE TITLE
aspell-en package missing

### ISSUE THREAD

**Issue by LordAro** [Alexpux/MSYS2-packages#1334]
I'm not entirely sure of the cause of this, but aspell-en is missing from the repositories:

```
 > pacman -S aspell-en
error: target not found: aspell-en
```

It's got a PKGBUILD in this repo, so maybe it's just a case of it not being built for the repos? If that is indeed the case, can I request that it is built? The mingw64 versions have many languages prebuilt, and without any languages, aspell is a bit useless...

**Comment by Alexpux** [comment]
pacman -Ss aspell-en will help you to find proper name

**Comment by Alexpux** [comment]
Then it not builded.

**Comment by LordAro** [comment]
In which case, can it be?

**Comment by Alexpux** [comment]
@LordAro I dont remember, need to check

**Comment by Alexpux** [comment]
in repo now
