### ISSUE TITLE
xsltproc error

### ISSUE THREAD

**Issue by peterbud** [Alexpux/MSYS2-packages#1345]
Running `xsltproc` results an error. Is it only me?
```
$ xsltproc.exe --version
C:/msys64/usr/bin/xsltproc.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory

```

ldd output
```
$ ldd C:/msys64/usr/bin/xsltproc.exe
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7ff996de0000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7ff996650000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7ff993300000)
        msys-xslt-1.dll => /usr/bin/msys-xslt-1.dll (0x480910000)
        msys-xml2-2.dll => /usr/bin/msys-xml2-2.dll (0x4ffb30000)
        msys-2.0.dll => /usr/bin/msys-2.0.dll (0x180040000)
        msys-exslt-0.dll => /usr/bin/msys-exslt-0.dll (0x563fa0000)
        ??? => ??? (0xe20000)
        msys-iconv-2.dll => /usr/bin/msys-iconv-2.dll (0x5603f0000)
        msys-lzma-5.dll => /usr/bin/msys-lzma-5.dll (0x49fa70000)
        msys-z.dll => /usr/bin/msys-z.dll (0x522fe0000)
        msys-gcrypt-20.dll => /usr/bin/msys-gcrypt-20.dll (0x4aee70000)

```

**Comment by mati865** [comment]
Run it from `cmd.exe` and you should see which lib is missing.

**Comment by andrew-grechkin** [comment]
ldd /usr/bin/xsltproc.exe
        ntdll.dll => /c/Windows/SYSTEM32/ntdll.dll (0x76f50000)
        kernel32.dll => /c/Windows/system32/kernel32.dll (0x76d30000)
        KERNELBASE.dll => /c/Windows/system32/KERNELBASE.dll (0x7fefcc90000)
        msys-exslt-0.dll => /usr/bin/msys-exslt-0.dll (0x563fa0000)
        msys-xslt-1.dll => /usr/bin/msys-xslt-1.dll (0x480910000)
        msys-2.0.dll => /usr/bin/msys-2.0.dll (0x180040000)
        msys-xml2-2.dll => /usr/bin/msys-xml2-2.dll (0x4ffb30000)
        msys-iconv-2.dll => /usr/bin/msys-iconv-2.dll (0x5603f0000)
        msys-icuuc62.dll => /usr/bin/msys-icuuc62.dll (0x41f550000)
        msys-icudata62.dll => /usr/bin/msys-icudata62.dll (0x427cd0000)
        msys-gcc_s-seh-1.dll => /usr/bin/msys-gcc_s-seh-1.dll (0x5e8160000)
        msys-stdc++-6.dll => /usr/bin/msys-stdc++-6.dll (0x526840000)
        msys-lzma-5.dll => /usr/bin/msys-lzma-5.dll (0x49fa70000)
        msys-z.dll => /usr/bin/msys-z.dll (0x522fe0000)
        msys-gcrypt-20.dll => /usr/bin/msys-gcrypt-20.dll (0x4aee70000)
        msys-gpg-error-0.dll => /usr/bin/msys-gpg-error-0.dll (0x45a000000)
        msys-intl-8.dll => /usr/bin/msys-intl-8.dll (0x430b30000)

**Comment by peterbud** [comment]
Gees, I'm stupid - I had my own hand-built `libxml2 `installed which was built with previous `icu`. Reinstalling `libxml2 `from the repo solved the problem.
