### ISSUE TITLE
building pacman with pacman -- "cp: cannot stat 'repo-add'..."

### ISSUE THREAD

**Issue by earnie** [Alexpux/MSYS2-packages#1365]
I'm recently attempting to learn msys2 development as it stands today.  I'm really impressed with the setup.  So I decided to start by learning the pacman system and what better way than to download the source package for pacman and give the makepkg command a go.  I've managed to overcome most of the issues thus far but now I have a issue which follows that I'm at a loss to resolve.  Any help here will be greatly appreciated.

```makepkg
  GEN      repo-add
cp: cannot stat 'repo-add': No such file or directory
make[3]: *** [Makefile:989: repo-remove] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [Makefile:654: all-recursive] Error 1
make[1]: *** [Makefile:980: all-recursive] Error 1
make: *** [Makefile:889: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by earnie** [comment]
I think this is a target dependency issue for the targets repo-remove and repo-elephant.  The way it's written works with `ln -s` but not with `cp -pR`.

This:
```Makefile
repo-remove: $(srcdir)/repo-add.sh.in
	$(AM_V_at)$(RM) repo-remove
	$(AM_V_at)$(LN_S) repo-add repo-remove

repo-elephant: $(srcdir)/repo-add.sh.in
	$(AM_V_at)$(RM) repo-elephant
	$(AM_V_at)$(LN_S) repo-add repo-elephant
```
should be:
```Makefile
repo-remove: repo-add
	$(AM_V_at)$(RM) repo-remove
	$(AM_V_at)$(LN_S) repo-add repo-remove

repo-elephant: repo-add
	$(AM_V_at)$(RM) repo-elephant
	$(AM_V_at)$(LN_S) repo-add repo-elephant
```

**Comment by earnie** [comment]
And making the suggested change to scripts/Makefile.am moves the build forward.  Now to get past the `make check` failure.

**Comment by Alexpux** [comment]
I will look

**Comment by Alexpux** [comment]
Fixed in https://github.com/Alexpux/MSYS2-packages/commit/37603ca4164d417b5c040487e9c6efcd5e7d8d00
