### ISSUE TITLE
ncurses use_default_colors returns ERR

### ISSUE THREAD

**Issue by OmegaDoom** [Alexpux/MSYS2-packages#1383]
Hello.

```
#include <ncurses/ncurses.h>
#include <iostream>

int main(int argc, char* argv[])
{
    initscr();
    start_color();
    int r = use_default_colors(); // r is ERR!
    if (ERR == r)
    {
        std::cout << "err!" << std::endl;
    }

    if (!has_colors())
    {
        printw("No colors!");
        return 1;
    }

    if (ERR == init_pair(1, COLOR_RED, -1))
    {
        std::cout << "init_pair err" << std::endl;
    }

    attron(COLOR_PAIR(1));
    printw("Hello world!!!");
    attroff(COLOR_PAIR(1));
    refresh();
    getch();
    endwin();
}

```

Because of that applications that use "use_default_colors" function don't work correctly. One of them is cgdb which fallbacks to monochrome/grey-scale. The root cause of this is how ncurses is configured.  It has --enable-term-driver option. If this option is disabled then use_default_colors works as expected. This driver is odd thing. It has such code:

tinfo_driver.c

```
static int
drv_defaultcolors(TERMINAL_CONTROL_BLOCK * TCB, int fg, int bg)
{
    SCREEN *sp;
    int code = ERR;

    AssertTCB();
    SetSP();

    if (sp != 0 && orig_pair && orig_colors && (initialize_pair != 0)) {
#if NCURSES_EXT_FUNCS
	sp->_default_color = isDefaultColor(fg) || isDefaultColor(bg);
	sp->_has_sgr_39_49 = (NCURSES_SP_NAME(tigetflag) (NCURSES_SP_ARGx
							  "AX")
			      == TRUE);
	sp->_default_fg = isDefaultColor(fg) ? COLOR_DEFAULT : fg;
	sp->_default_bg = isDefaultColor(bg) ? COLOR_DEFAULT : bg;
	if (sp->_color_pairs != 0) {
	    bool save = sp->_default_color;
	    sp->_default_color = TRUE;
	    NCURSES_SP_NAME(init_pair) (NCURSES_SP_ARGx
					0,
					(short)fg,
					(short)bg);
	    sp->_default_color = save;
	}
#endif
	code = OK;
    }
    return (code);
}

```

The problem is initialize_pair which corresponds to "initp" escape sequence. Only few terminals support initp but those that support don't work correctly in msys2 (Gibberish on screen and crashes). But when configuration has --disable-term-driver then we have following code:

lib_dft_fgbg.c

```
NCURSES_EXPORT(int)
NCURSES_SP_NAME(assume_default_colors) (NCURSES_SP_DCLx int fg, int bg)
{
    int code = ERR;

    T((T_CALLED("assume_default_colors(%p,%d,%d)"), (void *) SP_PARM, fg, bg));
    if (SP_PARM != 0) {
#ifdef USE_TERM_DRIVER
	code = CallDriver_2(SP_PARM, td_defaultcolors, fg, bg);
#else
	if ((orig_pair || orig_colors) && !initialize_pair) {

	    SP_PARM->_default_color = isDefaultColor(fg) || isDefaultColor(bg);
	    SP_PARM->_has_sgr_39_49 = (tigetflag("AX") == TRUE);
	    SP_PARM->_default_fg = isDefaultColor(fg) ? COLOR_DEFAULT : fg;
	    SP_PARM->_default_bg = isDefaultColor(bg) ? COLOR_DEFAULT : bg;
	    if (SP_PARM->_color_pairs != 0) {
		bool save = SP_PARM->_default_color;
		SP_PARM->_assumed_color = TRUE;
		SP_PARM->_default_color = TRUE;
		init_pair(0, (short) fg, (short) bg);
		SP_PARM->_default_color = save;
	    }
	    code = OK;
	}
#endif
    }
    returnCode(code);
}

```
if ((orig_pair || orig_colors) && !initialize_pair) works fine unlike previous code because of !initialize_pair!

Looks like term driver is odd. It's stated in ncurses site that this driver is experimental and used only for mingw.

Because of that I suggest to use --disable-term-driver. Same issue is applicable for mingw ncurces so I suggest to do the same thing for it.

**Comment by elieux** [comment]
Did you test `--disable-term-driver` in the default Windows console?

**Comment by OmegaDoom** [comment]
Yes, cmd also working as expected!

**Comment by earnie** [comment]
[MINGW-packages_ncurses_term_driver.patch.txt](https://github.com/Alexpux/MSYS2-packages/files/2329649/MINGW-packages_ncurses_term_driver.patch.txt)
[MSYS2-packages_ncurses_term_driver.patch.txt](https://github.com/Alexpux/MSYS2-packages/files/2329650/MSYS2-packages_ncurses_term_driver.patch.txt)

I've created patches based on this information.

**Comment by Alexpux** [comment]
Mingw version of ncurses cannot be builded with disabled term driver

**Comment by OmegaDoom** [comment]
Yes, I see it. Mingw requires terminal-driver. Thank you for fixing msys ncurses. Closing this issue.
