### ISSUE TITLE
Building iperf3 via MSYS

### ISSUE THREAD

**Issue by Iss03** [Alexpux/MSYS2-packages#1384]
I tried to make iperf3 or get it with pacman but have some problems.
Is it correct place for this issue? 

win_iperf3 can't work with udp multistream. 
(server: iperf3 -s client: iperf3 -c localhost -u -P 2)
I found iperf issue on official bug tracker https://github.com/esnet/iperf/issues/321 
Do someone know reason of this behavior?

**Comment by Alexpux** [comment]
iperf3 in repo now
