### ISSUE TITLE
Nodejs is broken

### ISSUE THREAD

**Issue by sharifzadesina** [Alexpux/MSYS2-packages#1390]
mingw-w64-nodejs package is broken cause of icu 62. it required icu 61.

**Comment by StarWolf3000** [comment]
Wrong repository. Is a Mingw-w64 package, not an MSYS2 package.

See Alexpux/MINGW-packages#3615. Fixed by Alexpux/MINGW-packages#4337.

**Comment by sharifzadesina** [comment]
@StarWolf3000 I thought they are same, thank you.
