### ISSUE TITLE
BSDTAR broken after the update

### ISSUE THREAD

**Issue by angelog0** [Alexpux/MSYS2-packages#1399]
Now, trying to use `bsdtar`,

```
bsdtar -xvof foo.tar.gz
C:/msys64/usr/bin/bsdtar.exe: error while loading shared libraries: msys-lz4-1.dll: cannot open shared object file: No such file or directory
```

I have many scripts based on `bsdtar'.. this means all that is broken too..

Reinstalling the previous version (3.3.2-2) works.

It seems that now the package depend on `liblz4` (Just installing `liblz4-devel` fixes the issue)

**Comment by peterbud** [comment]
Confirmed, same here

**Comment by angelog0** [comment]
I don't understand why you have upgraded to `bsdtar-3.3.3-2` without updating the dependencies... it still fails without a manual installation of `liblz4`...

**Comment by Alexpux** [comment]
I forgot one entry in 3.3.3-2 updat
https://github.com/Alexpux/MSYS2-packages/commit/79c2a3d9f5ff5f28a440a892ab1f512e1c9821e7

will be fixed later
