### ISSUE TITLE
mingw64 dlls and binaries linked to 32 bit  Windows dlls?

### ISSUE THREAD

**Issue by mathog** [Alexpux/MSYS2-packages#1409]
On a Windows 10 64 bit system msys2 was installed.  There are mingw64 and mingw32 directories.  Packages
were all installed like this:

```
ARCH=mingw-w64-x86_64
pacman -S --needed --noconfirm $ARCH-toolchain $ARCH-cmake $ARCH-ninja

```
including 

`pacman -S  mingw-w64-x86_64-ntldd
`

Oddly, everything seems to be linked to the 32 bit Windows core dlls.  Example:

```
which ntldd
   /mingw64/bin/ntldd

ntldd `which ntldd`
        imagehlp.dll => C:\WINDOWS\SYSTEM32\imagehlp.dll (0x0000000000170000)
        KERNEL32.dll => C:\WINDOWS\SYSTEM32\KERNEL32.dll (0x0000000000620000)
        msvcrt.dll => C:\WINDOWS\SYSTEM32\msvcrt.dll (0x0000000000620000)

 ntldd /mingw64/bin/libstdc++-6.dll
        libgcc_s_seh-1.dll (0x00000000001a0000)
        KERNEL32.dll => C:\WINDOWS\SYSTEM32\KERNEL32.dll (0x0000000000d50000)
        msvcrt.dll => C:\WINDOWS\SYSTEM32\msvcrt.dll (0x0000000000d50000)
        libwinpthread-1.dll (0x00000000001c0000)
        USER32.dll => C:\WINDOWS\SYSTEM32\USER32.dll (0x0000000000d50000)

```
The system has both the 32 bit and  64 bit files, and ntldd can look at them:

```
ntldd /c/windows/syswow64/msvcrt.dll
        ntdll.dll => C:\windows\syswow64\ntdll.dll (0x0000000000e10000)
        KERNELBASE.dll => C:\windows\syswow64\KERNELBASE.dll (0x0000000000e10000)

 ntldd /c/windows/system32/msvcrt.dll
        ntdll.dll => C:\windows\system32\ntdll.dll (0x0000000000da0000)
        KERNELBASE.dll => C:\windows\system32\KERNELBASE.dll (0x0000000000da0000)

```

So, I don't understand why binaries in mingw64, which is I believe the 64 bit build environment, are linked like this.

**Comment by mathog** [comment]
Note, I'm positive it was the 64 bit installer which was downloaded and installed.  In "Programs and Features" it is labeled "MSYS2 64bit", with product version 20180531 and size 227MB.

**Comment by StarWolf3000** [comment]
If you're on 64-bit Windows, 64-bit .dlls go into %SYSTEMROOT%\system32 and 32-bit .dlls into %SYSTEMROOT%\SysWOW64. On 32-bit Windows, 32-bit .dlls go into %SYSTEMROOT%\system32. So `ntldd` is working as expected and refers to the 64-bit .dlls.

**Comment by elieux** [comment]
Yes, `system32` doesn't necessarily mean 32-bit, it's a quirk of Windows (in order to keep backwards compatibility).

**Comment by mati865** [comment]
What about `file`?
```
$ file <path>
<path>: PE32 executable (console) Intel 80386 (stripped to external PDB), for MS Windows
$ file <path>
<path>: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
```

**Comment by mathog** [comment]
That looks good.  Thanks.
