### ISSUE TITLE
Issues with git rebase

### ISSUE THREAD

**Issue by joca-bt** [Alexpux/MSYS2-packages#141]
Whenever I try to rebase something with `msys git 2.2.0-1` I get this error:

```
mv: ‘... .git/rebase-merge/git-rebase-todo.new’ and ‘... .git/rebase-merge/git-rebase-todo’ are the same file
Could not skip unnecessary pick commands
```

Any ideas? (It works with the git from the official site so that excludes any possible repository errors.)

**Comment by DJm00n** [comment]
@joca-bt, try to use MSYS2 Shell, not MinGW-w64 Shell.

**Comment by joca-bt** [comment]
Seems to be ok.

**Comment by elieux** [comment]
Rebasing works now? (I'd try to confirm it myself, but I don't know how to rebase in command line.)
