### ISSUE TITLE
Unable to download msys2-x86_64-20180531.exe 

### ISSUE THREAD

**Issue by zeeshanhanif** [Alexpux/MSYS2-packages#1425]
Hello,

I'm trying to download msys2-x86_64-20180531.exe from website (http://www.msys2.org/) but it is giving error page not found. You please guide what is the problem

**Comment by lazka** [comment]
It seems to be working here.

**Comment by zeeshanhanif** [comment]
Is it the right URL, its not working for me here
http://repo.msys2.org/distrib/msys2-x86_64-latest.exe

**Comment by lazka** [comment]
Works for me too.

Alternative: https://sourceforge.net/projects/msys2/files/Base/x86_64/

**Comment by elieux** [comment]
Can you try `tracert repo.msys2.org`?  I remember there were issues with routes to some ISPs.

-- 
David Macek

**Comment by zeeshanhanif** [comment]
Working for me now, Thanks
