### ISSUE TITLE
pacman: allow filename case changes for package upgrades

### ISSUE THREAD

**Issue by lazka** [Alexpux/MSYS2-packages#1426]
pacman errors out if a package changes the case of a filename (recent openssl upgrade for example, https://github.com/Alexpux/MINGW-packages/issues/4458#issuecomment-424381478)

* It checks for new files in the new package compared to the old one (since case changed, this returns those)
* It then makes sure that the new files don't already exist (since the FS is case insensitive, this triggers)

Proposed patch to make things work (ASCII only):

https://bpaste.net/show/243ba50a6fb6

(I'll replace strncasecmp_l with an ascii only impl, but this was easier for starters)

Thoughts?

**Comment by Alexpux** [comment]
well as for start it ok i think

**Comment by lazka** [comment]
ok, see #1430
