### ISSUE TITLE
QtCreator plugins no loads

### ISSUE THREAD

**Issue by kassane** [Alexpux/MSYS2-packages#1437]
After upgrading from IDE to version 4.7.1-1, it does not want to load the dependencies needed to run properly.
![msys2_qtcreator-error](https://user-images.githubusercontent.com/6756180/46289618-f8b55b00-c55f-11e8-8666-ecee1b8794e7.png)

**Comment by Alexpux** [comment]
I can’t reproduce. See that Qt5 is patched properly with qtbinpatcher

**Comment by kassane** [comment]
I downloaded the original qtcreator and find out that the same plugins folder in msys2 was missing dependent libs. I copied from one to the other and it worked again. So the IDE in the repository is incomplete.

**Comment by Alexpux** [comment]
What libraries missing?
