### ISSUE TITLE
MSYS2 fails on start.

### ISSUE THREAD

**Issue by AMDphreak** [Alexpux/MSYS2-packages#1446]
The window is smaller than the display area, with a green border.
Fails on start.
goes quiet.
After a minute, new errors start popping up.

[Screenshots](https://imgur.com/gallery/REHqcDt)

**Comment by StarWolf3000** [comment]
Is this after the 1809 Windows Update?

**Comment by mati865** [comment]
One of the AV software (I think it was Avast or Comodo) was adding green border around programs that are sanboxed by it. Those sandboxes are very restrictive and totally break Cygwin/MSYS2.

**Comment by AMDphreak** [comment]
I apologize. That was it. I recently installed Comodo. It also affected Cygwin Terminal in the same way.

Sent from Mail for Windows 10
