### ISSUE TITLE
Guile 2.2.4-1 hangs with libgc 8.0.0-1 (but still working with libgc 7.6.0-1)

### ISSUE THREAD

**Issue by h-c-mueller** [Alexpux/MSYS2-packages#1454]
Keeping the system up to date with 'pacman -Suuy', I recently noticed guile (2.2.4-1) always hangs on start up. Downgrading of libgc from 8.0.0-1 to 7.6.0-1 resolved the problem for me.

**Comment by Alexpux** [comment]
gc downgraded to 7.6.8
