### ISSUE TITLE
Can you update OpenSSL to the very latest? 1.0.2 is rather old.

### ISSUE THREAD

**Issue by weallknowthis** [Alexpux/MSYS2-packages#1467]
Or perhaps provide a separate package, e.g openssl-1.1.1 and then people can switch between the two via pacman -S openssl or pacman -S openssl-1.1.1 or if the default is 1.1.1, then pacman -S openssl-1.0.2

**Comment by weallknowthis** [comment]
Alright, I'll look into it. In the meantime I should warn that OpenSSL 1.1.1 has an incompatible interface to 1.02, so software based on 1.0.2 will fail to compile. The interface has changed many structures to be opaque pointers and favors getters and setters rather than accessing structure members directly.

**Comment by Alexpux** [comment]
We already provide OpenSSL-1.1.1 for mingw packages

**Comment by weallknowthis** [comment]
I know, I use both, but MSYS2's package is older.

**Comment by Alexpux** [comment]
@weallknowthis @dscho new openssl in repo now
