### ISSUE TITLE
wxWidgets libraries come without stack trace support

### ISSUE THREAD

**Issue by twlostow** [Alexpux/MSYS2-packages#1474]
Hi,

Would it be possible to enable stack trace/exception handling support in the wxWidgets packages? This means enabling the following flags during build:
- wxUSE_ON_FATAL_EXCEPTION
- wxUSE_STACKWALKER
- wxUSE_DBGHELP

Many thanks,
Tom

**Comment by Alexpux** [comment]
create pull request
