### ISSUE TITLE
elinks.exe: error while loading shared libraries: msys-perl5_24.dll

### ISSUE THREAD

**Issue by BenKey** [Alexpux/MSYS2-packages#1479]
I get the following error when I attempt to run elinks.

> C:/msys64/usr/bin/elinks.exe: error while loading shared libraries: msys-perl5_24.dll: cannot open shared object file: No such file or directory

My environment is as follows.

- Windows 10 Pro 1809 64-bit
- msys/elinks-git 0.13.4008.f86be659-1 (net-utils) [installed]
- msys/perl 5.28.0-1 (base-devel) [installed]

My best guess is that elinks simply was not rebuilt after msys/perl was updated from version 5.24 to version 5.28.

**Comment by lukebakken** [comment]
#1101 still applies when trying to build `elinks` ... :disappointed:

**Comment by andrew-grechkin** [comment]
If you really need elinks you can build it yourself just use --without-guile in the PKGBUILD

**Comment by Alexpux** [comment]
I’m already do it and upload to repo

**Comment by lukebakken** [comment]
@Alexpux thank you, I can confirm that this issue is resolved.
