### ISSUE TITLE
Installing MSYS2 development packages

### ISSUE THREAD

**Issue by AaronNGray** [Alexpux/MSYS2-packages#148]
Is there anything that either gives a full install of all MSYS2 development tools or a script that downloads them ?

It might be good if the MSYS2 installer had a check box for downloading and installing development tools. As finding what you need to install from error messages is a total bind.

**Comment by joca-bt** [comment]
pacman -S --needed msys2-devel

**Comment by elieux** [comment]
`base-devel` contains common subset of packages for both MSYS2 and native development. The toolchains are then contained in groups `msys2-devel`, `mingw-w64-i686-toolchain`, and `mingw-w64-x86_64-toolchain`, depending on what you want to target. The information is now written down on the [MSYS2 introduction](https://sourceforge.net/p/msys2/wiki/MSYS2%20introduction/) wikipage.

**Comment by yukoff** [comment]
Just a follow-up: wiki was migrated to github, so find it here [MSYS2 introduction](/msys2/msys2/wiki/MSYS2-introduction)
