### ISSUE TITLE
Does msys2 contain objdump  as well ?

### ISSUE THREAD

**Issue by faizan80** [Alexpux/MSYS2-packages#1481]
Hi,

If I install msys2 or msys2-install, does it install objdump as well ??

**Comment by andrew-grechkin** [comment]
Try pacman -Syu --needed base-devel msys2-devel

**Comment by Alexpux** [comment]
Objdump command is part of binitils package

**Comment by sskras** [comment]
> Objdump command is part of binitils package

To be exact, it's called `binutils`.
