### ISSUE TITLE
gnupg-2.2.11-1 upgrade failed on signing.

### ISSUE THREAD

**Issue by t246246** [Alexpux/MSYS2-packages#1484]
Same error happend at least since 2.2.10-1, seems not fixed yet in 2.2.11-1

$ pacman -S gnupg
warning: gnupg-2.2.11-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) gnupg-2.2.11-1

Total Installed Size:  8.52 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                     [#####################] 100%
(1/1) checking package integrity                   [#####################] 100%
(1/1) loading package files                        [#####################] 100%
(1/1) checking for file conflicts                  [#####################] 100%
(1/1) checking available disk space                [#####################] 100%
:: Processing package changes...
(1/1) reinstalling gnupg                           [#####################] 100%
==> Appending keys from msys2.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key D55E7A6D7CE9BA1587C0ACACF40D263ECA25678A...
==> ERROR: D55E7A6D7CE9BA1587C0ACACF40D263ECA25678A could not be locally signed.
  -> Locally signing key 123D4D51A1793859C2BE916BBBE514E53E0D0813...
==> ERROR: 123D4D51A1793859C2BE916BBBE514E53E0D0813 could not be locally signed.
  -> Locally signing key B91BCF3303284BF90CC043CA9F418C233E652008...
==> ERROR: B91BCF3303284BF90CC043CA9F418C233E652008 could not be locally signed.
  -> Locally signing key 9DD0D4217D75A33B896159E6DA7EF2ABAEEA755C...
==> ERROR: 9DD0D4217D75A33B896159E6DA7EF2ABAEEA755C could not be locally signed.
error: command (/usr/bin/bash /usr/bin/bash -c . /tmp/alpm_e2BpMb/.INSTALL; post_upgrade 2.2.11-1 2.2.11-1 ) failed to execute correctly

**Comment by StarWolf3000** [comment]
Is `gpg-agent` running in the background?

**Comment by andrew-grechkin** [comment]
try 'mv /etc/pacman.d/gnupg /tmp' and then restart msys

**Comment by t246246** [comment]
Thank you for your comment.

After moving /etc/pacman.d/gnupg, restarting failed. (I'm behind proxy.)

gpg: /etc/pacman.d/gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
gpg: starting migration from earlier GnuPG versions
gpg: can't connect to the agent: IPC connect call failed
gpg: error: GnuPG agent unusable. Please check that a GnuPG agent can be started.
gpg: migration aborted
gpg: starting migration from earlier GnuPG versions
gpg: can't connect to the agent: IPC connect call failed
gpg: error: GnuPG agent unusable. Please check that a GnuPG agent can be started.
gpg: migration aborted
gpg: Generating pacman keyring master key...
gpg: can't connect to the agent: IPC connect call failed
gpg: agent_genkey failed: No agent running
gpg: key generation failed: No agent running
gpg: Done
==> Updating trust database...
gpg: no need for a trustdb check
==> Appending keys from msys2.gpg...
gpg: starting migration from earlier GnuPG versions
gpg: can't connect to the agent: IPC connect call failed
gpg: error: GnuPG agent unusable. Please check that a GnuPG agent can be started.
gpg: migration aborted
gpg: can't connect to the agent: IPC connect call failed
gpg: can't connect to the agent: IPC connect call failed
gpg: can't connect to the agent: IPC connect call failed
gpg: can't connect to the agent: IPC connect call failed
gpg: can't connect to the agent: IPC connect call failed

**Comment by t246246** [comment]
Then it becomes impossible to upgrade package with pacman:

error: msys: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust
error: failed to update msys (invalid or corrupted database (PGP signature))
error: failed to synchronize all databases

So I have to back /tmp/gnupg to /etc/pacman.d/ again now.

**Comment by StarWolf3000** [comment]
Your `gpg-agent` isn't running, that's why your're getting these errors. Possible solution: Temporary disable anti-virus software, they may kill cryptographic components (had this problem with Avast, when updating gnupg), or add the installation path to the exceptions.

You should still have gnupg in the package cache, so just reinstall it with `$ pacman -S gnupg`.

**Comment by t246246** [comment]
OK, It is impossible disable virus-buster here. But exculding c:\msys64 from Virus Buster Corporate Edition,  I try to run gpg-agent:

$ gpg-agent --version
gpg-agent (GnuPG) 2.2.11-unknown
libgcrypt 1.8.4
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ gpg-agent
gpg-agent[13132]: no gpg-agent running in this session
$ echo $?
2

It looks it won't run.

**Comment by StarWolf3000** [comment]
`gpg-agent` will be autorun when needed by a gpg component, such as the signing tool, and then remains running in the background until killed.

Now try to reinstall gnupg.

**Comment by t246246** [comment]
OK, It is impossible disable virus-buster here. But exculding c:\msys64 from Virus Buster Corporate Edition,  I try to run gpg-agent:

$ gpg-agent --version
gpg-agent (GnuPG) 2.2.11-unknown
libgcrypt 1.8.4
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ gpg-agent
gpg-agent[13132]: no gpg-agent running in this session
$ echo $?
2

It looks it won't run.

**Comment by t246246** [comment]
I checked man gpg-agent and now found:

% gpg-agent --daemon

then

% pacman -S gnupg

All is solved. Thank you again!

**Comment by StarWolf3000** [comment]
So, can you please close it then?

**Comment by t246246** [comment]
After doing the process above, once successing to sign, I confirmed that gpg-agent will automatically start.
So I will close this issue.

**Comment by Juno72** [comment]
Maybe related, seeing simular sympoms: using lasted install, or a full update using an older install, gnupg issues (filed a new issue):

(53/75) installing pinentry                                                                                [##############################################################] 100%
(54/75) upgrading gnupg                                                                                    [##############################################################] 100%
==> Appending keys from msys2.gpg...
gpg: starting migration from earlier GnuPG versions
gpg: can't connect to the agent: IPC connect call failed
gpg: error: GnuPG agent unusable. Please check that a GnuPG agent can be started.
gpg: migration aborted
==> Locally signing trusted keys in keyring...
  -> Locally signing key D55E7A6D7CE9BA1587C0ACACF40D263ECA25678A...
==> ERROR: D55E7A6D7CE9BA1587C0ACACF40D263ECA25678A could not be locally signed.
  -> Locally signing key 123D4D51A1793859C2BE916BBBE514E53E0D0813...
==> ERROR: 123D4D51A1793859C2BE916BBBE514E53E0D0813 could not be locally signed.
  -> Locally signing key B91BCF3303284BF90CC043CA9F418C233E652008...

**Comment by modem-man-gmx** [comment]
had to deactive Acronis protection for 30 minutes, otherwise the socket for gpg-agent got blocked.
