### ISSUE TITLE
Qt 5.12.0

### ISSUE THREAD

**Issue by Jocala** [Alexpux/MSYS2-packages#1514]
Will msys2 be providing the 5.12.0 LTS release?

**Comment by mingwandroid** [comment]
Did you make a PR for this? That's the best way to achieve your goal.

**Comment by Alexpux** [comment]
@Jocala  @mingwandroid  it not possible to build 32-bit Qt5 because of bugs with binutils+gcc+clang

**Comment by mingwandroid** [comment]
May it be time to consider dropping 32 bit support?

**Comment by Alexpux** [comment]
@mingwandroid well in future plans I thinking about it, but right now I have too many 32 bit systems still...

In any case latest binutils 2.31 and newer also have issues for 64 bit

**Comment by Alexpux** [comment]
@Jocala @mingwandroid I'm finishing 32 bit Qt5 build in a hack way so I hope  new packages will be in repo today or tomorrow

**Comment by Jocala** [comment]
This is incredibly useful, thank you so much.

**Comment by Jocala** [comment]
Are older Qt releases available?  I'm especially interested in 5.6.

**Comment by Alexpux** [comment]
@Jocala you can try to find binary package in repo, but you must install all old dependencies by hand.

Qt 5.12 in repo now

**Comment by Jocala** [comment]
Thanks!  And thanks for Qt 5.12 as well.

**Comment by Jocala** [comment]
Thanks again for packaging Qt 5.12 for msys2.  Will the static libraries be added as well?

**Comment by Alexpux** [comment]
@Jocala be patient, this is free time project
