### ISSUE TITLE
Repo git-2.20.1-1 has no .sig file at http://repo.msys2.org

### ISSUE THREAD

**Issue by TheOriginalFreddoFrog** [Alexpux/MSYS2-packages#1524]
Hi Folks,

The repo git-2.20.1-1 at http://repo.msys2.org/msys/i686 has no .sig file and is causing pacman -Syuu to break :-(

73

Steve I
Vk3VM / VK3SIR

**Comment by Alexpux** [comment]
@TheOriginalFreddoFrog fixed
