### ISSUE TITLE
Since last update Qt-static linked programs are 3 times larger

### ISSUE THREAD

**Issue by hkottmann** [Alexpux/MSYS2-packages#1527]
Yesterday I did an update of all packages. I have a small QT-program written that I link statically. Before the update the program had a size of 18MB, since the update when I compile it, the size is now 47MB.

**Comment by Alexpux** [comment]
This is wrong repo for mingw packages issues.
In any case issue probably because of https://github.com/Alexpux/MINGW-packages/pull/4587
