### ISSUE TITLE
ping in inetutils

### ISSUE THREAD

**Issue by jb-alvarado** [Alexpux/MSYS2-packages#153]
Hello,
is there a reason why the ping util is deactivated in inetutils? Right now I found out that I have no ping command in msys2 and in cygwin it was a part from inetutils. Or is it now in a other package included? 

Regards
Jonathan

**Comment by mingwandroid** [comment]
It's part of windows.

**Comment by elieux** [comment]
It'd be nice to have a "Linuxy" ping available, but extending the set of MSYS2 programs that are not essential for Windows development is not a goal for MSYS2; you can always use Cygwin. A mingw-w64 PKGBUILD for inetutils would be welcome, thought it seems that inetutils are not easily portable to native Windows (they're also not present in gnuwin32).

**Comment by Alexpux** [comment]
Cygwin also don't have ping from inetutils.

**Comment by elieux** [comment]
They have another ping though (http://ftp.arl.army.mil/~mike/ping.html).

**Comment by jb-alvarado** [comment]
Oh, this issue is still open... I had not the Windows PATH variable in my msys2 environment, now since I have it in, I can use the ping from windows and this is enough for me. So I think we can close here.

**Comment by divinity76** [comment]
@Alexpux 
> Cygwin also don't have ping from inetutils.

idk when it changed, but in 2022, [inetutils does include a linux-y ping](https://superuser.com/a/1480508/519577)
