### ISSUE TITLE
perl toolchain: xlocale.h

### ISSUE THREAD

**Issue by StefaE** [Alexpux/MSYS2-packages#1535]
Perl tool chain seems broken (fresh install following instructions on MSys2 home page. When installing packages which require c ...

> C:/Exec/MSys64/usr/lib/perl5/core_perl/CORE/perl.h:720:13: fatal error: xlocale.h: No such file or directory #   include <xlocale.h>

Looks very similar as over at [RedHat](https://bugzilla.redhat.com/show_bug.cgi?id=1464244); `perl -v`  tells me I've v5.28.1 and typing `cpan DBI` is sufficient to reproduce the issue.

Thx., Stefan

**Comment by StefaE** [comment]
I have:

> $ pacman -Q | grep runtime
msys2-runtime 2.11.2-1
msys2-runtime-devel 2.11.2-1

Yet, the issue persists.
Stefan

**Comment by StarWolf3000** [comment]
Is `/usr/include/xlocale.h` present? (`C:\Exec\MSys64\usr\include\xlocale.h` for your path)

Are you running the `cpan DBI` command from inside the terminal window (with MSYS2 environment loaded) or from outside?

**Comment by StefaE** [comment]
yes, `xlocale.h` is present.
I'm running `cpan DBI` from inside the terminal window known as `mingw64.exe`

**Comment by StarWolf3000** [comment]
> 
> yes, `xlocale.h` is present.
>
Good!
>
> I'm running `cpan DBI` from inside the terminal window known as `mingw64.exe`
>
This is the wrong environment. You need to run everything inside the environment loaded with `msys2.exe`. `msys32.exe` and `msys64.exe` load different paths (and the required file is not present in their paths).

**Comment by StefaE** [comment]
right - gcc not found; paths indeed change ...
>/bin/sh: gcc: command not found
make: *** [Makefile:509: Perl.o] Error 127
  TIMB/DBI-1.642.tar.gz
  /usr/bin/make -- NOT OK

**Comment by StarWolf3000** [comment]
`$ pacman -S base-devel msys2-devel` should meet your requirements.

**Comment by StefaE** [comment]
only after a further `pacman -S libcrypt-devel` ...

Thanks for your help, StarWolf3000. Without such excellent support, usability of MSys2 is heavily impeded by the lack of documentation ... Thx.

**Comment by Alexpux** [comment]
@StefaE you misunderstood the concept of MSYS/MINGW toolchains. You must not mix Development libraries and headers between MINGW and MSYS GCC. If you need Perl package for MINGW then you must use MINGW Perl and MINGW GCC to produce this package. In your error log it’s clear to see that you mix headers from /usr and /mingw64

**Comment by StefaE** [comment]
@Alexpux - thx., but I think then I'm back at where this thread started: Running a perl build (incl. eg. standard package DBI with `cpan DBI`) under `MinGWg4` fails with
> C:/Exec/MSys64/usr/lib/perl5/core_perl/CORE/perl.h:720:13: fatal error: xlocale.h: No such file or directory # include <xlocale.h>

**Comment by Alexpux** [comment]
@StefaE as I see there are no xlocale.h header for mingw, so you need fix it in some way

**Comment by StarWolf3000** [comment]
It used to be part of glibc, but has been removed some releases ago.

**Comment by StefaE** [comment]
is there a mingw perl anywhere?

**Comment by StarWolf3000** [comment]
> 
> is there a mingw perl anywhere?
>
`$ pacman -S mingw-w64-x86_64-perl`
`$ pacman -S mingw-w64-i686-perl`

![2kvdsg](https://user-images.githubusercontent.com/787808/50560929-e933e280-0d05-11e9-9c74-e43e489625d9.jpg)

**Comment by StefaE** [comment]
Point taken - I've asked better questions in the past; but I'm not as clever as ...

Anyway, that brings me as far as wanting to `cpam Module::Build`, which fails badly - at which point I realized that I was [shaving a yak](https://seths.blog/2005/03/dont_shave_that/), so I stay with my out-dated build process using MSys 1.0

Thanks for your contributions and Happy New Year!
