### ISSUE TITLE
error: failed retrieving file 'mingw32.db' from downloads.sourceforge.net : Failed to connect to ufpr.dl.sourceforge.net port 80

### ISSUE THREAD

**Issue by andalou** [Alexpux/MSYS2-packages#154]
I've newly installed MSYS2 on Windows 7, and I edited the mirrorlists on
/etc/pacman.d removing:
\#\# Primary
Server = ftp://148.251.42.38/MINGW/x86_64

Then, after doing 'pacman -Sy' I get:

$ pacman -Sy
:: Synchronizing package databases...
error: failed retrieving file 'mingw32.db' from downloads.sourceforge.net : Failed to connect to ufpr.dl.sourceforge.net port 80: Network is unreachable
error: failed to update mingw32 (download library error)
error: failed retrieving file 'mingw64.db' from downloads.sourceforge.net : Failed to connect to ufpr.dl.sourceforge.net port 80: Network is unreachable
error: failed to update mingw64 (download library error)
error: failed retrieving file 'msys.db' from downloads.sourceforge.net : Failed to connect to ufpr.dl.sourceforge.net port 80: Network is unreachable
error: failed to update msys (download library error)
error: failed to synchronize any databases
error: failed to init transaction (download library error)

**Comment by mingwandroid** [comment]
The sourceforge mirror must be down then. You'll probably have to wait until it is up again.

**Comment by andalou** [comment]
How long would it take until it is up again?
It's already been two days and I keep getting the same messages!

**Comment by Alexpux** [comment]
Maybe something wrong with your internet connection? It works ok.

**Comment by andalou** [comment]
Actually I don't have any problem with my internet connection.
Isn't there any other mirror to run this command from?
Or perhaps is it the timeout? Can I enlarge the timeout for this command?

**Comment by mingwandroid** [comment]
Ufpr mirror must be down. Try contacting sourceforge, or put a different
one in the /etc/pacman.d mirror files.
