### ISSUE TITLE
fish broken

### ISSUE THREAD

**Issue by Optiligence** [Alexpux/MSYS2-packages#1551]
It’s missing a dependency of `libpcre2_16` but also doesn’t start after that’s installed.

**Comment by orthoxerox** [comment]
See https://github.com/fish-shell/fish-shell/issues/5426

**Comment by Alexpux** [comment]
@orthoxerox use always ````__CYGWIN__```` GCC internal defines to distingish Cygwin/MSYS. Don't define your own ````CYGWIN```` from cmake

**Comment by orthoxerox** [comment]
@Alexpux that's something @mqudsi should take a look at, but I see you've already commented on their PR. I guess this is an extra one line patch for the MSYS2 package when 3.0.1 comes around if they don't fix it upstream.

**Comment by mqudsi** [comment]
Thanks for that info, I'll look into updating it. Regardless of `CYGWIN` or `__CYGWIN__`, the fish package maintainers are recommended to move over to cmake as we will be removing support for the autotools build system.

**Comment by Turbid** [comment]
I confirm this:
`C:/msys64/usr/bin/fish.exe: error while loading shared libraries: msys-pcre2-16-0.dll: cannot open shared object file: No such file or directory`

After installing libpcre2_16 it does not work.

**Comment by Optiligence** [comment]
my 2 cents: since the older version still works i would like the the update to be revoked/push to pacman repo with old version – in cases like this
It prevents broken updates for users that haven’t updated yet and allows easy downgrade via `pacman -Syuu` for those who already have. 
@Alexpux

**Comment by ZombineDev** [comment]
I workend around the problems with this commit:
https://github.com/ZombineDev/MSYS2-packages/commit/7acd480f8c0deec3b5e3c241ca6bf568a85f9a18

**Comment by mqudsi** [comment]
You need to use the code from fish master or the fish 3.0.1 branch.

**Comment by nyfair** [comment]
I confirm that 3.0.1 already fix this issue
