### ISSUE TITLE
subversion hangs with https://

### ISSUE THREAD

**Issue by dfgtyx** [Alexpux/MSYS2-packages#1561]
Any https address whether a repo or not leads to a hard hang.  For instance, on my windows 10 laptop (64 bit)

svn ls https://www.google.com

hangs and send my CPU to 100%

**Comment by TerminX** [comment]
This happens here as well. Been broken for over a month.

**Comment by totaam** [comment]
Same here, had to switch to tortoisesvn.
I keep forgetting then it gets stuck, forcing me to fire up the task manager, kill svn.exe then run svn cleanup... Tedious.

**Comment by nga888** [comment]
Yes, I've seen the same issue with git svn and Perl going into an infinite loop.

I believe it is linked to this problem in OpenSSL https://github.com/openssl/openssl/issues/2865.

**Comment by intvsteve** [comment]
Seeing this with an svn export as well.  Also running Windows 10.  Meantime I'm working around by using my decrepit old MSYS environment.

FWIW, I downgraded svn thinking it was related to the other issues surrounding svn 1.11 and GitHub that happened late last year.  That doesn't help.  I traced it to an infinite loop in msys-crypto-1.1.dll.

**Comment by Alexpux** [comment]
try updat packages and see if issue is solved. Recently was openssl rebuilded with patch for infinite loops

**Comment by totaam** [comment]
@Alexpux : the openssl has fixed it, yay!
I think you can close this ticket.
