### ISSUE TITLE
Problem parsing semicolon when running a command using system() from stdlib.h

### ISSUE THREAD

**Issue by monkeycode222** [Alexpux/MSYS2-packages#1563]
When running this c program
``` c
#include <stdlib.h>
   
int main()
{
    system("touch f1 ; touch f2");
    return 0;
}
```
it creates unexpected files on the working dir
``` bash
$ ls
';'   f1   f2   touch
```
running the same command directly from the shell creates the expected files
``` bash
$ touch f1 ; touch f2
$ ls
f1  f2
```

My MSYS2 version:
``` bash
$ uname -a
MINGW64_NT-6.1 PC 2.11.2(0.329/5/3) 2018-11-26 09:22 x86_64 Msys
```

**Comment by StarWolf3000** [comment]
Commands issued by `system()` do not use `bash` or any other *NIX shell on Windows in MSYS2/MINGW, they're run by `cmd.exe instead`. `cmd.exe` does not use `;` to separate multiple commands, so the result of `touch f1 ; touch f2` is to create 4 files in the current directory: `f1`, `;`, `touch` and `f2`.

**Comment by monkeycode222** [comment]
It makes sense! My mistake. Thanks
