### ISSUE TITLE
How can I install the NEdit editor via pacman?

### ISSUE THREAD

**Issue by aks2161989** [Alexpux/MSYS2-packages#1567]
Hi,

I want to install the NEdit editor on windows. Since msys2 comes with the arch Linux port of pacman, I expected it to install NEdit through the `pacman -S NEdit` command. However, I get the message "target not found". NEdit is available in the arch Linux repositories (https://www.archlinux.org/packages/community/x86_64/nedit/).

Can anyone offer any tips?

Thanks!

**Comment by Alexpux** [comment]
MSYS2 is windows target, not Linux. MSYS2 doesn’t use Arch Linux repositories, so you need build NEdit yourself
