### ISSUE TITLE
sourceforge hosted mirror in unavailable

### ISSUE THREAD

**Issue by RumataEstor** [Alexpux/MSYS2-packages#165]
The project seems to be removed from sourceforge. The only mirror left in pacman-mirrors is pointing to sourceforge, so now there is no working mirrors in an installed system.

**Comment by Alexpux** [comment]
You are wrong. Just source forge.net was unavailable about 8 hours. Now all working.

**Comment by RumataEstor** [comment]
Yes, not it's all right.

When I had the problem, sourceforge.net was available, but MSYS2 project was not found and all the cached links were pointing to 404 page.

**Comment by Alexpux** [comment]
Now all pages are available
