### ISSUE TITLE
Msys2-Filesystem removes customized /etc/group and /etc/passwd files

### ISSUE THREAD

**Issue by BrisingrAerowing** [Alexpux/MSYS2-packages#166]
Would it be possible to make it NOT do that? I use a customized /etc/passwd file for portability (running off of a USB3 HDD) and having it removed every time the filesystem is upgraded is quite annoying.

**Comment by rossy** [comment]
+1. I also use a custom passwd and group.

**Comment by Alexpux** [comment]
Fixed in filesystem-2015.2-2
