### ISSUE TITLE
Anti-Virus flags gspawn-win32-helper.exe as adware

### ISSUE THREAD

**Issue by Kevin551** [Alexpux/MSYS2-packages#169]
Have just run pacman -Syu
My anti-virus program F-Secure quarantines gspawn-win32-helper.exe as Gen:Variant.Adware.SMSHoax.71
I assume this is a false positive.

**Comment by mingwandroid** [comment]
Report it to F-Secure?

**Comment by martell** [comment]
http://portableapps.com/node/3972#comment-18432

Fsecure have falsely tagged this in the past.
They will investigate and fix the false report if you email them

**Comment by achadwick** [comment]
Bitdefender, F-Secure, and a few other presumably signature-based systems are lighting up this same bit of adware (`Gen:Variant.Adware.SMSHoax.71`) in a couple of recent-ish versions of the GLib package too in VirusTotal:

* `mingw-w64-i686-glib2-2.46.2-3-any.pkg.tar.xz`
  * Report: <https://www.virustotal.com/en/file/543c636057d786b20d797a80486e1fa0efecb5af1d3cdc2bdc4d5e9288d382dc/analysis/1451757321/>
* `mingw-w64-i686-glib2-2.44.1-2-any.pkg.tar.xz`
  * Report: https://www.virustotal.com/en/file/b114d8634b8de5c101f16b3437cbdf3e42bebab903a19c7fd54b8c7e9d12d989/analysis/1451756922/

This is the package containing `mingw32/bin/gspawn-win32-helper.exe`. Evidently the scanner does some unpacking.

Brought to my attention in <https://twitter.com/fennekki_/status/683163636936871936> for that 2.44.1-2 version. I'll continue to investigate as much as I can. Let's see if <https://malwr.com> can be persuaded to say anything about about the contents, for starters.

**Comment by mingwandroid** [comment]
Like this:
https://malwr.com/analysis/NjE2ODIwNjExYjBhNDAwYmIzMzkxNmY5NWM5ZDY0YjM/

Not sure what that means?

**Comment by achadwick** [comment]
Hmm, the exe in question needs libwinpthread to link at runtime, so I guess malwr won't do anything if that DLL isn't present.

I think it can do stuff with zipfiles, but my cobbled-together initial attempt produced "Error: Analysis failed: The package "modules.packages.zip" start function raised an error: Unable to execute the initial process, analysis aborted." :neutral_face:

**Comment by achadwick** [comment]
My gut feeling: probably a false positive. But that's only a gut feeling.

**Comment by mingwandroid** [comment]
My opinion of the virus scanning 'industry' couldn't be much lower; all that fear mongering, cash and CPU cycles and environmental damage for so little .. but we need fully reproducible builds [1] before we have anything concrete in our corner.

https://reproducible-builds.org/
