### ISSUE TITLE
Tab-completion in bash doesn't work well outside PATH

### ISSUE THREAD

**Issue by elieux** [Alexpux/MSYS2-packages#181]
Experienced by me and xod from IRC. If I go to a build directory with these files:
```
config.h
config.hin
config.log
config.status
configure
configure.ac
configure.orig
```
and write `./con` and press Tab, I don't get any suggestions from bash.

xod also sometimes gets `config.guess` right away, which is wrong.

Cygwin behaves properly by completing to `./config` and showing a list of options on second Tab press.

**Comment by martell** [comment]
I assume there are a few #ifdefs for cygwin we need to add msys to.
Take a look at 7b767f6 maybe what you need is in there

**Comment by Alexpux** [comment]
No. "__CYGWIN__" is defined for MSYS2 always.

**Comment by martell** [comment]
ahh right I didn't know that.
Must be a bug there somewhere then

**Comment by Alexpux** [comment]
I'm upload new bash packages. Try it.

**Comment by elieux** [comment]
@martell, yes. @Alexpux, thanks. The `./con` testcase now works. I'll try asking xod if his problems are resolved, too.

**Comment by elieux** [comment]
xod reports it works, too.
