### ISSUE TITLE
gitk very very very slow to start

### ISSUE THREAD

**Issue by KrullKorg** [Alexpux/MSYS2-packages#190]
about 1 minute to complete the visualization of a very little reposistory

then it seams to work normaly

**Comment by elieux** [comment]
How do you run it? Since tcl/tk is only available as a mingw-w64 package, I need to run from a mingw shell, but even then it always says `cannot find a Git repository here`.

**Comment by KrullKorg** [comment]
i think the problem is again only for machine under domain; i just tried at home and it works perfectly

**Comment by KrullKorg** [comment]
also emacs is very slow when it opens/saves files

**Comment by KrullKorg** [comment]
i just tried gitk and emacs under cygwin and they work perfectly

**Comment by elieux** [comment]
Can we close this issue and continue in #138, since you're already posting there, too?

**Comment by KrullKorg** [comment]
yes, if it is the same thing
