### ISSUE TITLE
Crash whem installing latest msys2-runtime

### ISSUE THREAD

**Issue by juergenpf** [Alexpux/MSYS2-packages#199]
When using pacman -Su and latest msys2-runtime gets updated, my MSYS2 crashes with a stack trace and from then on it's unusabe. Tried autorebase from an admin cmd, but just get also the stack trace. What's going wrong here (n.b. this only happens on some of my machines)

C:\msys64>.\autorebase.bat
      0 [main] dash 18844 C:\msys64\usr\bin\dash.exe: **\* fatal error - user sha
red memory size mismatch detected - 0x11328/0x8A28.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version _should_
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
Stack trace:
Frame        Function    Args
0000024CBC0  0018006FCCE (0018020B321, 0018020AE59, 00000008A28, 0000024BA20)
0000024CBC0  00180046E22 (0000024CA88, 00000110010, 0018020B12D, 00000000000)
0000024CBC0  00180046E62 (00180263FD5, 00000011328, 00000008A28, 00180254850)
0000024CBC0  00180048429 (001800473A0, 0000024CE00, 001800CAA68, 00000000000)
0000024CBC0  00180121675 (00000000000, 00000000000, 00000000000, 00000000000)
0000024CBC0  00180047415 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  0018004603C (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  001800460D4 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100410F71 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100401010 (00000000000, 00000000000, 00000000000, 00100401000)
00000000000  7FFC7DA75F32 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  7FFC7DF75D04 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace

**Comment by oysteinkrog** [comment]
This has happened twice for me now, basically requiring a reinstall.
I did the correct update procedure as specified in the documentation.

**Comment by elieux** [comment]
I'm not sure what happened here. Can you check the [BLODA](https://cygwin.com/faq/faq.html#faq.using.bloda)? Do you have any Cygwin-compiled programs in `PATH`?

**Comment by elieux** [comment]
Closing due to missing follow-up information.
