### ISSUE TITLE
Remove nasm and yasm from base-devel

### ISSUE THREAD

**Issue by elieux** [Alexpux/MSYS2-packages#206]
Shouldn't `nasm` and `yasm` packages be moved from `base-devel` to `msys2-devel` and `mingw-w64-{i686,x86_64}-{y,n}asm` be added to `mingw-w64-{i686,x86_64}-toolchain`? Current situation seems inconsistent.

**Comment by Alexpux** [comment]
We don't have ````msys2-devel```` group. And why we need add mingw versions of nam/yasm to ````toolchain```` group?

**Comment by elieux** [comment]
If I understand the strategy behind the groups correctly, `base-devel` only contains tools that are common to both msys2 and mingw development, so since there are both msys2 and mingw versions of nasm/yasm available, they should go to the respective toolchain groups instead.

Alternatively, if it's okay to have them in `makedepends`, then just removing them from `base-devel` would probably be the right thing to do.
