### ISSUE TITLE
zsh: fatal error: sgtty.h: No such file or directory

### ISSUE THREAD

**Issue by KoltesDigital** [Alexpux/MSYS2-packages#207]
I've just installed _msys2-x86_64-20150202.exe_ and wanted to install zsh.

``` sh
foo@bar MINGW64 ~/MSYS2-packages/zsh
$ makepkg
...
gcc -c -I. -I../Src -I../Src -I../Src/Zle -I. -D_FORTIFY_SOURCE=2  -DHAVE_CONFIG_H -march=x86-64 -mtune=generic -O2 -pipe  -o builtin.o builtin.c
In file included from zsh.mdh:15:0,
                 from builtin.c:33:
zsh_system.h:420:21: fatal error: sgtty.h: No such file or directory
 #  include <sgtty.h>
                     ^
compilation terminated.
```

FYI configure outputs (excerpt)

``` sh
checking where the RLIMIT macros are located... restmp.c:1:26: fatal error: sys/resource.h: No such file or directory
 #include <sys/resource.h>
                          ^
compilation terminated.
/dev/null
```

``` sh
zsh configuration
-----------------
zsh version               : 5.0.7
host operating system     : x86_64-pc-msys
source code location      : .
compiler                  : gcc
preprocessor flags        : -D_FORTIFY_SOURCE=2
executable compiler flags : -march=x86-64 -mtune=generic -O2 -pipe
executable linker flags   : -pipe
library flags             : -lpcre -liconv -lncursesw -lm
installation basename     : zsh
binary install path       : /usr/bin
man page install path     : /usr/share/man
info install path         : /usr/share/info
functions install path    : /usr/share/zsh/functions
```

Is there a package for this?

**Comment by Alexpux** [comment]
are you install msys2-runtime-devel?

**Comment by Bloutiouf** [comment]
I didn't, but there is still the error.

In the meantime, I found that `pacman -S zsh` works ([see this blog](http://qiita.com/magichan/items/7702d7865deaaca2ad44)). What is the difference then?

**Comment by elieux** [comment]
Just checking; did you [update your installation](https://sourceforge.net/p/msys2/wiki/MSYS2%20installation)?

**Comment by Bloutiouf** [comment]
When I got this error, it was a fresh install. Since then I haven't checked.

**Comment by elieux** [comment]
So you did not update? As the installer name (msys2-x86_64-20150202.exe) suggests, the installer is from February, so you need to run an update to get from "fresh" to "up-to-date". :)

**Comment by Bloutiouf** [comment]
At that time it was the latest version, stable I guess. After that I found that the package from pacman works, so I'm using it instead of trying to compile from this repo. I haven't understood the difference between the two, maybe you know?

**Comment by elieux** [comment]
The `zsh` package is compiled by us and then `pacman -S zsh` just downloads and installs it onto your computer. With `makepkg`, the compilation happens on your computer. Sometimes the GitHub repository contains a newer version of the package (happens regularly with `-git` and `-svn` packages).

**Comment by Bloutiouf** [comment]
Ok I hadn't understood that part. I'll retry compiling the package soon then.
