### ISSUE TITLE
Gettext doesn't works under GBK ANSI env.

### ISSUE THREAD

**Issue by lygstate** [Alexpux/MSYS2-packages#208]
$ msgfmt --help
▒÷▒▒▒C:\CI-Tools\vcs\Git-New\mingw64\bin\msgfmt.exe [ѡ▒▒] ▒ļ▒▒▒.po ...

▒▒▒▒▒▒ģʽ▒▒▒▒▒▒▒ɶ▒▒▒▒▒▒▒Ϣ▒ļ▒▒▒

▒▒ѡ▒▒▒▒▒▒õĲ▒▒▒▒▒ʹ▒ö▒ѡ▒▒ʱҲ▒Ǳ▒▒▒ġ▒
▒▒ѡ▒▒▒▒Ҳ▒▒▒▒ˡ▒

▒▒▒▒▒ļ▒▒▒λ▒ã▒
  ▒ļ▒▒▒.po ...               ▒▒▒▒▒ļ▒
  -D, --directory=Ŀ¼        ▒▒<Ŀ¼>▒в▒▒▒▒▒▒▒▒ļ▒
▒▒▒▒▒▒▒▒ļ▒Ϊ -▒▒▒򽫶▒ȡ▒▒׼▒▒▒롣

▒▒▒▒ģʽ▒▒
  -j, --java                  Java ģʽ▒▒▒▒▒▒ Java ▒▒Դ▒▒▒▒
      --java2                 ▒▒▒▒ --java▒▒▒▒▒▒▒▒▒▒ Java2 (JDK 1.2 ▒▒▒▒▒
                              ▒İ汾)
      --csharp                C# ģʽ▒▒▒▒▒▒ .NET .dll ▒ļ▒
      --csharp-resources      C# ▒▒Դģʽ▒▒▒▒▒▒ .NET .resources ▒ļ▒
      --tcl                   Tcl ģʽ▒▒▒▒▒▒ tcl/msgcat .msg ▒ļ▒
      --qt                    Qt ģʽ▒▒▒▒▒▒ Qt .qm ▒ļ▒
      --desktop               Desktop Entry mode: generate a .desktop file

▒▒▒▒ļ▒λ▒ã▒
  -o, --output-file=▒ļ▒      ▒▒▒▒▒д▒▒ָ▒▒▒ļ▒
      --strict                ʹ▒▒▒ϸ▒▒ Uniforum ģʽ
▒▒▒▒▒▒▒ļ▒▒▒ -▒▒▒▒Ὣ▒▒▒д▒▒▒▒▒▒׼▒▒▒▒▒

▒▒ Java ģʽ▒▒▒▒ļ▒λ▒ã▒
  -r, --resource=▒▒Դ         ▒▒Դ▒▒▒▒
  -l, --locale=▒▒ϵ           ▒▒ϵ▒▒▒ƣ▒▒▒▒▒▒ǡ▒▒▒▒ԡ▒▒▒▒▒▒▒_▒▒▒ҡ▒▒ĸ▒ʽ
      --source                produce a .java file, instead of a .class file
  -d Ŀ¼                     ▒▒Ŀ¼▒▒εĻ▒▒▒Ŀ¼
▒▒▒▒▒▒▒▒▒▒▒▒Դ▒▒▒▒▒▒ͬ▒▒ϵ▒▒▒ƹ▒ͬ▒▒▒▒▒ģ▒▒▒▒▒֮▒▒▒▒▒▒»▒▒߷ָ▒▒▒
-d ѡ▒▒▒Ǳ▒▒▒ġ▒class ▒ļ▒▒▒▒▒▒▒ָ▒▒▒▒Ŀ¼▒▒

▒▒ C# ģʽ▒▒▒▒ļ▒λ▒ã▒
  -r, --resource=▒▒Դ         ▒▒Դ▒▒▒▒
  -l, --locale=▒▒ϵ           ▒▒ϵ▒▒▒ƣ▒▒▒▒▒▒ǡ▒▒▒▒ԡ▒▒▒▒▒▒▒_▒▒▒ҡ▒▒ĸ▒ʽ
  -d Ŀ¼                     ▒▒▒▒▒▒ϵ▒▒ .dll ▒ļ▒▒ĵĻ▒▒▒Ŀ¼
-l ▒▒ -d ѡ▒▒▒Ǳ▒Ҫ▒ġ▒.dll ▒ļ▒▒▒д▒▒ָ▒▒Ŀ¼▒▒▒▒Ŀ¼▒▒▒▒▒▒Ŀ¼▒▒▒▒▒▒ȡ▒▒▒▒▒▒ϵ▒▒

▒▒ Tcl ģʽ▒▒▒▒ļ▒λ▒ã▒
  -l, --locale=▒▒ϵ           ▒▒ϵ▒▒▒ƣ▒▒▒▒▒▒ǡ▒▒▒▒ԡ▒▒▒▒▒▒▒_▒▒▒ҡ▒▒ĸ▒ʽ
  --d Ŀ¼                    .msg ▒▒Ϣ▒▒Ļ▒▒▒Ŀ¼
-l ▒▒ -d ѡ▒▒▒Ǳ▒Ҫ▒ġ▒▒▒▒▒▒ɵ▒ .msg ▒ļ▒▒▒▒▒▒▒ָ▒▒▒▒Ŀ¼▒▒

Desktop Entry mode options:
  -l, --locale=▒▒ϵ           ▒▒ϵ▒▒▒ƣ▒▒▒▒▒▒ǡ▒▒▒▒ԡ▒▒▒▒▒▒▒_▒▒▒ҡ▒▒ĸ▒ʽ
  -o, --output-file=▒ļ▒      ▒▒▒▒▒д▒▒ָ▒▒▒ļ▒
  --template=TEMPLATE         a .desktop file used as a template
  -d DIRECTORY                base directory of .po files
  -kWORD, --keyword=WORD      ▒▒▒▒ WORD ▒▒Ϊһ▒▒▒▒▒▒Ĺؼ▒▒▒
  -k, --keyword               ▒▒ʹ▒▒Ĭ▒Ϲؼ▒▒▒
The -l, -o, and --template options are mandatory.  If -D is specified, input
files are read from the directory instead of the command line arguments.

▒▒▒▒▒ļ▒▒▒▒﷨▒▒
  -P, --properties-input      ▒▒▒▒▒ļ▒▒▒ Java .properties ▒﷨▒▒▒▒
      --stringtable-input     ▒▒▒▒▒ļ▒▒▒ NeXTstep/GNUstep .strings ▒﷨▒▒▒▒

▒▒▒▒▒ļ▒▒Ľ▒▒ͣ▒
  -c, --check                 ͬʱ▒▒▒▒ --check-format▒▒--check-header ▒▒
                                --check-domain ▒▒▒ּ▒▒
      --check-format          ▒▒▒▒▒▒▒▒▒йصĸ▒ʽ▒ַ▒▒▒
      --check-header          ▒▒▒▒ļ▒ͷ▒▒▒Ƿ▒▒▒ڼ▒▒▒▒▒▒▒▒▒▒
      --check-domain          ▒▒▒ domain ָ▒▒▒ --output-file ѡ▒▒֮▒▒
                                ▒Ƿ▒▒ͻ
  -C, --check-compatibility   ▒▒ GNU msgfmt ▒▒ X/Open msgfmt ▒ķ▒ʽ▒▒▒▒ļ▒
      --check-accelerators[=CHAR]  ▒▒▒˵▒▒▒Ŀ▒еĿ▒ݼ▒▒▒▒▒Ƿ▒▒▒▒
  -f, --use-fuzzy             ▒▒▒▒▒▒▒ʹ▒▒ģ▒▒▒ķ▒▒▒▒▒Ŀ

▒▒▒ϸ▒ڣ▒
  -a, --alignment=▒▒▒▒        ▒▒<▒▒▒▒>▒▒▒ֽ▒Ϊ▒▒λ▒▒▒▒▒ַ▒▒▒(Ĭ▒ϣ▒1)
      --endianness=BYTEORDER  ▒▒ָ▒▒▒ֽ▒▒▒▒▒▒ 32λ▒▒
                                (big ▒▒▒▒ little ▒▒ϵͳƽ̨Ĭ▒ϵ▒)
      --no-hash               ▒▒▒▒▒▒▒ļ▒▒▒▒▒▒▒▒▒▒▒ϣ▒▒

▒▒Ϣ▒▒▒▒▒▒▒
  -h, --help                  ▒▒ʾ▒˰▒▒▒▒▒▒˳▒
  -V, --version               ▒▒▒▒汾▒▒Ϣ▒▒▒˳▒
      --statistics            ▒▒ӡ▒▒▒ڷ▒▒▒▒ͳ▒▒
  -v, --verbose               ▒▒▒▒▒▒▒▒▒▒▒ϸ▒̶▒

▒▒▒▒▒󱨸▒▒▒ <bug-gnu-gettext@gnu.org>▒▒

**Comment by Alexpux** [comment]
run like:
````LANGUAGE=en_US.UTF-8 msgfmt --help````

**Comment by lygstate** [comment]
@Alexpux It's different under different shell'
Mingw64 shell
```
~PC MINGW64 /usr/bin
$ msgfmt
C:\CI-Tools\vcs\Git-New\mingw64\bin\msgfmt.exe: û▒и▒▒▒▒▒▒▒▒ļ▒
▒▒▒ԡ▒C:\CI-Tools\vcs\Git-New\mingw64\bin\msgfmt.exe --help▒▒▒鿴▒▒▒▒▒▒Ϣ▒▒

~PC MINGW64 /usr/bin
$
```

```
~PC MSYS /usr/bin
$ msgfmt
msgfmt: 没有给出输入文件
试试“msgfmt --help”查看帮助信息。

~-PC MSYS /usr/bin
$


```

**Comment by lygstate** [comment]
@Alexpux LANGUAGE=en_US.UTF-8 msgfmt --help can works, but make the output always to be
English, and all locale translation doesn't works.

**Comment by lygstate** [comment]
When I using the mingw64 version, the msgfmt always crashes when I am not running under mintty env, and after I remove all /mingw64/share/locale/* files,
the msgfmt doesn't crash anymore, so the msgfmt /gettext for mingw64 is problem, and this will cause all localized apps crash.
