### ISSUE TITLE
Feature request: Environment variables for msys2 root in Windows environment with Windows path-syntax

### ISSUE THREAD

**Issue by bagong** [Alexpux/MSYS2-packages#213]
Hi,

I am trying to make cmake find-modules find libraries installed in the mingw32/64 tree, and I would like to do it in a way that a cmake running directly under Windows can also find them. Them mingw32/bin, lib etc folders I presume can be relied upon as hardcoded path elements, but the msys root folder and Win-drive could be called almost anything, right? Wouldn't it be useful to have a Windows system env variable that returns the msys root path? Or is there somethink like that?

**Comment by mingwandroid** [comment]
Having cmake pick up msys2 libraries and headers would not be wanted when building mingw?? software (and vice versa). Am I misunderstanding you?

**Comment by bagong** [comment]
Sorry, my question must be put confusing. I want cmake to (optionally) pick up libraries and headers stored in the mingw-tree (which is a subfolder of the msys2 root) in order to build another application alltogether. This app I would like to have the option to build outside of msys. So it's not msys libraries I want, but "native windows" ones stored in the mingw folders.
So to give a specific example: build an application called supercollider with cmake, that depends on libraries and headers from libsndfile, portaudio, fftw and readline. Using cmake I can build supercollider outside of msys (I think), but it would be helpful if I could address the locations of the libraries with variables returning specifics of a users msys2 install. One user might have the libsndfile-1.dll in G:\msys64\mingw32\bin, another one in C:\msys\mingw32\bin. That first part of the path I would like to read from an environment variable.

**Comment by mingwandroid** [comment]
Our mingw-w64 compilers search in the /mingw??/lib and mingw??/include paths already and cmake queries gcc for those paths. The only use case for what you are asking for seems to be if you are using non-MSYS2 supplied mingw-w64 compilers but wanting to link to MSYS2's mingw-w64 libraries. This is a bad idea for various compatibility reasons so isn't something we should do anything to support .. Again if I'm still missing something here let me know.

**Comment by mingwandroid** [comment]
cmake doesn't need to concern itself with msys2 paths since msys2 converts the paths to windows form before cmake sees them.. Usually!

**Comment by bagong** [comment]
As to your second statement: well, that's true if compiling from inside the msys environment. My wish would be to be able to use the mingw toolchain, and all packages stored inside the mingw tree to build from outside the msys environment. This could be cmake on the win-command line or Qt Creator running outside of msys, but using the mingw-toolchain provided by you.

So a use case that I think would make sense for my request: msys2, next to providing a unixish environment for unix build tools, and a Windows gcc-toolchain, *also* provides a package manager for native Windows apps that are build with that toolchain, right? In my case I need msys2 to build portaudio, because it cannot be built with cmake easily. But for the other dependencies it is enough for me to use mingw as a toolchain and libraries/packages repository... So I could actually build outside of msys, right? While the mingw-toolchain knows itself where _it's_ libraries are, cmake doesn't automatically know where to find packages like libsndfile and portaudio. Am I overlooking something?

**Comment by elieux** [comment]
If you're using cmake from mingw??, it should be able to find everything.

Anyway, one problem with your proposition -- users can have multiple independent MSYS2 roots. Your build script/system should probably require users to specify the path to the sysroot manually (but in an easy-to-understand way).

**Comment by bagong** [comment]
> If you're using cmake from mingw??, it should be able to find everything.

That's an interesting suggestion, thanks! I could define the library paths relative to the cmake binary location then (there is a cmake variable for this). But I see two problems: people trying their luck with cmake installed under Windows will run into trouble. And I'd have to add mingw??/bin to the system path, which seems like more hassle and problem prone than defining a sysroot manually.

> users can have multiple independent MSYS2 roots.

Ah, true, but maybe a corner case? Each install could overwrite the old variable, so only the last one is automatic. Users that can handle multiple msys2 installs wouldn't be too challenged with the requirement to define the variable value manually, I think. I am more concerned of users that dare to enter the field of building since there now is a very convenient build system...

**Comment by bagong** [comment]
Rethinking the set the path requirement: maybe that's a strong reason not to encourage building from outside msys. So maybe not a good idea... ;) Should I close the issue?

**Comment by mingwandroid** [comment]
Generally speaking, MSYS2 aims to work as well as possible without any requirement to add anything to your system's PATH variable.

However for us to have any chance of making this work (and in general for MSYS2 software to interoperate correctly), we need to modify various bits of software so that for example relative paths are used. Therefore using non-MSYS2 versions of software (for example cmake and qt creator) will never be something we make significant efforts to support. If said software is missing from MSYS2 then we'll add it or welcome contributions that do that, if it's software we already package then the user will be required to use our version unless they can strongly justify not doing so. I can't imagine any valid reason not to at present.

Having said that, launching MSYS2 software (both msys2 and mingw?? stuff) from outside msys2_shell.bat and mingw??_shell.bat is something we do support as much as is reasonable.

So for example you should be able to run our CMake from cmd.exe, generating mingw Makefiles and then be able to use mingw32_make.exe from the same cmd.exe to build the thing, both without modifying PATH. At that stage the user might need to identify a toolchain file to CMake but that's standard CMake usage procedure anyway.

Qt Creator is a little more tricky though because the qt concept of 'Kits' IMHO needs to include the ability to modify the build and run environments similarly to how the Project settings page does.

**Comment by bagong** [comment]
Thanks a lot for the well considered and friendly comments in this thread! A nice community!

**Comment by mingwandroid** [comment]
Generally speaking, when I use MSYS2 stuff from within cmd.exe first I'll do:

set "PATH=C:\msys64\mingw64\bin;%PATH%"
.. then execute what I want.

That way, for example, cmake finds GCC without further prompting.

**Comment by bagong** [comment]
Yea, my last suggestion was to offer a shell that does that automatically, and add a env variable that allows to derive the mingw sysroot independently of the msys install location. That way one could write cmake find modules easily in a way that a user could configure/compile with cmake without having to specify any paths. So compiling would boil down to `cmake ..` and `cmake --build . --config debug --target install`, all of which is easy to memorize and makes sense. Writing a toolchain file or specifying 5 paths to libraries is very error prone and turns away people...
But it's not a big deal, I admit, and I understand that a msys centered project has more important things to do than make msys obsolete (no sarcasm meant!!) ;)

**Comment by bagong** [comment]
Just another word to confirm that @elieux is right and my assumption was wrong:
If you build in a Windows command line with cmake, using msys2-provided mingw-cmake, it does in fact back-convert the unix-style paths provided in find-modules to Windows paths (well, maybe it doesn't, but it finds modules at a path that is syntactically incorrect on a Windows command line). So as lang as we are willing to use mingw-cmake everything is fine. I have two versions of cmake installed on my system (using the Win one for VS) just separated by the order in the path :) So far I have not met any problem with this. Very nice!
