### ISSUE TITLE
msys2-runtime update causes issue in text output

### ISSUE THREAD

**Issue by samrg472** [Alexpux/MSYS2-packages#215]
Updating to version 2.1.0.16305.2579661 causes an issue in text output formatting on Windows software. This issue is not present in version 2.0.16506.ec7f957-1 which comes packaged with the msys2-x86_64-20150202 installer.

The issue is the terminal is not splitting on line breaks when running Windows software such as Java.
If you run `java >& out; cat out` the output is normal in the terminal.

**Comment by elieux** [comment]
This is a known issue recently introduced in Cygwin. A fix should be available soon-ish (in a week or two, I guess).

**Comment by elieux** [comment]
This should be resolved in 2.1.0.16349.9da8ac1-1. Can you confirm / close the issue?

**Comment by samrg472** [comment]
Confirmed fixed.
