### ISSUE TITLE
libffi-devel doesn't put headers in /usr/include

### ISSUE THREAD

**Issue by Mischanix** [Alexpux/MSYS2-packages#216]
had to copy from $CHOST/include/*.h after running libtool/configure

**Comment by Alexpux** [comment]
I don't understand what you mean.

**Comment by Mischanix** [comment]
Installing libffi-devel should put ffi.h and ffitarget.h in the system include path.  It currently does not.  These headers can be found in ${CHOST}/include/, but are not copied to $DEST/usr/include by `make install`.

**Comment by Alexpux** [comment]
it install them in it's standard location: ````/usr/lib/libffi-3.2.1/include````
