### ISSUE TITLE
Add mirror

### ISSUE THREAD

**Issue by svnpenn** [Alexpux/MSYS2-packages#221]
The only other mirror was killed with 10470cb, making SourceForge the only
current mirror. SourceForge is slow as fuck, as many know.

Please add a new mirror to rectify this.

**Comment by Alexpux** [comment]
We don't have infrastructure for it, so it will not be added in near time

**Comment by svnpenn** [comment]
Here are some fast Cygwin mirrors, generated with [this script][1]. Consider
contacting some of them, they might offer free hosting.

    http://cygwin.osuosl.org
    http://lug.mtu.edu/cygwin
    http://cygwin.mirror.rafal.ca
    ftp://mirrors.sonic.net/cygwin
    http://cygwin.mirrors.pair.com
    ftp://mirror.nexcess.net/cygwin
    http://mirrors.sonic.net/cygwin
    http://mirror.nexcess.net/cygwin
    ftp://mirror.steadfast.net/cygwin
    http://mirror.steadfast.net/cygwin
    http://mirrors.xmission.com/cygwin
    http://mirror.team-cymru.org/cygwin
    ftp://ftp.gtlib.gatech.edu/pub/cygwin
    ftp://mirrors-usa.go-parts.com/cygwin
    http://mirror.csclub.uwaterloo.ca/cygwin
    http://mirror.cs.vt.edu/pub/cygwin/cygwin
    http://mirror.cpsc.ucalgary.ca/mirror/cygwin.com

[1]:http://github.com/svnpenn/a/blob/3d02578d83ef543d80b4/misc/cygwin-mirrors.sh

**Comment by svnpenn** [comment]
Here is one link, looks like they may have free hosting

http://osuosl.org/request-hosting

**Comment by svnpenn** [comment]
@Alexpux here is one link, looks like they may have free hosting

http://osuosl.org/request-hosting

**Comment by elieux** [comment]
Just putting some more info here:
 - in March, I asked heanet.ie to host a mirror, but they haven't replied
 - one of our users managed to make a mirror, but I'm not sure what's the status on that (and I don't want to make any more information public without explicit consent)
 - I prepared a [mirroring script](https://gist.github.com/elieux/a71d10b1c52d5e92b2c7), so anyone can make a local mirror easily

**Comment by svnpenn** [comment]
@Alexpux @elieux any updates on this? I suggested a perhaps free option

**Comment by elieux** [comment]
A wild mirror appeared: #250 :)

**Comment by svnpenn** [comment]
https://github.com/Alexpux/MSYS2-packages/pull/357

**Comment by svnpenn** [comment]
https://github.com/Alexpux/MSYS2-packages/issues/296

**Comment by svnpenn** [comment]
https://github.com/Alexpux/MSYS2-packages/pull/250

**Comment by svnpenn** [comment]
https://github.com/Alexpux/MSYS2-packages/issues/163
