### ISSUE TITLE
scons: mingw-w64-gcc fails due to permission denied (bad environment)

### ISSUE THREAD

**Issue by elieux** [Alexpux/MSYS2-packages#235]
During an attempt to build mingw-w64-nsis, I found out scons has a problem with invoking native programs. Scons, in pursue of reproducible builds, tries to clean up the environment before running its detection (configure-like) tests, but mingw-w64-gcc need some of these environment variables to work reliably.

The problem I observed was that gcc was getting permission denied errors while trying to write to `C:\Windows`. I checked the environment that this gcc had and it was very small (including `MSYSTEM`, `PATH` and few other) and lacked `TEMP` and `TMP`, so gcc didn't know where to put its temporary files.

The `win32.py` platform initializer knows this and passes some vars through to the build environment, see https://bitbucket.org/scons/scons/src/d83ec49e287da9d6cfa22d968ebc24ae3ad8882d/src/engine/SCons/Platform/win32.py?at=default#cl-373. I'd say that our `msys.py` platform script also needs this, but maybe I'm wrong -- is there a better way of compiling with mingw-w64 from MSYS2 using scons?

**Comment by Alexpux** [comment]
Look into mingw-w64-mesa package.
I don't have issues with scons building it.
Maybe your issue is poor scons scripts for NSIS

**Comment by elieux** [comment]
Minimalistic example `SConstruct`:
```
EnsureSConsVersion(1,2)
defenv = Environment()
Export('defenv')
conf = defenv.Configure()
if not conf.CheckLibWithHeader('z', 'zlib.h', 'c'):
	print 'zlib is missing!'
	Exit(1)
conf.Finish()
```
Produces:
```
$ scons
scons: Reading SConscript files ...
Checking for C library z... no
zlib is missing!
```
`config.log`:
```
file /w/trash/eee/SConstruct,line 7:
	Configure(confdir = .sconf_temp)
scons: Configure: Checking for C library z... 
.sconf_temp/conftest_0.c <-
  |
  |
  |#include "zlib.h"
  |
  |int
  |main() {
  |  
  |return 0;
  |}
  |
gcc -o .sconf_temp/conftest_0.o -c .sconf_temp/conftest_0.c

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Cannot create temporary file in C:\Windows\: Permission denied
scons: Configure: no
```

**Comment by elieux** [comment]
As for mesa, its `SConstruct` has lines like `ENV = os.environ` that explain why it doesn't suffer from this issue.

**Comment by elieux** [comment]
Here is a patch that works for me: https://gist.github.com/elieux/fd63e62fda6a05778004
