### ISSUE TITLE
Add python3 counterpart of colorama

### ISSUE THREAD

**Issue by felixonmars** [Alexpux/MSYS2-packages#245]
@mingwandroid
Would you consider to use the split python{,2}-colorama PKGBUILD I maintain in Arch Linux [community]?

BTW: There is a 0.3.3 bump :)

**Comment by mingwandroid** [comment]
I'll take a look at it but I'm very busy with work for the next few weeks so may not get a chance until after that.

**Comment by felixonmars** [comment]
Thanks! Not in a hurry :)

**Comment by lazka** [comment]
This was fixed in b3c58d885551477ced96 it seems
