### ISSUE TITLE
mintty: Pressing Up while a program is running moves the cursor up

### ISSUE THREAD

**Issue by orgads** [Alexpux/MSYS2-packages#246]
Then the output of the running program overwrites previous lines.

On Linux bash, pressing Up writes ^[[A, leaving the cursor on the same line.

**Comment by elieux** [comment]
This should be reported to mintty/mintty instead. (I couldn't find any previous report, which is weird.)

**Comment by orgads** [comment]
Done: https://github.com/mintty/mintty/issues/630

Thanks.

**Comment by elieux** [comment]
Wow, such dedication. :) Thanks. I will follow the ticket over at mintty's tracker.
