### ISSUE TITLE
Pressing Tab with Shift down doesn't trigger completion

### ISSUE THREAD

**Issue by orgads** [Alexpux/MSYS2-packages#247]
With MSYS1 it is possible to complete using Tab with Shift down. This is useful for example when typing an uppercase directory name and completing it without having to release Shift (e.g. /d/Some/LONG_P<tab>)

**Comment by elieux** [comment]
Add this to your `~/.inputrc` and restart your shell:
```
"\e[Z": menu-complete
```
Does it help?

**Comment by orgads** [comment]
It works. Thanks!

I prefer complete over menu-complete :)

**Comment by elieux** [comment]
Cool.
