### ISSUE TITLE
Package request:  libportmidi

### ISSUE THREAD

**Issue by j3ffhubb** [Alexpux/MSYS2-packages#252]
Hello,

I'd like to request that [Portmidi](http://sourceforge.net/projects/portmedia/?source=navbar) (cross-platform C library for interfacing with MIDI hardware) be added to the MSYS2 repositories.  There is an optional bundled GUI application that has a Java dependency, IMHO that component could be omitted and just package the libportmidi dll and headers.

Thanks

**Comment by Alexpux** [comment]
I think it need to be added into MINGW-PACKAGES instead.

**Comment by j3ffhubb** [comment]
Oops, sorry, I'll close the 2 issues I just opened and re-open them in MINGW-PACKAGES.  Thanks.

**Comment by j3ffhubb** [comment]
A new issue had been opened [here](https://github.com/Alexpux/MINGW-packages/issues/638)
