### ISSUE TITLE
Latest msys2-runtime causes error messages on login and tab completion

### ISSUE THREAD

**Issue by lf-** [Alexpux/MSYS2-packages#258]
This first occurred for me when I upgraded msys2-runtime to 2.1.0.16359.acadff9-1. It was fixed by downgrading to 2.1.0.16305.2579661-2.

A small sampling of them is as follows:
      3 [main] bash 164 shared_info::initialize: size of shared memory region changed from 39824 to 28048
      3 [main] bash 10060 shared_info::initialize: size of shared memory region changed from 39824 to 28048
      3 [main] chmod 8812 shared_info::initialize: size of shared memory region changed from 39824 to 28048
      3 [main] bash 6068 shared_info::initialize: size of shared memory region changed from 39824 to 28048
      3 [main] chmod 9884 shared_info::initialize: size of shared memory region changed from 39824 to 28048
      3 [main] bash 8480 shared_info::initialize: size of shared memory region changed from 39824 to 28048
      3 [main] test 5792 shared_info::initialize: size of shared memory region changed from 39824 to 28048
      3 [main] bash 7728 shared_info::initialize: size of shared memory region changed from 39824 to 28048
      3 [main] test 3528 shared_info::initialize: size of shared memory region changed from 39824 to 28048
      3 [main] bash 8424 shared_info::initialize: size of shared memory region changed from 39824 to 28048

**Comment by elieux** [comment]
Hi. Did you follow our [upgrading steps](https://sourceforge.net/p/msys2/wiki/MSYS2%20installation)? Did you see any warnings during the upgrade? Can you check if you're running any [potentially dodgy application](https://cygwin.com/faq/faq.html#faq.using.bloda) that could interfere with the runtime?

**Comment by lf-** [comment]
After trying those upgrading steps, it still produces those error messages.

Is the "Windows Defender" entry referring to the Windows 8 one or the Windows 7 one? The Windows 8 version is a rebranded Microsoft Security Essentials. I tried disabling it, no dice.

**Comment by jhasse** [comment]
I'm having the same problem. Is there a workaround?

**Comment by lf-** [comment]
pacman -U /var/cache/pacman/msys2-runtime-whatever.pkg.tar.xz

Change your pacman configuration to ignore that package to prevent it from being updated again.

**Comment by mingwandroid** [comment]
> Change your pacman configuration to ignore that package to prevent it from being updated again.
Don't follow this advise please.

Instead read https://sourceforge.net/p/msys2/wiki/MSYS2%20installation

**Comment by lf-** [comment]
What? It was still broken when I followed that to update it. Therefore I'm suggesting that there's a bug introduced by that version.

**Comment by jhasse** [comment]
@mingwandroid We aren't stupid. I've also followed the instructions exactly.

This is what I did:

``` bash
pacman -Sy
pacman --needed -S bash pacman pacman-mirrors msys2-runtime
# restart, not using 32 bit version, so no autorebase.bat
pacman -Su
```

**Comment by mingwandroid** [comment]
@jhasse  Why are you getting defensive? I never said you were stupid. However the advise given by @lf is dangerous so it's important that it is identified as such. Telling pacman to hold specific packages at a certain version is the correct way to use MSYS2. It's a horrible hack that's going to come back to haunt anyone who does it.

From the information given, I think there is still a bash.exe process or some other msys2 processes running on the system. Can you try shutting down? Or investigating whether you have msys2 processes running via Process Hacker 2 please?

**Comment by jhasse** [comment]
Sorry, it just feels like MSYS 2 breaks at EVERY update. And every time I ask for help someone tells me to read paragraph III carefully :D

I can't reboot this computer atm. I will try Process Hacker 2, thanks :)

**Comment by mingwandroid** [comment]
@jhasse No problem. And we are aware that when pacman updates msys2-runtime and/or bash the user experience is not good.

**Comment by jhasse** [comment]
Found the problem! ssh-agent.exe was still running. Killing it and restarting MSYS fixed this. Thanks for your help @mingwandroid.

Can this be done automatically? Maybe an update.bat which runs all the necessary steps?

**Comment by mingwandroid** [comment]
Yeah, you could use `taskkill` for this.

**Comment by mingwandroid** [comment]
.. which comes with Windows.

**Comment by lf-** [comment]
Definitely a PEBCAK. Closing.

**Comment by lf-** [comment]
Hi! I am back 5 years later because this happened to me again (as a very different person). You can quickly deal with this issue by the following PowerShell oneliner that kills every process whose executable is under your msys2 installation:

```powershell
PS> Get-Process | Where-Object {$_.path -like 'C:\msys64*'} | Stop-Process
```

where `C:\msys64` is replaced with the path to your msys2 installation. If you want to see what it will kill, omit the last `Stop-Process` pipeline step.

I hope this is useful :)

**Comment by lovetox** [comment]
thanks @lf- wasted a few hours until i found your comment

**Comment by texasbruce** [comment]
> 
> 
> Hi! I am back 5 years later because this happened to me again (as a very different person). You can quickly deal with this issue by the following PowerShell oneliner that kills every process whose executable is under your msys2 installation:
> 
> ```powershell
> PS> Get-Process | Where-Object {$_.path -like 'C:\msys64*'} | Stop-Process
> ```
> 
> where `C:\msys64` is replaced with the path to your msys2 installation. If you want to see what it will kill, omit the last `Stop-Process` pipeline step.
> 
> I hope this is useful :)

Thanks it worked. For anyone reading, make sure to replace msys path to your own installation path, or i just used `*\msys64*`.

msys2 update user experience is one of the worst I've ever had...

**Comment by thiendangnn63** [comment]
@If- sorry if this is a dumb question but I am super new to PowerShell and I don't know what you meant by replacing where with the path to my msys2 installation. Hope that you can answer this even though it has been more than 2 years since you posted, I would appreciate it very much, thank you in advance.

**Comment by thiendangnn63** [comment]
> Hi! I am back 5 years later because this happened to me again (as a very different person). You can quickly deal with this issue by the following PowerShell oneliner that kills every process whose executable is under your msys2 installation:
> 
> ```powershell
> PS> Get-Process | Where-Object {$_.path -like 'C:\msys64*'} | Stop-Process
> ```
> 
> where `C:\msys64` is replaced with the path to your msys2 installation. If you want to see what it will kill, omit the last `Stop-Process` pipeline step.
> 
> I hope this is useful :)

Sorry if this is a dumb question but I am super new to PowerShell and I don't know what you meant by replacing where with the path to my msys2 installation. I hope that you can answer this even though it has been more than 2 years since you posted, I would appreciate it very much, thank you in advance. @lf-

**Comment by mathanprasannakumar** [comment]
> > Hi! I am back 5 years later because this happened to me again (as a very different person). You can quickly deal with this issue by the following PowerShell oneliner that kills every process whose executable is under your msys2 installation:
> > ```powershell
> > PS> Get-Process | Where-Object {$_.path -like 'C:\msys64*'} | Stop-Process
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > where `C:\msys64` is replaced with the path to your msys2 installation. If you want to see what it will kill, omit the last `Stop-Process` pipeline step.
> > I hope this is useful :)
> 
> Sorry if this is a dumb question but I am super new to PowerShell and I don't know what you meant by replacing where with the path to my msys2 installation. I hope that you can answer this even though it has been more than 2 years since you posted, I would appreciate it very much, thank you in advance.

Have you find any solution for the above issue ?

**Comment by Biswa96** [comment]
@mathanprasannakumar What is your issue?
