### ISSUE TITLE
Uname -p returns "unknown"

### ISSUE THREAD

**Issue by gvcgael** [Alexpux/MSYS2-packages#268]
Hello,

I'm running latest MSYS2 version and packages.

When using "uname -p", I get "unknown", thus, "./configure" of the library "Coin3D 2.5.0" returns an error because it canno't get the processor running.

**Comment by Alexpux** [comment]
This is how I build coin3d:
https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-coin3d-hg/PKGBUILD#L43

You need specify --build, --host and --target.

**Comment by gvcgael** [comment]
Perfect. Thanks.

I still wonder why does uname -p returns a wrong value :)
