### ISSUE TITLE
Compatibility between mingw libs and msys libs

### ISSUE THREAD

**Issue by gvcgael** [Alexpux/MSYS2-packages#270]
Hi

I'm trying to build QccPack.

It imports sys/_types.h but also crtdefs.h.

In types.h, there is this line (122) : 
```cpp
#ifndef __time_t_defined
typedef _TIME_T_ time_t;
#define __time_t_defined
#endif
```

In crtdefs.h, there is this line (133)

```cpp
#ifndef __TIME_T_DEFINED
#define __TIME_T_DEFINED
#ifdef _USE_32BIT_TIME_T
typedef __time32_t time_t;
#else
typedef __time64_t time_t;
#endif
#endif
```

This cause a types conflict because time_t is defined twice.

**Comment by Alexpux** [comment]
mingw-w64 header ````sys/types.h```` have:
````
#ifndef _TIME_T_DEFINED
#define _TIME_T_DEFINED
#ifdef _USE_32BIT_TIME_T
typedef __time32_t time_t;
#else
typedef __time64_t time_t;
#endif
#endif
````
So maybe you mix mingw-w64 and msys headers?

**Comment by elieux** [comment]
I assume they meant MSYS2 `sys/types.h` and `w32api/crtdefs.h`.

**Comment by Alexpux** [comment]
then need to see where ````crtdefs.h```` is included

**Comment by gvcgael** [comment]
Ok I found the issue. The types.h used was from /usr/include whereas crtdefs was the one included in /mingw64/x86_64-w64-mingw32/include/. I should use types.h from /mingw64/x86_64-w64-mingw32/include/

I need both path to be used, so I include the two paths in this order : 
 - /mingw64/x86_64-w64-mingw32/include/
 - /usr/include/

But it doesnt seems to fix the problem, types.h from /usr/include is still used.
Any idea ?

**Comment by Alexpux** [comment]
Show how you build this package.

**Comment by gvcgael** [comment]
In which case should I use which path ? 

I suppose it depends if i use gcc or mingw-gcc ? What are the differences between those two ?

**Comment by Alexpux** [comment]
All stuff under /usr is MSYS2 programs that builded with msys-gcc.
msys-gcc is like cygwin-gcc, so headers under /usr/include is cygwin headers and you **MUST NOT*** use them with mingw-gcc.

**Comment by gvcgael** [comment]
Thanks for your fast answers,
Are libraries built with msys-gcc compatible with programs build with mingw-gcc ?

**Comment by Alexpux** [comment]
No, you can't link with msys-builded libraries using mingw gcc.

**Comment by Alexpux** [comment]
Read our wiki: https://sourceforge.net/p/msys2/wiki/Home/

**Comment by gvcgael** [comment]
Ok, thanks. I understand better how MSYS2 is organized.

So I need to be able to build QccPack using Mingw since i'll use it in a Qt application (which is built using mingw). Thanks, I guess thie issue can be closed, while the other one ( https://github.com/Alexpux/MSYS2-packages/issues/269 ) should be reopened.

**Comment by gvcgael** [comment]
One question. 

What is the difference, in MSYS2, between mingw32-make and make ? Can I build for mingw libs using make ? Should I favor mingw32-make ? In which scenario should I avoid using make ?

**Comment by Alexpux** [comment]
We always prefer to use ````make```` under MSYS2  instead ````mingw32-make```` so you can always use it.
````mingw32-make```` is make builded with mingw-w64 gcc, while ````make```` builded with msys gcc.

**Comment by gvcgael** [comment]
So both make will generate windows-native executable if I specify the correct compiler, mingw-w64 ?

**Comment by Alexpux** [comment]
Yes. But with auto tools projects you need **ALWAYS** use make.
