### ISSUE TITLE
crosstool-NG update request

### ISSUE THREAD

**Issue by OTLabs** [Alexpux/MSYS2-packages#277]
MSYS2 offers binary package for crosstool-NG version 1.19.

Same time in MSYS2-packages there is package for version 1.20.

The crosstool-NG website now offers version 1.21.

Hope you can generate new binary for version 1.20 and offer it via pacman.

Hope someone can update MSYS2-packages to include latest version 1.21 and generate corresponding binary package.

**Comment by martell** [comment]
@OTLabs I will update the package and patches to 1.21 when I get a chance tomorrow :)
You might be waiting awhile for the package after that though because @Alexpux is in the middle of a gcc 5.1 mass rebuild

**Comment by OTLabs** [comment]
Thank you for this update @martell !

**Comment by martell** [comment]
Leave it open until I update as a reminder :)
ping me also if I don't do it by the end of the weekend

**Comment by OTLabs** [comment]
Sorry, pressed wrong button.

Sure, will ping you, thanks!

**Comment by OTLabs** [comment]
Ping! :-)

**Comment by martell** [comment]
done :)

You will have to wait for alexey to update the packages on the repo however

**Comment by Alexpux** [comment]
@martell, it not builded. Get linking errors:
````
  LD     'nconf'
zconf.tab.o:zconf.tab.c:(.text+0x163e): undefined reference to `libintl_gettext'
zconf.tab.o:zconf.tab.c:(.text+0x476f): undefined reference to `libintl_gettext'
zconf.tab.o:zconf.tab.c:(.text+0x563b): undefined reference to `libintl_gettext'
zconf.tab.o:zconf.tab.c:(.text+0x580c): undefined reference to `libintl_gettext'
zconf.tab.o:zconf.tab.c:(.text+0xc5fc): undefined reference to `libintl_gettext'
zconf.tab.o:zconf.tab.c:(.text+0xc60a): more undefined references to `libintl_gettext' follow
mconf.o:mconf.c:(.text+0x1342): undefined reference to `libintl_setlocale'
mconf.o:mconf.c:(.text+0x1356): undefined reference to `libintl_bindtextdomain'
mconf.o:mconf.c:(.text+0x1362): undefined reference to `libintl_textdomain'
mconf.o:mconf.c:(.text+0x1494): undefined reference to `libintl_gettext'
mconf.o:mconf.c:(.text+0x1506): undefined reference to `libintl_gettext'
mconf.o:mconf.c:(.text+0x1531): undefined reference to `libintl_gettext'
collect2: error: ld returned 1 exit status
Makefile:100: recipe for target 'mconf' failed
make[2]: *** [mconf] Error 1
make[2]: *** Waiting for unfinished jobs....
zconf.tab.o:zconf.tab.c:(.text+0x163e): undefined reference to `libintl_gettext'
zconf.tab.o:zconf.tab.c:(.text+0x476f): undefined reference to `libintl_gettext'
zconf.tab.o:zconf.tab.c:(.text+0x563b): undefined reference to `libintl_gettext'
zconf.tab.o:zconf.tab.c:(.text+0x580c): undefined reference to `libintl_gettext'
zconf.tab.o:zconf.tab.c:(.text+0xc5fc): undefined reference to `libintl_gettext'
zconf.tab.o:zconf.tab.c:(.text+0xc60a): more undefined references to `libintl_gettext' follow
conf.o:conf.c:(.text+0xe51): undefined reference to `libintl_setlocale'
conf.o:conf.c:(.text+0xe65): undefined reference to `libintl_bindtextdomain'
conf.o:conf.c:(.text+0xe71): undefined reference to `libintl_textdomain'
conf.o:conf.c:(.text+0xf10): undefined reference to `libintl_gettext'
conf.o:conf.c:(.text+0xf8e): undefined reference to `libintl_gettext'
conf.o:conf.c:(.text+0x100d): undefined reference to `libintl_gettext'
conf.o:conf.c:(.text+0x1087): undefined reference to `libintl_gettext'
conf.o:conf.c:(.text+0x1213): undefined reference to `libintl_gettext'
conf.o:conf.c:(.text+0x1374): more undefined references to `libintl_gettext' follow
collect2: error: ld returned 1 exit status
Makefile:108: recipe for target 'conf' failed
make[2]: *** [conf] Error 1
Makefile:166: recipe for target 'build-lib-kconfig' failed
make[1]: *** [build-lib-kconfig] Error 2
Makefile:126: recipe for target 'build' failed
make: *** [build] Error 2
````

**Comment by martell** [comment]
@Alexpux I don't get those link errors
I'll jump on IRC and we try to fix this

**Comment by martell** [comment]
@OTLabs alexey as narrowed this issue down to having gettext-devel installed.
You can built the PKGBUILD yourself until such a time it lands in the repo :)

**Comment by OTLabs** [comment]
@martell and @Alexpux - thank you!

May I suggest to add gettext-devel in dependencies in PKGBUILD?

**Comment by Alexpux** [comment]
crosstools-ng currently not building with gettext installed. Wait while it will be fixed.

**Comment by Sukumi** [comment]
Any idea when u plan to fix that issue?

**Comment by Sukumi** [comment]
At least this patch applied solved the build problem
(Addapted from a CYGWIN patch: https://sourceware.org/ml/crossgcc/2012-05/msg00012.html)
  #############################################################

--- crosstool-ng-1.21.0/kconfig/Makefile	2015-09-03 09:45:51.840310400 +0200
+++ crosstool-ng-1.21.0.new/kconfig/Makefile	2015-09-03 10:39:24.252670900 +0200
@@ -35,20 +35,21 @@
 conf_OBJ = $(patsubst %.c,%.o,$(conf_SRC))
 conf_DEP = $(patsubst %.o,%.dep,$(conf_OBJ))
 $(conf_OBJ) $(conf_DEP): CFLAGS += $(INTL_CFLAGS)
+conf: LDFLAGS += -lintl

 # What's needed to build 'mconf'
 mconf_SRC = mconf.c
 mconf_OBJ = $(patsubst %.c,%.o,$(mconf_SRC))
 mconf_DEP = $(patsubst %.c,%.dep,$(mconf_SRC))
 $(mconf_OBJ) $(mconf_DEP): CFLAGS += $(NCURSES_CFLAGS) $(INTL_CFLAGS)
-mconf: LDFLAGS += $(NCURSES_LDFLAGS)
+mconf: LDFLAGS += -lintl $(NCURSES_LDFLAGS)

# What's needed to build 'nconf'
 nconf_SRC = nconf.c nconf.gui.c
 nconf_OBJ = $(patsubst %.c,%.o,$(nconf_SRC))
 nconf_DEP = $(patsubst %.c,%.dep,$(nconf_SRC))
-$(nconf_OBJ) $(nconf_DEP): CFLAGS += $(INTL_CFLAGS) -I/usr/include/ncurses
-nconf: LDFLAGS += -lmenuw -lpanelw -lncursesw
+$(nconf_OBJ) $(nconf_DEP): CFLAGS += -I/usr/include/ncurses/ $(INTL_CFLAGS)
+nconf: LDFLAGS += -lintl -lmenuw -lpanelw -lncursesw

**Comment by Alexpux** [comment]
Maybe you will create pul request for this issue instead publish patch here?

**Comment by Sukumi** [comment]
good hint...just not sure about the maintainer policy here

**Comment by OTLabs** [comment]
Running v.1.21 of crosstool-ng will generate following error:
    ct-ng build
    [ERROR]  Your file system in '/home/ogurevich/cross/bin/.build' is *not* case-sensitive!

In previouse version this message was cualified as warning and crosstool-ng was able to continue, now it is an error and crosstool-ng aborts execution.

**Comment by OTLabs** [comment]
I get following error while building crosstool-ng:

    makepkg
    ...
    ==> Validating source files with md5sums...
    crosstool-ng-1.21.0.tar.xz ... Passed
    crosstool-ng-1.21.0.tar.xz.sig ... Skipped
    0001-Modify-config-to-support-correct-Mingw64-Triplet-Nam.patch ... Passed
    0002-use-wide-versions-of-libs-for-nconf.patch ... Passed
    0003-modify-kconfig-make-lintl.patch ... Passed
    0004-kconfig-nconf-fix-compile-with-ncurses-reentrant-API.patch ... Passed
    ==> Verifying source file signatures with gpg...
    crosstool-ng-1.21.0.tar.xz ... FAILED (unknown public key CAD7C8FC35B871D1)
    ==> ERROR: One or more PGP signatures could not be verified!

**Comment by bhundven** [comment]
I know this is old, but if you want to verify the key:
```gpg --recv-keys 35B871D1```
then check the fingerprint: 
```gpg --fingerprint "Bryan Hundven"```
You should get:
```Key fingerprint = 561E D9B6 2095 88ED 23C6  8329 CAD7 C8FC 35B8 71D1```

Also now documented here: http://crosstool-ng.org/#using_a_released_version

**Comment by nistvan86** [comment]
Getting this error when trying to install crosstool-ng with latest MSYS2:

`Istvan@inagy-pc MSYS ~/MSYS2-packages/crosstool-ng
$ makepkg
==> Making package: crosstool-ng 1.21.0-1 (25 Feb 2016 20:19:36)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found crosstool-ng-1.21.0.tar.xz
  -> Found crosstool-ng-1.21.0.tar.xz.sig
  -> Found 0001-Modify-config-to-support-correct-Mingw64-Triplet-Nam.patch
  -> Found 0002-use-wide-versions-of-libs-for-nconf.patch
  -> Found 0003-modify-kconfig-make-lintl.patch
  -> Found 0004-kconfig-nconf-fix-compile-with-ncurses-reentrant-API.patch
==> Validating source files with sha256sums...
    crosstool-ng-1.21.0.tar.xz ... Passed
    crosstool-ng-1.21.0.tar.xz.sig ... Skipped
    0001-Modify-config-to-support-correct-Mingw64-Triplet-Nam.patch ... Passed
    0002-use-wide-versions-of-libs-for-nconf.patch ... Passed
    0003-modify-kconfig-make-lintl.patch ... Passed
    0004-kconfig-nconf-fix-compile-with-ncurses-reentrant-API.patch ... Passed
==> Verifying source file signatures with gpg...
    crosstool-ng-1.21.0.tar.xz ... FAILED (the public key 561ED9B6209588ED23C68329CAD7C8FC35B871D1 is not trusted)
==> ERROR: One or more PGP signatures could not be verified!
`
