### ISSUE TITLE
Update https://github.com/Alexpux/MSYS2-packages/blob/master/mintty/PKGBUILD file

### ISSUE THREAD

**Issue by paladox** [Alexpux/MSYS2-packages#278]
Hi please update https://github.com/Alexpux/MSYS2-packages/blob/master/mintty/PKGBUILD file because mintty is no longer active on google code and have moved to GitHub where they have started developing it again. new link for mintty is https://github.com/mintty/mintty

**Comment by Alexpux** [comment]
Done by https://github.com/Alexpux/MSYS2-packages/commit/dc548f4df607ffe5064986c4ee65714ecf3563ba

**Comment by paladox** [comment]
Thanks.
