### ISSUE TITLE
G_GSIZE_FORMAT defined incorrectly in glibconfig.h

### ISSUE THREAD

**Issue by conklech** [Alexpux/MSYS2-packages#279]
glib-2.0 exposes a constant, [`G_GSIZE_FORMAT`](https://developer.gnome.org/glib/stable/glib-Basic-Types.html#G-GSIZE-FORMAT:CAPS`), that is supposed to specify the platform-dependent formatting string for printing values of type `gsize` ~ `size_t`. As of `mingw64/mingw-w64-x86_64-glib2 2.44.1-1`, that constant is defined as `zu` in `/mingw64/lib/glib-2.0/include/glibconfig.h`, a generated file.

But our GCC doesn't support that:

    $ cat test.c
    #include<stdio.h>

    main()
    {
      printf ("%zu\n" , sizeof (int)); // prints "zu"
      printf ("%u\n" , sizeof (int));  // prints "4"
    }
    $ gcc test.c
    $ ./a.exe
    zu
    4

We already patch at least one other package to work around this limitation; see [this patch to libxml2](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-libxml2/0020-fix-size_t-format-specifier.all.patch). I don't know why autoconf/whatever is generating the header gets it wrong. I don't know if patching glibconfig.h directly is an appropriate resolution.

This is presumably related to #79. 

This bug breaks GTK in Haskell on Windows; see gtk2hs/gtk2hs#110.

**Comment by mingwandroid** [comment]
The problem is that you are not passing -D__USE_MINGW_ANSI_STDIO=1 to the compiler. MSYS2 packages are all built with this flag. I should add something to the wiki about that actually.

**Comment by conklech** [comment]
Yes; please document this requirement. I confess I'm a little confused. Shouldn't `pkg-config` report that as a required flag?

Would you kindly suggest how I should fix this downstream? Under what circumstances should this option *not* be set when using the MSYS2 distributed mingw64/32 packages?

**Comment by mingwandroid** [comment]
I added a note to https://sourceforge.net/p/msys2/wiki/Porting/

In general using -D__USE_MINGW_ANSI_STDIO=1 is not a requirement, but if you want to use ANSI Standard Specifiers then you need to pass it.

You need to set it in CPPFLAGS, Here's how we ensure our packages are built with this flag: https://github.com/Alexpux/MSYS2-packages/blob/master/pacman/makepkg_mingw32.conf#L50

If you want to make a new bug that the pkg config files for glib-2.0 should have this flag added then please do!

https://github.com/Alexpux/MSYS2-packages/issues/79 is concerned with our msys2 GCC toolchain, not our MinGW-w64 ones and it's not related to ANSI format specifiers. The reason for lack of C++11 is down to the fact that newlib is used by Cygwin (and thus inherited by msys2).

**Comment by conklech** [comment]
Thanks for the detailed reply; I was able to resolve the immediate problem. I'll get this addressed downstream as appropriate.

**Comment by mingwandroid** [comment]
Great. I filed a new bug https://github.com/Alexpux/MSYS2-packages/issues/280 so I don't forget. On balance, I think fixing the glibc-2.0 .pc files is the most correct approach.
