### ISSUE TITLE
glib-2.0's .pc files need -D__USE_MINGW_ANSI_STDIO=1 adding to them.

### ISSUE THREAD

**Issue by mingwandroid** [Alexpux/MSYS2-packages#280]
See: https://github.com/Alexpux/MSYS2-packages/issues/279 for the reasoning.

**Comment by conklech** [comment]
Just to summarize my reasoning from #279: glib exposes a macro, `G_GSIZE_FORMAT`, advertised as providing the platform-local format string to print variables of type `size_t`. Without `__USE_MINGW_ANSI_STDIO=1`, this is incorrect.

**Comment by mingwandroid** [comment]
Urgh, I filed this with the wrong repo. Correct URL: https://github.com/Alexpux/MINGW-packages/issues/691
