### ISSUE TITLE
mingw-64-sfml fails when makepg-mingw

### ISSUE THREAD

**Issue by roig** [Alexpux/MSYS2-packages#281]
Hello, I'm trying to use MSYS2 for the first time and I need the SFML package.

When I try to build SFML with makepg-mingw, it applies the patch ok and starts to build but then fails with this: 
patching file CMakeLists.txt
Hunk #1 succeeded at 188 (offset 24 lines).
Hunk #2 succeeded at 282 (offset 24 lines).
patching file src/SFML/CMakeLists.txt
patching file src/SFML/Audio/CMakeLists.txt
Hunk #1 succeeded at 56 with fuzz 2 (offset 25 lines).
patching file src/SFML/Graphics/CMakeLists.txt
Hunk #1 succeeded at 87 (offset -5 lines).
patching file doc/CMakeLists.txt
patching file cmake/Config.cmake
patching file cmake/Macros.cmake
==> Iniciando build()...
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/msys64/mingw64/bin/g++.exe
-- Check for working CXX compiler: C:/msys64/mingw64/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Found OpenGL: opengl32
-- Found JPEG: C:/msys64/mingw64/lib/libjpeg.dll.a
-- Found OpenAL: C:/msys64/mingw64/lib/libOpenAL32.dll.a
-- Found VORBIS: C:/msys64/mingw64/lib/libvorbis.dll.a
-- Found FLAC: C:/msys64/mingw64/lib/libFLAC.dll.a
-- Found Doxygen: C:/msys64/usr/bin/doxygen.exe (found version "1.8.10")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/msys64/home/Dani/repos/MINGW-packages/mingw-w64-sfml/src/build-x86_64-w64-mingw32
Scanning dependencies of target doc
Scanning dependencies of target sfml-main
Scanning dependencies of target sfml-system
[  1%] Building CXX object src/SFML/Main/CMakeFiles/sfml-main.dir/MainWin32.cpp.obj
Building API Documentation...[  2%] Building CXX object src/SFML/System/CMakeFiles/sfml-system.dir/Clock.cpp.obj
[  3%] Building CXX object src/SFML/System/CMakeFiles/sfml-system.dir/Err.cpp.obj
[  3%] Building CXX object src/SFML/System/CMakeFiles/sfml-system.dir/Lock.cpp.obj
error: Failed to open temporary file /C/msys64/home/Dani/repos/MINGW-packages/mingw-w64-sfml/src/SFML-2.3/C:/msys64/home/Dani/repos/MINGW-packages/mingw-w64-sfml/src/build-x86_64-w64-mingw32/share/doc/SFML/doxygen_objdb_2204.tmp
Exiting...
doc/CMakeFiles/doc.dir/build.make:57: fallo en las instrucciones para el objetivo 'doc/CMakeFiles/doc'
make[2]: *** [doc/CMakeFiles/doc] Error 1
CMakeFiles/Makefile2:1065: fallo en las instrucciones para el objetivo 'doc/CMakeFiles/doc.dir/all'
make[1]: *** [doc/CMakeFiles/doc.dir/all] Error 2
make[1]: *** Se espera a que terminen otras tareas....
[  4%] Building CXX object src/SFML/System/CMakeFiles/sfml-system.dir/Mutex.cpp.obj
[  5%] Building CXX object src/SFML/System/CMakeFiles/sfml-system.dir/Sleep.cpp.obj
[  6%] Building CXX object src/SFML/System/CMakeFiles/sfml-system.dir/String.cpp.obj
[  7%] Building CXX object src/SFML/System/CMakeFiles/sfml-system.dir/Thread.cpp.obj
[  7%] Building CXX object src/SFML/System/CMakeFiles/sfml-system.dir/ThreadLocal.cpp.obj
[  7%] Linking CXX static library ../../../lib/libsfml-main.a
[  8%] Building CXX object src/SFML/System/CMakeFiles/sfml-system.dir/Time.cpp.obj
[  9%] Building CXX object src/SFML/System/CMakeFiles/sfml-system.dir/FileInputStream.cpp.obj
[  9%] Built target sfml-main
[ 10%] Building CXX object src/SFML/System/CMakeFiles/sfml-system.dir/MemoryInputStream.cpp.obj
[ 11%] Building CXX object src/SFML/System/CMakeFiles/sfml-system.dir/Win32/ClockImpl.cpp.obj
[ 11%] Building CXX object src/SFML/System/CMakeFiles/sfml-system.dir/Win32/MutexImpl.cpp.obj
[ 12%] Building CXX object src/SFML/System/CMakeFiles/sfml-system.dir/Win32/SleepImpl.cpp.obj
[ 13%] Building CXX object src/SFML/System/CMakeFiles/sfml-system.dir/Win32/ThreadImpl.cpp.obj
[ 14%] Building CXX object src/SFML/System/CMakeFiles/sfml-system.dir/Win32/ThreadLocalImpl.cpp.obj
[ 15%] Linking CXX shared library ../../../lib/sfml-system-2.dll
[ 15%] Built target sfml-system
Makefile:127: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2
==> ERROR: Se produjo un fallo en build().
    Cancelando...

Anyone having this error? Thank you :+1:

**Comment by Alexpux** [comment]
Change PKGBUILD and replace in makedepends "doxygen" with "${MINGW_PACKAGE_PREFIX}-doxygen"

**Comment by Alexpux** [comment]
Pushed fix: https://github.com/Alexpux/MINGW-packages/commit/fac4a50b7f2559cb9e0efba75af0bf05e4a4f069

Akso don't create issues for ming-packages in msgs-packages repo.
