### ISSUE TITLE
How to start msys2-shell with fish-shell

### ISSUE THREAD

**Issue by amosbird** [Alexpux/MSYS2-packages#283]
I've tested fish 2.2.0. It works on msys2. How can I make it default shell?

**Comment by Alexpux** [comment]
You need fix ````bat```` files: msys2_shell, mingw32_shell and mingw64_shell to invoke fish instead bash. Also replace /usr/bin/sh.exe with copy of fish.exe

**Comment by eugenesvk** [comment]
@amosbird
Would you please share your config PKGBUILD etc files as I can't seem to be able to build it. Thank you

**Comment by eugenesvk** [comment]
By the way, below are some config files that allow fish to work as login interactive shell (mainly just rewritten the `/etc/profile` file). 
1. [Function to check MSys2 presence](https://github.com/eugenesvk/Settings-Fish/blob/master/Functions/check_system.fish) (I need it to use the same configs on other systems)
2. **fish.config** first command that would set required environment variables for fish to work properly if fish is run as a login shell
```
set -l system (check_system)
if test "$system" = Win
  if status -l; source $HOME/.config/fish/profileMSys2.fish; end   # copy of /etc/profile -> fish
end
```
3. [Fish Login Profile](https://github.com/eugenesvk/Settings-Fish/blob/master/profileMSys2.fish)


Also, in respective `*_shell.bat` I've made the following adjustment

```
:startmintty
if NOT EXIST %WD%mintty.exe goto startsh
if EXIST %WD%fish.exe goto startfish
...
:startfish
::Set env var to fish socket otherwise fish bugs because can't create files in this dir on its own
set "XDG_RUNTIME_DIR=/tmp/fish.%USERNAME%/"
start %WD%mintty -i /msys2.ico /usr/bin/fish --login %*
exit
```

@Alexpux when I replaced `/usr/bin/sh.exe` it stopped working, the initial process would hang, so I left that part out.

**Comment by eugenesvk** [comment]
Resolved it myself, turned out to be a simple fix in a variable declaration [see here](https://github.com/Alexpux/MSYS2-packages/issues/204)

**Comment by josephan** [comment]
Another option is to pass `-shell fish` when starting `msys2_shell.cmd`. Here is my config for Windows Terminal:
```json
{
    "colorScheme": "One Half Dark",
    "commandline": "C:\\msys64\\msys2_shell.cmd -defterm -here -no-start -msys  -use-full-path -shell fish",
    "font": {
        "face": "JetBrains Mono NL",
        "size": 14
    },
    "guid": "{cb9a972f-54b4-42ff-bcbc-e5dd0525d2ca}",
    "hidden": false,
    "icon": "C:\\msys64\\msys2.ico",
    "name": "Fish"
}
```

**Comment by Biswa96** [comment]
@josephan Would you mind if the idea is also added in documentation here https://www.msys2.org/docs/terminals/ ?

**Comment by josephan** [comment]
@Biswa96 Of course not! Feel free!
