### ISSUE TITLE
strace.exe from msys2 32bit doesn't seem to work on 64 bit executables

### ISSUE THREAD

**Issue by adrpo** [Alexpux/MSYS2-packages#291]
Hi,

Very nice project! Thank you and good luck with it!

I wonder if there is a strace I could download and use on 64bit executables. 
Do I need to install msys2 64bit to get an strace that works on 64bit executables?

**Comment by mingwandroid** [comment]
Yes, there is no good reason for an MSYS2 user to run the 32-bit version if they have a 64-bit CPU. Can I ask what thought process led you to do that? :-)

**Comment by mingwandroid** [comment]
Probably our installer should warn that you're doing something sub-optimal ..

**Comment by Alexpux** [comment]
Also strace from msys2-runtime is designed to debug msys2 applications but not mingw or other Windows one.

**Comment by adrpo** [comment]
Thanks for the quick responses. 
I thought I could use strace to debug an issue with a Qt5 application that just exits. 
I tried gdb but it doesn't work as there seems to be some stack corruption :)
I'll give Process Monitor a try.

I want to use msys2 as a replacement for msys to build some of our software (OpenModelica).
I chose to use msys2 32bit as it would work on older 32bit systems and msys2 64bit would not.
I  think that companies still have 32 bit systems that they use even if most of the world moved to 64 bit computers :)

**Comment by mingwandroid** [comment]
That's still not a reason to use 32-bit MSYS2, if you personally are sat in-front of a 64-bit computer, then you should use 64-bit MSYS2. That can be used to create both 32-bit and 64-bit native Windows software with no problem.

**Comment by adrpo** [comment]
True. And in general most developers are using 64 bit systems. I'll think more about it :)

**Comment by adrpo** [comment]
How is the proffered way of asking questions about the Msys2 project?
Via this issue tracker or via the SF mailing list: msys2-users@lists.sourceforge.net?
I want to ask some more questions and I don't want to annoy your workflow :)

**Comment by Alexpux** [comment]
Issue tracker is only for bugs/requests.
You can ask anything about MSYS2 via ML or our IRC channel #msys2 on oftc.net

**Comment by adrpo** [comment]
Thanks.

**Comment by adrpo** [comment]
Just if anybody is ever running into this problem: I had the GCC flag -enable-auto-import that is needed by an older version of GCC (namely 4.4.0) which made the generated executables do nothing but exit with an error code. GDB didn't help as the program didn't even reach main. After removing the flag everything started to work fine.
