### ISSUE TITLE
install gcc on msys2

### ISSUE THREAD

**Issue by Arnold1** [Alexpux/MSYS2-packages#293]
Hi,

whats the right package to install gcc on msys2?
```
pacman -S gcc
pacman -S mingw-w64-x86_64-gcc
```

I use: msys2-x86_64-20150512.exe

Thanks,
A

**Comment by mingwandroid** [comment]
Which GCC do you want? MSYS2 GCC or MinGW-w64 GCC?

Please read the wiki: sourceforge.net/p/msys2/wiki/Home/

**Comment by Arnold1** [comment]
i tried to install http://sourceforge.net/projects/mingw-w64/files/latest/download
and get the error: Cannot download repository.txt [0]

**Comment by mingwandroid** [comment]
Why did you try to do that? If you want MSYS2's MinGW-w64 x86_64 GCC then you should install the ```mingw-w64-x86_64-toolchain``` package group via:

```pacman -S mingw-w64-x86_64-toolchain```

**Comment by Arnold1** [comment]
ok. where is mingw-w64-x86_64-gcc installed to? which mingw-w64-x86_64-gcc or which gcc doesnt find gcc...

**Comment by Alexpux** [comment]
PATH=/mingw64/bin:$PATH which gcc

**Comment by mingwandroid** [comment]
Again, please read the Wiki. Here is a clickable link: https://sourceforge.net/p/msys2/wiki/Home/

You should use mingw64_shell.bat as that sets the correct environment for using our MinGW-w64 x86_64 toolchain.

**Comment by Arnold1** [comment]
ok. i didnt see that minw64_shell.bat was installed...

**Comment by mingwandroid** [comment]
Please read the wiki. Everything is explained there.
