### ISSUE TITLE
New Installation times-out with msys.db not fetchable from Sourceforge

### ISSUE THREAD

**Issue by eliezedeck** [Alexpux/MSYS2-packages#302]
I'm not sure where to report this, but I followed the guide here: https://msys2.github.io/
On the step #5 in that guide, here is the error that I'm getting:

    error: failed retrieving file 'msys.db' from downloads.sourceforge.net : Connection timed out after 10305 milliseconds
    error: failed to update msys (download library error)
    warning: bash-4.3.033-2 is up to date -- skipping
    warning: pacman-4.2.1.6142.e7b8173-1 is up to date -- skipping
    warning: pacman-mirrors-20141223-1 is up to date -- skipping
    warning: msys2-runtime-2.1.0.16359.acadff9-1 is up to date -- skipping
     there is nothing to do

Here is a screenshot.
![msys2 install msys db failure](https://cloud.githubusercontent.com/assets/7553916/8941758/33ec1872-357a-11e5-8218-7b2e1094856c.jpg)

This error persists no matter how many times I tried it. I even tried on a Virtual Machine with a fresh install, and another different machine. Same thing all the time.

**Comment by Alexpux** [comment]
Follow instructions  https://github.com/Alexpux/MINGW-packages/issues/702 to get new mirrors

**Comment by eliezedeck** [comment]
Thanks @Alexpux, it works great now.

**Comment by karippery** [comment]
error failed retrieving files
![msys2](https://user-images.githubusercontent.com/33422429/54342135-f80b0f80-463b-11e9-9872-b7518de3945d.PNG)
could you give me solution for this problem?

**Comment by karippery** [comment]
any way thank you 
i find the solution for this problem .  it was proxy settings. i was update ect/profile
