### ISSUE TITLE
address space needed by 'msys-z.dll' is already occupied

### ISSUE THREAD

**Issue by chaffra** [Alexpux/MSYS2-packages#303]
I noticed this error in the configure  phase for several projects I am building i.e. numpy and petsc. I am using the MSYS2 environement with the MSYS2 gcc and python2. Any idea what I am missing? The text below shows I was able to compile a simple test program in the numpy configure phase, but it fails to execute _configtest.exe. Should I be linking the msys-2.0.dll to create the exe?

C compiler: gcc -fno-strict-aliasing -march=i686 -mtune=generic -O2 -pipe -DNDEBUG -DNDEBUG -march=i686 -mtune=generic -O2 -pipe -DNDEBUG

compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/include -I/usr/include/python2.7 -c'
gcc: _configtest.c
gcc _configtest.o -o _configtest.exe
_configtest.exe
     12 [main] python2 4596 child_info_fork::abort: address space needed by 'msys-z.dll' (0x250000) is already occupied:collision:
error: [Errno 11] Resource temporarily unavailable
Failure with exit status: 1
Exit message: There was a problem in build setup for numpy-1.9.2.

**Comment by Alexpux** [comment]
Seems you use 32-bit MSYS2. You need close MSYS2 shell and run ***autorebase.bat***

**Comment by chaffra** [comment]
Thanks, that works!
