### ISSUE TITLE
cannot refresh msys.db from sourceforge

### ISSUE THREAD

**Issue by Eviv** [Alexpux/MSYS2-packages#307]
Dear all,

I reinstalled msys2 yesterday both under W10 andd W7 and though I can use pacman to install packages such as gcc make, etc..., I have a problem with pacman -Syu: I cannot download msys.db from sourceforge (mingw32 and mingw64 OK).
Please find below the debug output.

 pacman -Syuv --debug
debug: pacman v4.2.1-257-g3356d-dirty - libalpm v9.0.1
debug: config: attempting to read file /etc/pacman.conf
debug: config: new section 'options'
debug: config: HoldPkg: pacman
debug: config: arch: x86_64
debug: config: SigLevel: Required
debug: config: SigLevel: DatabaseOptional
debug: config: LocalFileSigLevel: Optional
debug: config: new section 'mingw32'
debug: config file /etc/pacman.conf, line 73: including /etc/pacman.d/mirrorlist.mingw32
debug: config: new section 'mingw64'
debug: config file /etc/pacman.conf, line 76: including /etc/pacman.d/mirrorlist.mingw64
debug: config: new section 'msys'
debug: config file /etc/pacman.conf, line 79: including /etc/pacman.d/mirrorlist.msys
debug: config: finished parsing /etc/pacman.conf
debug: setup_libalpm called
debug: option 'logfile' = /var/log/pacman.log
debug: option 'gpgdir' = /etc/pacman.d/gnupg/
debug: option 'cachedir' = /var/cache/pacman/pkg/
debug: registering sync database 'mingw32'
debug: database path for tree mingw32 set to /var/lib/pacman/sync/mingw32.db
debug: GPGME version: 1.5.4
debug: GPGME engine info: file=/usr/bin/gpg, home=/etc/pacman.d/gnupg/
debug: checking signature for /var/lib/pacman/sync/mingw32.db
debug: 1 signatures returned
debug: fingerprint: AD351C50AE085775EB59333B5F92EFC1A47D45A1
debug: summary: valid
debug: summary: green
debug: status: Success
debug: timestamp: 1436268517
debug: exp_timestamp: 0
debug: validity: full; reason: Success
debug: key: AD351C50AE085775EB59333B5F92EFC1A47D45A1, Alexey Pavlov (Alexpux) <alexpux@gmail.com>, owner_trust unknown, disabled 0
debug: signature is valid
debug: signature is fully trusted
debug: setting usage of 15 for mingw32 repository
debug: adding new server URL to database 'mingw32': http://downloads.sourceforge.net/project/msys2/REPOS/MINGW/i686
debug: registering sync database 'mingw64'
debug: database path for tree mingw64 set to /var/lib/pacman/sync/mingw64.db
debug: checking signature for /var/lib/pacman/sync/mingw64.db
debug: 1 signatures returned
debug: fingerprint: AD351C50AE085775EB59333B5F92EFC1A47D45A1
debug: summary: valid
debug: summary: green
debug: status: Success
debug: timestamp: 1436268449
debug: exp_timestamp: 0
debug: validity: full; reason: Success
debug: key: AD351C50AE085775EB59333B5F92EFC1A47D45A1, Alexey Pavlov (Alexpux) <alexpux@gmail.com>, owner_trust unknown, disabled 0
debug: signature is valid
debug: signature is fully trusted
debug: setting usage of 15 for mingw64 repository
debug: adding new server URL to database 'mingw64': http://downloads.sourceforge.net/project/msys2/REPOS/MINGW/x86_64
debug: registering sync database 'msys'
debug: database path for tree msys set to /var/lib/pacman/sync/msys.db
debug: checking signature for /var/lib/pacman/sync/msys.db
debug: 1 signatures returned
debug: fingerprint: AD351C50AE085775EB59333B5F92EFC1A47D45A1
debug: summary: valid
debug: summary: green
debug: status: Success
debug: timestamp: 1431416285
debug: exp_timestamp: 0
debug: validity: full; reason: Success
debug: key: AD351C50AE085775EB59333B5F92EFC1A47D45A1, Alexey Pavlov (Alexpux) <alexpux@gmail.com>, owner_trust unknown, disabled 0
debug: signature is valid
debug: signature is fully trusted
debug: setting usage of 15 for msys repository
debug: adding new server URL to database 'msys': http://downloads.sourceforge.net/project/msys2/REPOS/MSYS2/x86_64
Root      : /
Conf File : /etc/pacman.conf
DB Path   : /var/lib/pacman/
Cache Dirs: /var/cache/pacman/pkg/
Lock File : /var/lib/pacman/db.lck
Log File  : /var/log/pacman.log
GPG Dir   : /etc/pacman.d/gnupg/
Targets   : --
:: Synchronisation des bases de données de paquets...
debug: url: http://downloads.sourceforge.net/project/msys2/REPOS/MINGW/i686/mingw32.db
debug: maxsize: 26214400
debug: using time condition: 1436268517
debug: opened tempfile for download: /var/lib/pacman/sync/mingw32.db.part (wb)
debug: curl returned error 0 from transfer
debug: response code: 304
debug: file met time condition
 mingw32 est à jour
debug: url: http://downloads.sourceforge.net/project/msys2/REPOS/MINGW/x86_64/mingw64.db
debug: maxsize: 26214400
debug: using time condition: 1436268449
debug: opened tempfile for download: /var/lib/pacman/sync/mingw64.db.part (wb)
debug: curl returned error 0 from transfer
debug: response code: 304
debug: file met time condition
 mingw64 est à jour
debug: url: http://downloads.sourceforge.net/project/msys2/REPOS/MSYS2/x86_64/msys.db
debug: maxsize: 26214400
debug: using time condition: 1431416285
debug: opened tempfile for download: /var/lib/pacman/sync/msys.db.part (wb)
debug: curl returned error 28 from transfer
erreur : échec de récupération du fichier « msys.db » depuis downloads.sourceforge.net : Connection timed out after 10700 milliseconds
debug: failed to sync db: erreur de la bibliothèque de téléchargement
erreur : la mise à jour de msys a échoué (erreur de la bibliothèque de téléchargement)

**Comment by Alexpux** [comment]
Guys, how many time you will ask the same questions? Looking into current issues will help you a lot.
SourceForge ***IS DOWN***.
See issue https://github.com/Alexpux/MSYS2-packages/issues/296

**Comment by Eviv** [comment]
Dear Alexpux,

I did have a look at the titles of the messages on the current page, but nothing seemed like my problem for me, although now I remember going through #302... => I need vacations! ;)
Anyway, thanks a lot for the link, for your patience and, not the least, for your work on msys2.

(Since I have 2 systems, I tried both methods given in Mingw-packages #702: edit of /etc/pacman.d/mirrorlist.xxxx and wget http://repo.msys2.org/msys/x86_64/pacman-mirrors-20150722-1-any.pkg.tar.xz
pacman -U pacman-mirrors-20150722-1-any.pkg.tar.xz and both worked)

Many Thanks,

Eviv
