### ISSUE TITLE
dependencies to distribute msys2 package

### ISSUE THREAD

**Issue by chaffra** [Alexpux/MSYS2-packages#318]
Is it possible to distribute a package built with msys2 gcc compiler? Is the only additionnal library needed at runtime msys-2.0.dll?

**Comment by Alexpux** [comment]
Don't think that this is good idea. As MSYS2 use cygwin runtime you need to read https://www.cygwin.com/faq.html#faq.what.free. Next, why not distribute mingw version of package instead?

**Comment by chaffra** [comment]
Thank you. I wanted to, but part of my package contains a library (petsc) which seems difficult to port to mingw but now builds with msys2. But I understand the cost issues.

Thanks.
