### ISSUE TITLE
Add PHP

### ISSUE THREAD

**Issue by atrauzzi** [Alexpux/MSYS2-packages#322]
As per advice [here](http://sourceforge.net/p/msys2/tickets/183/).

Would love to see a build of PHP made available with most `.so` modules available as separate packages, similar to how Linux distros do it.

Worth noting: Don't compile-in cURL (even though it's perfectly reasonable to want to), otherwise Google App Engine users could encounter issues depending on how their `app.yaml` file is configured.

**Comment by bardware** [comment]
PHP 7 including the php-ast extension would be nice.

**Comment by mingwandroid** [comment]
Ok, but why as an MSYS2-package? I know nothing of PHP. Someone from that community would have to do the work here of maintaining it I think.

**Comment by elieux** [comment]
+1 but I don't think keeping this ticket open will help anything.

**Comment by the-liquid-metal** [comment]
Hello.

It has been 2 years now since this thread was created. I still not found any php package in msys2. is there any progress about it? why it took so long?

**Comment by the-liquid-metal** [comment]
If i am not wrong, there are already php packages in cygwin. Is it hard to replicate it on msys?

php is able to run in console mode natively. i feel something is missing when i call php on command prompt.  Somehow, the coloring output is disappears. did i forget something?

**Comment by atrauzzi** [comment]
TBH, I do suggest anyone reading consider Windows Subsystem for Linux. If you don't have Windows 10 and can't use Linux, it's worth that alone.

**Comment by mati865** [comment]
Cygwin emulates POSIX and MinGW is about creating native software (without emulation).

**Comment by muv1** [comment]
https://github.com/msys2/MSYS2-packages/pull/371
