### ISSUE TITLE
obstack.h missing from MSYS2

### ISSUE THREAD

**Issue by AaronNGray** [Alexpux/MSYS2-packages#323]
obstack.h seems to be missing from MSYS2. And is used by many GNU projects.
I would expect it to be in /usr/include but it is not present.

**Comment by elieux** [comment]
Seems like it's not part of POSIX, just some GNU extension(*). You can probably use [Gnulib to substitute `obstack.h`](https://www.gnu.org/software/gnulib/manual/html_node/obstack_002eh.html) if you need, or try to get it into [Newlib](https://sourceware.org/newlib/)/Cygwin upon which MSYS2 is built.

*) https://en.wikipedia.org/wiki/Obstack
