### ISSUE TITLE
error: gamin-devel: missing required signature

### ISSUE THREAD

**Issue by mabreedlove** [Alexpux/MSYS2-packages#330]
Issue with gamin-devel that prevents installation.  This is only for gamin-devel as the gamin package works fine.  This is low-priority as I have no direct need for this package but it prevents installing the development package group easily.

$ pacman -S gamin-devel
resolving dependencies...
looking for conflicting packages...

Packages (1) gamin-devel-0.1.10-2

Total Installed Size:  0.03 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                           [#######################################] 100%
(1/1) checking package integrity                                         [#######################################] 100%
error: gamin-devel: missing required signature
error: failed to commit transaction (package missing required signature)
Errors occurred, no packages were upgraded.

**Comment by elieux** [comment]
Is fixed.
