### ISSUE TITLE
old versions.

### ISSUE THREAD

**Issue by dcrystalj** [Alexpux/MSYS2-packages#331]
Is there any way to install old versions of packages. For example I want to install tmux 1.9 because of mouse support ?

**Comment by mingwandroid** [comment]
If you have it in `/var/cache/pacman/pkg` and there hasn't been any Binary Incompatibility ( https://en.wikipedia.org/wiki/Binary_code_compatibility ) introduced by updates to any packages that it depends on then you can use `pacman -U <filepath>`

**Comment by mingwandroid** [comment]
This isn't a bug btw.

**Comment by maoueh** [comment]
`tmux` mouse options are now all handled by the single `set -g mouse on` on `tmux` 2.x.
