### ISSUE TITLE
bash ignores $TMP and $TEMP

### ISSUE THREAD

**Issue by jeroenooms** [Alexpux/MSYS2-packages#334]
I'm trying to build a version of `sh` that I can use outside msys2. However the standard msys2 build of bash seems to hardcode the temporary dir to `/tmp`. Is there any way I can change that so that it works in plain windows?

![screenshot](http://i.imgur.com/hxTtnOf.png)

**Comment by elieux** [comment]
The `usertemp` mount type is now available in Cygwin/MSYS2. You could built your own runtime version that has mounts `/tmp` using `usertemp` by default, or just provide an `/etc/fstab` with the correct definition.
