### ISSUE TITLE
Can not find `sponge`

### ISSUE THREAD

**Issue by tpimh** [Alexpux/MSYS2-packages#339]
Which package contains `sponge` utility? In Arch it's `moreutils`.

The path should probably be `/usr/bin/sponge`.

**Comment by DavidEGrayson** [comment]
I can't find it either.  Maybe you could contribute a PKGBUILD script for moreutils if you want it to be added to MSYS2.

**Comment by ErichDonGubler** [comment]
I actually contributed it somewhat recently, and it's available now: https://github.com/Alexpux/MSYS2-packages/tree/master/moreutils
