### ISSUE TITLE
Installing GTK+

### ISSUE THREAD

**Issue by ashok1123** [Alexpux/MSYS2-packages#351]
Hi,
I am trying to install GTK+ and as described I downloaded MSYS2 and it failed to update the packages. I am not very familiar with installation from DOS. I want to install in a PC where internet connection is not available. I want to download the packages from a PC with internet connection and transfer the files. Can you please tell me how to do it?

**Comment by omac777** [comment]
Take a look at this:
http://gtkmm-installation.blogspot.ca/2015/01/gtkmm-installation-on-windows-step-by.html
It definitely works.  The author of this blog is meticulous and has troubleshooting for any error you might get along the process.  Do your best to use the msys2 mingw64 shell.  There are two shells w32 and w64.  The other thing I recommend for having less issues is to run the mingw64 shell as administrator.

https://github.com/omac777/gtksnowloadcount/blob/master/Makefile.msys2.mingw64.x86_64
https://github.com/omac777/gtksnowloadcount/

**Comment by ashok1123** [comment]
The links were awesome, I have not yet installed, but update you if I face any issues or if successful.
