### ISSUE TITLE
npm doesn't work after updating winpty-git

### ISSUE THREAD

**Issue by poxu** [Alexpux/MSYS2-packages#360]
winpty exact version is winpty-git-1.1.1.184.db12b07

Steps to reproduce
------------------------
1. Download msys2-base-x86_64-20150916.tar.xz
2. Unpack it to d:/soft/msys2
3. Run mingw64-shell.bat
4. Restart
5. pacman -S mingw64/mingw-w64-x86_64-nodejs
6. npm (output should be ok)
7. update-core
8. Restart
9. pacman -S msys/winpty-git
10. npm

Expected result
-------------------
npm help output as usual

Actual result
----------------
````
module.js:340
    throw err;
          ^
Error: Cannot find module 'D:\mingw64\lib\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
````
Additional info
-----------------
npm looks for npm-cli.js in   
````
"$basedir/node" "$basedir/../lib/node_modules/npm/bin/npm-cli.js" "$@"
````
Basedir is /mingw64/bin, so the problem must be evaluating relative path

Downgrading to winpty-git-1.1.1.148.47a69d0 helps

**Comment by elieux** [comment]
I can verify. The process chain looks like this:
```
/mingw64/bin/npm
/usr/bin/sh (executes script)
/mingw64/bin/node /mingw64/bin/../lib/node_modules/npm/bin/npm-cli.js
/usr/bin/bash (executes script)
/usr/bin/winpty /mingw64/bin/node.exe /mingw64/bin/../lib/node_modules/npm/bin/npm-cli.js
C:\msys64\mingw64\bin\node.exe /mingw64/bin/../lib/node_modules/npm/bin/npm-cli.js
```

**Comment by elieux** [comment]
I assume that there should be some path mangling going on at the last step, but for some reason, it's not there with the newer winpty build. Unfortunately, I don't have time to dive into the source code (or the changelog) at the moment.

**Comment by elieux** [comment]
So [this is what changed since the previous build](https://github.com/rprichard/winpty/compare/47a69d0...db12b07). Nothing there strikes me as the definite reason for the breakage, but rprichard/winpty@2ecc596 looks pretty suspicious. Anyone up for bisecting it?

**Comment by poxu** [comment]
I have tried to do it, but I have trouble compiling winpty without that suspicious commit.

**Comment by elieux** [comment]
See #361 for a fix.

**Comment by danielmario** [comment]
It isn't working again with winpty-git 1~0.2.2.365.79c9859-1 and mingw-w64-x86_64-nodejs 0.10.40-1.
