### ISSUE TITLE
gnu-netcat 0.7.1 zero-IO mode bug

### ISSUE THREAD

**Issue by heskeutz** [Alexpux/MSYS2-packages#365]
Trying to execute commands such as the following doesn't work:
`$ nc -vvz localhost 80`
It results in the following error:
`assertion "ret == 0" failed: file "core.c", line 372, function: core_tcp_connect
Aborted (core dumped)`
I can confirm that the aforementioned operation works with netcat 1.11.

**Comment by mingwandroid** [comment]
Please make a pull request updating to netcat 1.11.
