### ISSUE TITLE
"winpty-git: rename console.exe to winpty.exe to fix unknown bugs"  not contains Makefile fix 

### ISSUE THREAD

**Issue by dokechin** [Alexpux/MSYS2-packages#367]
https://github.com/Alexpux/MSYS2-packages/commit/1f207df00201dbfcb46f9b41b667519c0a37cd2f

MSYS2-packages/winpty-git/src/winpty/Makefile
is remains console.exe description
so I cound not makepkg winpty-git occuring below error.

install: `build/console.exe' を stat できません: No such file or directory
Makefile:33: ターゲット 'install' のレシピで失敗しました

**Comment by Alexpux** [comment]
It contain. Seems you are missing to apply patch

**Comment by Alexpux** [comment]
Fixed
