### ISSUE TITLE
Unable to update anymore

### ISSUE THREAD

**Issue by jpsdr** [Alexpux/MSYS2-packages#372]
I've tried several things, re-install from scratch. I install several things, gcc one of them, upadte, everything went fine until the last final part, it appened a few days ago, final update fail.
My OS is Windows 7 x86, and so i'm using the "msys2-i686".
Here what i have :

```
$ pacman -Su
:: Début de la mise à jour complète du système...
résolution des dépendances...
recherche des conflits entre paquets...

Paquets (2) curl-7.45.0-1  libcurl-7.45.0-1

Taille totale installée :     1,07 MiB
Taille de mise à jour nette :  0,04 MiB

:: Procéder à l’installation ? [O/n] O
(2/2) vérification des clés dans le trousseau      [#####################] 100%
(2/2) vérification de l’intégrité des paquets      [#####################] 100%
(2/2) chargement des fichiers des paquets          [#####################] 100%
(2/2) analyse des conflits entre fichiers          [#####################] 100%
(2/2) vérification de l’espace disque disponible   [#####################] 100%
erreur : impossible d’ouvrir le dossier //usr/share/libalpm/hooks/ : Permission denied
erreur : la validation de la transaction a échoué (failed to run transaction hooks)
Des erreurs se sont produites, aucun paquet n’a été mis à jour.
```

Translation : 
```
Start up full update system
<....>
Do you want to update [Y/n] Y
<...>
(2/2) check of avaible disc space [#########] 100%
error : unable to open (directory or file but the word is directory)  //usr/share/libalpm/hooks/ : Permission denied
error : (this one already has translation).
Errors has occured, no update done.
```

This occurs after installation of a lot of several others things and packages, and it's only since a few days.

**Comment by jpsdr** [comment]
I've more information on the issue : If i'm not updating the core, installing and updating things with the core from the msys2-i686-20150916 version, everything works fine. As soon as i update the core, i'm not able to install/update anymore. It happened only very recentely, so issue is probably caused by a very recent core update.

**Comment by elieux** [comment]
Can you try updating `msys2-runtime` and `pacman` separately, with shell exit+reopen inbetween? It'd be nice to find out which package is causing the problem here.

By the way, you don't have to re-install everytime, you can create a separate installation just for testing or use backups.

**Comment by jpsdr** [comment]
I've tested, and it's the ```pacman``` package which create the problem here.

**Comment by elieux** [comment]
Do you have the `/usr/share/libalpm/hooks` directory?

**Comment by jpsdr** [comment]
Neither do i... More strange, on my PC at work under Windows XP x86, i don't have this issue. And my home PC is dual boot Windows 7 x86/x64, and i don't have the issue under Windows7 x64, only x86.

**Comment by jpsdr** [comment]
I've created the directory and tested, out of curiosity, but still the same error message... :(

**Comment by elieux** [comment]
Are you able to dig into the source code? [guide here](https://sourceforge.net/p/msys2/wiki/Contributing%20to%20MSYS2/)

**Comment by jpsdr** [comment]
Not realy...

**Comment by jpsdr** [comment]
Tested with the new core update, still the same issue... :(

**Comment by BMBurstein** [comment]
same issue here. same error. :(

**Comment by BMBurstein** [comment]
@jpsdr I found what appears to be a workaround (at least, it works for me so far): Download the previous base (from May 12) and start from that. I was able to update the core (using the old pre update-core method since it is not yet in this version), and then update everything else without error.

**Comment by jpsdr** [comment]
At least, i'm not alone...
As i have a multi-boot pc (as explained), for now my workaround is to update when i boot under Windows7 x64.

**Comment by BMBurstein** [comment]
I didn't realize you were having this issue on 32bit Windows. I am having it on 64bit Windows 7.

**Comment by jpsdr** [comment]
But the difference is that my Windows7 x64 is very light, minimal, almost nothing is installed. My standard OS, with "everything" installed is the 32bits version. Maybe there is some kind of conflict with something else, but what...??

**Comment by Alexpux** [comment]
Try downgrade "msys2-runtime" to one of the previous releases and then try update packages again

**Comment by BMBurstein** [comment]
This issue just started again for me. I will look up how to downgrade and try Alexpux's advice.

**Comment by BMBurstein** [comment]
No it gets weird. I was getting this error while working at home on my work laptop. I connected the VPN to the office, and pacman works. I disconnect the VPN and this error returns. I tried a few times and it seems consistent. But I have no problem downloading the packages even on my home connection, only installing them after they are downloaded. So the network connection shouldn't have any effect at that point!

**Comment by mingwandroid** [comment]
Some questions (note, the answers to these won't lead me personally to diagnose much further since I'm not good with this sort of stuff, but it will likely be helpful for some of the others):

1. Did you install MSYS2 while connected to the company network? (maybe then some weird ACL stuff got involved).
2. Did you mess with /etc/nsswitch.conf?
3. Did you mess with /etc/fstab?
4. Did you run mkpasswd and/or mkgroup?

I think you might need to use strace to dig deeper.

**Comment by BMBurstein** [comment]
1. Yes.
2. Yes, see http://sourceforge.net/p/msys2/mailman/message/34103617/
3. No.
4. Yes, see answer 2 above.

**Comment by mingwandroid** [comment]
That all sounds like it's working as expected to me then. Your MSYS2 account is tied to your work network, so when you aren't connected to that you don't have permissions anymore.

**Comment by BMBurstein** [comment]
Glad to know it is working, although the error message could be more helpful, but just for my general education, can you explain to me what is going on here? I have no idea how permissions and accounts work in either msys or Windows, and just followed the steps in the link above as copy-paste, without understanding what I was doing.

**Comment by jpsdr** [comment]
On my PC at home.
1. PC was just connected to internet, but no weird account or anything.
2 and more. No.

**Comment by elieux** [comment]
@jpsdr, issue still there?

Do you have any hook-related options in `/etc/pacman.conf`? Can you post the output of pacman run with the error with `--debug` added to the command line?

**Comment by jpsdr** [comment]
I've just tested, yes.
Pacman.conf :
 
#
# /etc/pacman.conf
#
# See the pacman.conf(5) manpage for option and repository directives

#
# GENERAL OPTIONS
#
[options]
# The following paths are commented out with their default values listed.
# If you wish to use different paths, uncomment and update the paths.
#RootDir     = /
#DBPath      = /var/lib/pacman/
#CacheDir    = /var/cache/pacman/pkg/
#LogFile     = /var/log/pacman.log
#GPGDir      = /etc/pacman.d/gnupg/
HoldPkg      = pacman
#XferCommand = /usr/bin/curl -C - -f %u > %o
#XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u
#CleanMethod = KeepInstalled
#UseDelta    = 0.7
Architecture = auto

# Pacman won't upgrade packages listed in IgnorePkg and members of IgnoreGroup
#IgnorePkg   =
#IgnoreGroup =

#NoUpgrade   =
#NoExtract   =

# Misc options
#UseSyslog
#Color
#TotalDownload
CheckSpace
#VerbosePkgLists

# By default, pacman accepts packages signed by keys that its local keyring
# trusts (see pacman-key and its man page), as well as unsigned packages.
#SigLevel = Never
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
#RemoteFileSigLevel = Required

# NOTE: You must run `pacman-key --init` before first using pacman; the local
# keyring can then be populated with the keys of all official Arch Linux
# packagers with `pacman-key --populate archlinux`.

#
# REPOSITORIES
#   - can be defined here or included from another file
#   - pacman will search repositories in the order defined here
#   - local/custom mirrors can be added here or in separate files
#   - repositories listed first will take precedence when packages
#     have identical names, regardless of version number
#   - URLs will have $repo replaced by the name of the current repo
#   - URLs will have $arch replaced by the name of the architecture
#
# Repository entries are of the format:
#       [repo-name]
#       Server = ServerName
#       Include = IncludePath
#
# The header [repo-name] is crucial - it must be present and
# uncommented to enable the repo.
#

# The testing repositories are disabled by default. To enable, uncomment the
# repo name header and Include lines. You can add preferred servers immediately
# after the header, and they will be used before the default mirrors.

[mingw32]
Include = /etc/pacman.d/mirrorlist.mingw32

[mingw64]
Include = /etc/pacman.d/mirrorlist.mingw64

[msys]
Include = /etc/pacman.d/mirrorlist.msys

# An example of a custom package repository.  See the pacman manpage for
# tips on creating your own repositories.
#[custom]
#SigLevel = Optional TrustAll
#Server = file:///home/custompkgs

Here the end with debug :

debug: looking for file conflicts
debug: searching for file conflicts: msys2-runtime
debug: searching for filesystem conflicts: msys2-runtime
debug: searching for file conflicts: flex
debug: searching for filesystem conflicts: flex
debug: searching for file conflicts: mingw-w64-i686-headers-git
debug: searching for filesystem conflicts: mingw-w64-i686-headers-git
debug: searching for file conflicts: mingw-w64-i686-crt-git
debug: searching for filesystem conflicts: mingw-w64-i686-crt-git
debug: searching for file conflicts: mingw-w64-i686-libpng
debug: searching for filesystem conflicts: mingw-w64-i686-libpng
debug: searching for file conflicts: mingw-w64-i686-tools-git
debug: searching for filesystem conflicts: mingw-w64-i686-tools-git
debug: searching for file conflicts: msys2-runtime-devel
debug: searching for filesystem conflicts: msys2-runtime-devel
debug: searching for file conflicts: ncurses
debug: searching for filesystem conflicts: ncurses
vérification de l’espace disque disponible...
debug: checking available disk space
debug: discovered mountpoint: /m
debug: discovered mountpoint: /k
debug: discovered mountpoint: /j
debug: discovered mountpoint: /i
debug: discovered mountpoint: /h
debug: discovered mountpoint: /g
debug: discovered mountpoint: /f
debug: discovered mountpoint: /e
debug: discovered mountpoint: /d
debug: discovered mountpoint: /c
debug: discovered mountpoint: /bin
debug: discovered mountpoint: /
debug: loading fsinfo for /
debug: partition /, needed 5, cushion 5121, free 1768031
erreur : impossible d’ouvrir le dossier //usr/share/libalpm/hooks/ : Permission denied
debug: returning error 31 from alpm_trans_commit : failed to run transaction hooks
erreur : la validation de la transaction a échoué (failed to run transaction hooks)
Des erreurs se sont produites, aucun paquet n’a été mis à jour.
debug: unregistering database 'local'
debug: freeing package cache for repository 'local'
debug: unregistering database 'mingw32'
debug: freeing package cache for repository 'mingw32'
debug: unregistering database 'mingw64'
debug: freeing package cache for repository 'mingw64'
debug: unregistering database 'msys'
debug: freeing package cache for repository 'msys'

**Comment by elieux** [comment]
Can you `pacman -Sv`? Just for completeness.

What does `ls //usr/share/libalpm/hooks/` do? Do you by any chance have a `usr` computer on your local network?

**Comment by jpsdr** [comment]
I don't have a usr computer on my local network, and ls //usr/share/libalpm/hooks will probably do nothing because directory doesn't exist. And if i create the directory, it changes nothing, as i've allready said. I'll do the pacman -Sv this evening when back home.

**Comment by elieux** [comment]
It seems you've misunderstood. The problem is that the path checked by pacman has two slashes at the start, thus constituting a [UNC path](https://cygwin.com/cygwin-ug-net/using.html#unc-paths). `ls //usr/share` also fails even though `/usr/share/` exists.

**Comment by jpsdr** [comment]
Result of ls :
$ ls //usr/share/libalpm/hooks/
ls: impossible d'ouvrir le répertoire //usr/share/libalpm/hooks/: Permission denied
"Unable to open directory ...."

$ pacman -Sv
Root      : /
Conf File : /etc/pacman.conf
DB Path   : /var/lib/pacman/
Cache Dirs: /var/cache/pacman/pkg/
Hook Dirs : //usr/share/libalpm/hooks/  /etc/pacman.d/hooks/
Lock File : /var/lib/pacman/db.lck
Log File  : /var/log/pacman.log
GPG Dir   : /etc/pacman.d/gnupg/
Targets   : --
erreur : aucune cible spécifiée (utiliser -h pour l’aide)

**Comment by elieux** [comment]
Okay, that sounds right. For reference, this is what happens on my installation (and I guess on installations of many others):

```
$ ls //usr/share/libalpm/hooks/
ls: cannot access //usr/share/libalpm/hooks/: No such file or directory
```

We need to fix the path in pacman. After that, you should be able to update it again without problems.

**Comment by elieux** [comment]
I sent a patch to the `pacman-dev` mailing list, see https://lists.archlinux.org/pipermail/pacman-dev/2015-November/020607.html. I expect the patch will make it into master during the week and we'll release new `pacman` package after that.

**Comment by jpsdr** [comment]
Issue is now fixed, thanks.
