### ISSUE TITLE
Current tmux broken

### ISSUE THREAD

**Issue by 573** [Alexpux/MSYS2-packages#376]
I tried using `tmux`:

    $ tmux -V
> tmux 2.2

    $ pacman -Ss tmux-git
> msys/tmux-git 2.1.61.gc975de2-1 [Installiert]
    A terminal multiplexer

When I'm running `tmux` this is what I get (`tmux.exe.stackdump`):

> Exception: STATUS_ACCESS_VIOLATION at rip=0018019C1FD
rax=0000000000000008 rbx=0000000600075280 rcx=0000000000000008
rdx=000000000022CE00 rsi=0000000000229C50 rdi=0000000000000008
r8 =0000000000000158 r9 =0000000000000158 r10=0000000000230000
r11=00000001004436EA r12=0000000000000000 r13=0000000000000000
r14=0000000000000000 r15=0000000600069F80
rbp=0000000000000000 rsp=0000000000229AB8
program=C:\ProgramData\msys64\usr\bin\tmux.exe, pid 9964, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
00000000000  0018019C1FD (001801297AB, 00000229B18, 00000229B20, 00600075280)
00000000000  001004437AF (3F300000018, 0060006B100, 00000000000, 00600074FC8)
00000000000  0010042F52F (00000000001, 00000000030, 00000000000, 00000000008)
00600051BC0  0010040BAB4 (00600051BC0, 00000229CF0, 000000003F3, 737365732D77656E)
00000229CF0  0010040D02D (00600051BC0, 00000000000, 00600057500, 00000000001)
00600057AB8  0010040D188 (0010042B71B, 00000000000, 00600057500, 0000022A198)
00600057AB8  0010042B4B7 (7FEFF5A00E0, 0000022A220, 00000395B90, 00000000000)
00600057AB8  0010042BBE7 (00600057AB0, 000000000C8, 001802FC488, 0000022A680)
00600057AB8  00100426510 (00600016138, 00000000005, 001801297AB, 00600067AF8)
0060001D140  004E2CA338C (001800CDDE3, 00000000005, 00100469380, 00000000000)
00000000001  004E2CA3AA1 (0060001D330, 00000000000, 00000000002, 00600015FD0)
00000000005  0010042676F (00600057500, 000FFFFFFFF, 00000000000, 00700000006)
00000000005  0010042D521 (00180251716, 00000000000, 0000022A89C, 00000000000)
00000000005  00100403712 (00000000000, 00000000000, 00000000000, 00000000000)
0000022CB68  00100403B01 (00000000000, 00000000000, 00180328916, 00100000000)
00600010420  001004470F8 (00000000020, 30001000300FF00, 00180048350, 0000022D680)
End of stack trace (more stack frames may be present)

**Comment by Joffrey** [comment]
Same problem on my Msys2 x64 installation.

**Comment by moguriso** [comment]
I confirmed as well ;-(

**Comment by dvhh** [comment]
To expand on what @Joffrey is saying (downgrading tmux 2.1=>2.0) : 

    cd /var/cache/pacman/pkg/
    pacman -U tmux-git-2.0.198.g9a0ce98-1-x86_64.pkg.tar.xz

**Comment by 573** [comment]
@Joffrey, @dvhh thanks for the workaround. Runs.

**Comment by kracejic** [comment]
I can also confirm this. Old version (2.0) runs fine.

**Comment by Joffrey** [comment]
The new package **tmux-git-2.1.144.g78a00c8-1** doesn't work neither.

**Comment by moguriso** [comment]
It looks OK to run on my environment. However my patch is not good. Because tmux.stackdump file is out yet... @Joffrey if possible, could you provide me your .tmux.conf file?

**Comment by dvhh** [comment]
@Joffrey have you run `update-core` 

I confirm that the fix from @moguriso works as intended

**Comment by Joffrey** [comment]
Yes I Did.
Tmux is no longer working for me.

>Exception: STATUS_ACCESS_VIOLATION at rip=0018016486B
>rax=FFFFFFFFFFFFFFF8 rbx=0000000000000008 rcx=0000000000000008
>rdx=00000000FFFFFFFF rsi=00000006000563E0 rdi=0000000100426BF0
>r8 =0000000001501150 r9 =0000000600000000 r10=0000000000600000
>r11=00000001802FF400 r12=00000006000669E8 r13=0000000000000000
>r14=0000000000000000 r15=000000007FFFFFFF
>rbp=00000006000569A8 rsp=00000000005FA100
>program=C:\msys64\usr\bin\tmux.exe, pid 8712, thread main
>cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
>Stack trace:
>Frame        Function    Args
>006000569A8  0018016486B (00180129BEB, 006000569A8, 006000669E8, 006000567F8)
>006000569A8  001800CE5D3 (006000563E0, 00000058001, 00000000010, 006000563E0)
>006000569A8  00180129BEB (006000563E0, 00000058001, 00000000010, 006000563E0)
>006000569A8  0010042A8A9 (00000000001, 00000000000, 00000000000, 00000000000)
>006000569A8  0010042C59C (003FB0A0525, 00000000000, 0018010382D, 0060006E680)
>006000569A8  00100426C6E (0060001B848, 00000000005, 00180129BEB, 006000669E8)
>0060001B9B0  003FB0A338C (006000699A0, 00600089A30, 0010042B67E, 0010042D820)
>00000000001  003FB0A3AA1 (0060001BBA0, 00000000000, 00000000002, 0060001B6E0)
>00000000005  00100426EEF (006000563E0, 000FFFFFFFF, 00000000000, 00700000006)
>00000000005  0010042DF1C (00180254716, 00000000000, 000005FA89C, 00000000001)
>00000000005  001004036A2 (00000000000, 00000000000, 00000000000, 000005FA9F8)
>000005FCB68  00100403A71 (00000000000, 00000000000, 0018032C3D6, 001802D8800)
>00000000001  00100447B02 (00000000020, FF0700010302FF00, 00180048350, 000005FD680)
>000005FCBC0  001800483C1 (00000000000, 00000000000, 00000000000, 00000000000)
>00000000000  0018004603C (00000000000, 00000000000, 00000000000, 00000000000)
>00000000000  001800460D4 (00000000000, 00000000000, 00000000000, 00000000000)
>End of stack trace (more stack frames may be present)

**Comment by Joffrey** [comment]
**~/.tmux.conf** file

># vim: set ft=tmux :
># https://github.com/rafaelh/dot_win/blob/master/tmux.conf
>
># set -g mouse-select-window on
># set -g mouse-select-pane on
>
>#set -sg escape-time 250
>
>set -g terminal-overrides "xterm*:Ms=\\E]52;%p1%s;%p2%s\\007:Ss=\\E[%p1%d q:Se=\\E[0 q"
># ^ l'astuce qui me manquait car le curseur (de texte) ne revenait pas à la normale
>
># https://gist.github.com/saamalik/5691197
># http://comments.gmane.org/gmane.comp.terminal-emulators.tmux.user/4685
>set -g default-terminal "screen-256color"
>set -g default-command "CHERE_INVOKING=1 MSYSTEM=MSYS bash -i"
>#set -g default-command "CHERE_INVOKING=1 MSYSTEM=MSYS bash --login"
>
>bind c new-window -c "#{pane_current_path}"
>
># == COLOUR Scheme (Solarized dark) ==
>
># Status Bar Colours
>set-option -g status-fg yellow                            #Status Bar fg
>set-option -g status-bg black                             #Status Bar bg
>set-option -g status-attr default
>set-window-option -g window-status-current-fg brightred   #Active Window fg
>set-window-option -g window-status-current-bg default     #Active Window bg
>
># default window title colors
>set-window-option -g window-status-fg brightblue          #base0
>set-window-option -g window-status-bg default
>#set-window-option -g window-status-attr dim
>
># Window Pane Border Colours
>set-option -g pane-border-fg        brightgreen           #Window Border 
>set-option -g pane-active-border-fg brightgreen           #Active Window Border
>
># message text
>set-option -g message-bg black                            #base02
>set-option -g message-fg brightred                        #orange
>
># pane number display
>set-option -g display-panes-active-colour blue            #blue
>set-option -g display-panes-colour brightred              #orange
>
># clock
>set-window-option -g clock-mode-colour green              #green

**Comment by ilvetz** [comment]
Same error using Zsh. When I use bash, tmux works correctly.

**Comment by moguriso** [comment]
I'm investigating but I don't progress for now. Probably one or some environment parameter is not correctly passed to tmux from console. (It will include the expectations.)

> Exception: STATUS_ACCESS_VIOLATION at rip=0018016486B

This stackdump seems output from xstrdup. Currently msys2 repo includes my patch so tmux could run tentatively. But that still dump stackdump file. Therefor I think stackdump is not reason of stop issue.

**Comment by 573** [comment]
I confirm it works!

**Comment by klesh** [comment]
Hi, I run into same situation here.
```bash
$ pacman -Ss tmux
msys/tmux-git 2.1.263.g5083e93-1
$ tmux
lost server
$ tmux -V
tmux 2.2
```
Unfortunately, I don't have a older version reside in /var/cache/pacman/pkg to rollback...
Can anyone advise how to solve this? I tried this but no luck either:
```bash
$ pacman -S "tmux=2.0"
```

**Comment by moguriso** [comment]
@klesh It seems current version is not installed. Because if it's done, console should be shown like below.

```
$ pacman -Ss tmux
msys/tmux-git 2.1.263.g5083e93-1 [installed]
    A terminal multiplexer
```

How would  you like to try re-install current version?

`$pacman -S tmux`

In addition if "/etc/tmux-xxxx" directory is available, remove it just in case before you run tmux.

**Comment by nobk** [comment]
tmux dont work on my last updated msys2.

```
$ pacman -Ss tmux
msys/tmux-git 2.1.263.g5083e93-1 [installed]
    A terminal multiplexer
$ tmux -V
tmux 2.2
$ tmux
lost server
$ pacman -Q filesystem
filesystem 2017.02-4
$ env | grep UTF
LANG=zh_CN.UTF-8
LC_MESSAGES=C.UTF-8
$
```
