### ISSUE TITLE
Aclocal and autoconf broken by latest msys2-runtime

### ISSUE THREAD

**Issue by wiiaboo** [Alexpux/MSYS2-packages#379]
msys2-runtime-2.2.1.**16655**.6ecd782-1-x86_64 works.
With msys2-runtime-2.3.0.**16690**.4930b0d-1-x86_64 installed, on running aclocal/autoconf, eventually `sh.exe` freezes with 50% CPU load, but on force-closing the `sh.exe` process twice aclocal/autoconf seem to continue working normally and creating working "configure" scripts.

**Comment by MrXo** [comment]
You just saved me from many more hours of digging through Google search results, I would've never figured that out on my own. Closing the shell process indeed helps.

Has this been fixed for a future release?

**Comment by wiiaboo** [comment]
Yes, it was.
