### ISSUE TITLE
zsh completion issue

### ISSUE THREAD

**Issue by EdVanDance** [Alexpux/MSYS2-packages#38]
Hi guys,

it's pretty cool to have zsh in msys2, but unfortunately it does not complete hard drives.
E.g: `cd /c/<TAB>` does not show possible completions for `/c`. But it works as expected for bash.

Any ideas about fixing this?

Greetings, 
Ed

CC @mashir43

**Comment by baldrianbandit** [comment]
Within Msys2, running compinit breaks the autocompletion of paths.

Assuming you are using oh-my-zsh, comment out the whole sections "Load and run compinit" and "Load all plugins" within ~/.oh-my-zsh/oh-my-zsh.sh and restart your shell.

**Comment by elieux** [comment]
@baldrianbandit, would you know if this is a bug in MSYS2, or in zsh? If there is a way to fix this issue without disabling stuff (I assume compinit and plugins are generally useful and desirable features), maybe we can patch this and fix it for all users.

**Comment by EdVanDance** [comment]
It works without compinit. But zsh without its completion system is somehow useless :cry: 

Any ideas about fixing?

**Comment by heinep** [comment]
Hi guys,

With compinit loaded, try putting this line into your zshrc configuration file:
`zstyle ':completion:*' fake-files /: '/:c'`
You should be able to autopcomplete on /c/whatever/file/or/directory.

If you need completion on more hard drives/partitions just add them after the 'c', eg.
`zstyle ':completion:*' fake-files /: '/:c d e'`

This is just a workaround and I do think that the issue should be fixed somewhere upstream. But never the less I've got autocompletion on /c, /d, etc. in zsh now.

**Comment by EdVanDance** [comment]
Wow that's awesome, it works :+1: 

I added the following snippet to my zshrc to get all drives automatically added:
```sh
# complete hard drives in msys2
drives=$(mount | sed -rn 's#^[A-Z]: on /([a-z]).*#\1#p' | tr '\n' ' ')
zstyle ':completion:*' fake-files /: "/:$drives"
unset drives
```

Thanks a lot @heinep.

**Comment by EdVanDance** [comment]
After some further investigation I think fake-files is the only way to go.

This approach is also mentioned in [From Bash to Z Shell](https://books.google.de/books?id=_q7ZgTUvft0C&pg=PA257&lpg=PA257&dq=bash+cygdrive+completion&source=bl&ots=IixXof8R0j&sig=8foN_Y3RWFK-_MChC-mDQ2iA4QM&hl=en&sa=X&redir_esc=y#v=onepage&q=bash%20cygdrive%20completion&f=false).
