### ISSUE TITLE
binutils is not in base-devel

### ISSUE THREAD

**Issue by cptG** [Alexpux/MSYS2-packages#382]
When trying to build a package with makepkg, even after installing base-devel, the strip executable is not found. You have to install binutils.
I think it'd make sense to include binutils in base-devel.

**Comment by cptG** [comment]
Oh, I see. msys2-devel is the group needed to build packages.
Maybe update README?

**Comment by elieux** [comment]
See https://sourceforge.net/p/msys2/wiki/Contributing%20to%20MSYS2/

I updated the page to make it clearer that `base-devel` differs from what an ArchLinux user might expect.
