### ISSUE TITLE
[Package Request] GDL - GNU Data Language

### ISSUE THREAD

**Issue by BWV998** [Alexpux/MSYS2-packages#387]
I'd like to use [GDL - GNU Data Language](http://gnudatalanguage.sourceforge.net) on MSYS2.
Could you add GDL, please?

Thank you.

**Comment by elieux** [comment]
As an msys2 package, or a mingw-w64 package?

**Comment by BWV998** [comment]
I’m so sorry for not replying sooner.
As a mingw-w64 package, please?
I would appreciate if you could deal with it when you have time.

Thank you.

**Comment by elieux** [comment]
In that case, please open an issue in http://github.com/alexpux/mingw-packages and close this one. I can't guarantee that anyone will pick the request and starts working on it, unless they, as well, want GDL on Windows.

Note this link: http://cyfinity.egloos.com/1727847

**Comment by BWV998** [comment]
Hi, elieux.
Thank you for your reply.

I see, I'll close this issue.
Thank you for your kindness.
