### ISSUE TITLE
Cmake does nothing, simply returns

### ISSUE THREAD

**Issue by markjohndoyle** [Alexpux/MSYS2-packages#397]
Hi,

I've installed cmake via pacman but nothing happens when I run it. I've tried --version and --help but get the same result. I've tried both **msys/cmake 3.2.3-1** and **mingw64/mingw-w64-x86_64-cmake 3.3.2-2** in combinations.

I have base-devel installed and the following make version:

```
λ make --version
GNU Make 4.1
Built for x86_64-pc-msys
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

I'm definitely defaulting to the mingw64 version:

```
λ which cmake
/mingw64/bin/cmake
```

I've also installed the cmake extras just in case but saw no change which isn't unexpected.

Other info:
OS: Windows 10 x64
There is a windows version of cmake on the system but it's lower in the PATH hierarchy and I get the same results whether it's installed or not.

Any ideas?

**Comment by mingwandroid** [comment]
Strange. Where's your MSYS2 root directory?

**Comment by markjohndoyle** [comment]
It is, everything else has worked fine.

MSYS2 is located at `C:\msys64`

**Comment by mingwandroid** [comment]
Can you paste the contents of log.txt after `strace cmake.exe > log.txt 2>&1` here please?

**Comment by markjohndoyle** [comment]
[log.txt](https://github.com/Alexpux/MSYS2-packages/files/47132/log.txt)


There is an interested few lines around line 981.

```
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in
/mingw64/share/cmake-3.2.3 2834 2513202 [main] cmake 10912 write: 152 = write(2, 0x60005CCD8, 152)
```

**Comment by mingwandroid** [comment]
That's actually OK, strace.exe unfortunately affects the thing it observes. This is something that we need to fix.

**Comment by Alexpux** [comment]
Current mingw make is 3.3.2 so I wonder why it try to find /mingw64/share/cmake-**3.2.3**

**Comment by mingwandroid** [comment]
Try without conemu.

**Comment by markjohndoyle** [comment]
@Alexpux , I currently have mingw and msys versions installed, but I get the same error if I have either or both installed.

```
λ pacman -Ss cmake
mingw32/mingw-w64-i686-cmake 3.3.2-2
    A cross-platform open-source make system (mingw-w64)
mingw32/mingw-w64-i686-extra-cmake-modules 5.12.0-1
    Extra CMake modules (mingw-w64)
mingw64/mingw-w64-x86_64-cmake 3.3.2-2 [installed]
    A cross-platform open-source make system (mingw-w64)
mingw64/mingw-w64-x86_64-extra-cmake-modules 5.12.0-1 [installed]
    Extra CMake modules (mingw-w64)
msys/cmake 3.2.3-1 [installed]
    A cross-platform open-source make system
```

@mingwandroid 
Same issue within the mingw shell **mingw64_shell.bat**

Aha! It seems on in the **msys2_shell.bat**

**Comment by markjohndoyle** [comment]
My conemu task is as follows:

```
set MSYSTEM=MINGW64  & "C:\msys64\usr\bin\bash.exe"  --login -i -new_console:t:Console
```

I guess this is the MSYSTEM variable as it also fails in mingw64_shell.bat

**Comment by mingwandroid** [comment]
That should be fine though!

**Comment by markjohndoyle** [comment]
Ok, it's fine in conemu if I set MSYSTEM to MSYS

```set MSYSTEM=MSYS  & "C:\msys64\usr\bin\bash.exe"  --login -i -new_console:t:Console```

which isn't a solution but it's a pretty big clue I guess.

**Comment by mingwandroid** [comment]
In general other mingw64 stuff works? I'll have to try to help you after my work I think.

**Comment by markjohndoyle** [comment]
Given Alexs comment, maybe the mingw shell is trying to use the msys version. I'm not even sure if that would be a problem but it's all I can think of. Having said that, the binaries each shell is using seem to be correct:
```
MINGW64 ~
λ which cmake
/mingw64/bin/cmake


MSYS ~
λ which cmake
/usr/bin/cmake
```

Everything else works very well, I use gcc daily and gdb often. This is the only issue I've have with msys2.

**Comment by markjohndoyle** [comment]
Another lead:

The trace log.txt shows

```
    2       2 [main] cmake (8392) **********************************************
  276     278 [main] cmake (8392) Program name: C:\msys64\usr\bin\cmake.exe (windows pid 8392)
   42     320 [main] cmake (8392) OS version:   Windows NT-10.0
   48     368 [main] cmake (8392) **********************************************
```

which I think is the msys cmake (3.2.3)

I'd expect 

```
MINGW64 ~
λ which cmake
/mingw64/bin/cmake
```
to run ```C:\msys64\mingw64\bin\cmake.exe```

**Comment by mingwandroid** [comment]
Ah, that was my bad instructions, please do: `strace C:/msys64/mingw64/bin/cmake.exe` instead.

**Comment by markjohndoyle** [comment]
Shouldn't cmake default to /mingw64/bin anyway?

Ok ```strace /mingw64/bin/cmake > log.txt 2>&1``` shows a different error. It looks like the cmake binary is missing a shared object or symbol.

![missing-symbol](https://cloud.githubusercontent.com/assets/223918/11470155/e9f1e6ae-975b-11e5-9f67-932d2b944ae1.PNG)

**Comment by mingwandroid** [comment]
Ok, you need to drop dependency walker into your mingw64/bin folder and launch it from msys64_shell.bat, then load cmake.exe into that, and figure out what DLL is getting loaded from somewhere in your path outside of MSYS2.

**Comment by markjohndoyle** [comment]
Do you mean mingw64_shell.bat? Cmake works fine in the msys64_shell.

I'm not sure how to read the dependency walker output, there seems to be a lot of warnings and yellow icons even when I run something that works fine.

I did notice the same missing function though when I ran:
```
MINGW64 /mingw64/bin
λ ./depends ./cmake.exe
```

I've attached the output just in case you find it useful. The Dll looks like it comes from msys:
![cmake-dep-walk](https://cloud.githubusercontent.com/assets/223918/11472499/5347a858-976d-11e5-91e1-efc22be243cc.PNG)

**Comment by mingwandroid** [comment]
Ok, compare against:

```
sha1sum /mingw64/bin/libstdc++-6.dll
d9578495bf43c3553702c9c31c4d287e288a1def */mingw64/bin/libstdc++-6.dll

pacman -Ss mingw-w64-x86_64-gcc-libs
mingw64/mingw-w64-x86_64-gcc-libs 5.2.0-4 (mingw-w64-x86_64-toolchain) [installed]
    GNU Compiler Collection (libraries) for MinGW-w64
```

**Comment by markjohndoyle** [comment]
This might be interesting, I have my gcc and gcc-libs on ignore (probably should've remembered that earlier, sorry!) as I have to stay < 5

I suppose cmake is compiled against a newer libc++?

```
MINGW64 /mingw64/bin
λ sha1sum libstdc++-6.dll
e1da77aea61289784e68af382b4f325f9b56884b *libstdc++-6.dll

MINGW64 /mingw64/bin
λ pacman -Ss mingw-w64-x86_64-gcc-libs
mingw64/mingw-w64-x86_64-gcc-libs 5.2.0-4 (mingw-w64-x86_64-toolchain) [installed: 4.9.2-5]
    GNU Compiler Collection (libraries) for MinGW-w64

MINGW64 /mingw64/bin
λ gcc --version
gcc.exe (Rev5, Built by MSYS2 project) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by mingwandroid** [comment]
MSYS2 is all about rolling releases and being close to the cutting edge. The ignore feature of ArchLinux's Pacman is strongly discouraged and should only ever be used for 'leaf' nodes of the (binary) dependency graph.

So yeah, you can't mix < 5 GCC and GCC libs and continue to update any other MSYS2 packages that link to those (in theory pretty much any of them, esp. C++ ones). If you need some old GCC then you should build that yourself into a different prefix but you're then off treading your own path in a world of incompatible-with-MSYS2-libraries.

Mentioning this sooner would've been good, but no worries.

Out of interest, why must you stay < 5?

**Comment by markjohndoyle** [comment]
Just because we have a lot of COTS compiled against 4 and somebody on the team had some ABI problems trying to compile using gcc 5. The target platform will be the v4 ABI so it was just simpler to hold off.

Honestly, I didn't look much further into it other than discovering it should be possible to compile with gcc5 although a few extra flags related to ABI might be required and there still may be some issues.

**Comment by mingwandroid** [comment]
I'm not sure what COTS are, but if you have binary software that you can't recompile and MSYS2 upgrades to a version of GCC that makes it incompatible with that software, then I think at that point you need to make your own mirror of MSYS2 or a server and forgo updating MSYS2 until you can arrange all the binary software to make the transition.

If you then need to compiler newer versions of other software against those frozen packages, e.g. CMake, the PKGBUILD / makepkg{,-mingw} system is hopefully user-friendly enough and we can help out if you run into problems.

**Comment by markjohndoyle** [comment]
Sorry, "Commercial off-the-shelf"; acronyms everywhere :)

Yes, that makes sense. 

I've just built cmake from source and installed it in it's own sandbox for now. Seems ok.

Thanks for all the help!

**Comment by TBBle** [comment]
I realise it's late, but the error shown in the dialog comes from cmake built with libstdc++ from gcc 5.1 onwards, trying to load libstdc++ from gcc 5.0 or older.

For details see [Dual ABI](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html) in the gcc documentation. Specifically, if you set `_GLIBCXX_USE_CXX11_ABI` to false when building, the old ABI for `std::list` and `std::string` will be used.

However, that doesn't solve the problem of code built against newer stdlibc++ versions depending on newer *features* in that stdlibc++ version compared to the older version. It's only for ABI compatibility when you have other libraries than stdlibc++ built against the old ABI.

Which means that this ticket looks like a user-environment issue, and can probably be closed.

**Comment by markjohndoyle** [comment]
Absolutely.
