### ISSUE TITLE
wget 1.17.1 stop working

### ISSUE THREAD

**Issue by zdm** [Alexpux/MSYS2-packages#424]
Hi.
After today wget update it stop working completely.
It doesn't show any output and do nothing.

**Comment by DavidEGrayson** [comment]
I haven't tried it myself but there were some people on the MSYS2 IRC saying wget now depends on gpgme.  I would recommend trying `pacman -S libgpgme` to install the missing dependency.  If that works, then the PKGBUILD for wget should be fixed to explicitly list libgpgme as a dependency.

**Comment by zdm** [comment]
Yes, it works with libgpgme installed.

**Comment by Alexpux** [comment]
Fixed.
