### ISSUE TITLE
Is there a simple install archive available (for "portable" installs)?

### ISSUE THREAD

**Issue by rivy** [Alexpux/MSYS2-packages#427]
I'm using [`scoop`](https://github.com/rivy/scoop) to install most of my Windows PC tooling these days. `scoop` installs the tools in a quick/easy, scriptable, and portable manner. I'd like to add an MSYS2 manifest for the tool so that I can install it in a similar manner, but the `scoop` tool requires an archive that can be simply extracted. Any archive type extractable by `7zip` would be workable.

I have a few GUI tools that can see and extract the .7z archive within the installer, but `7zip` itself cannot parse the installer as an archive nor extract any content.

Is there a simple, extractable archive available (or can one be made available)?

Just making the .7z archive artifact (already created during the installer generation step) available would probably solve the issue.

**Comment by mingwandroid** [comment]
If you want take go from A (fresh install of `Windows`) to B (`Windows` with `MSYS2`) via C (`Scoop`) that's your choice I suppose:

http://sourceforge.net/projects/msys2/files/Base/i686/msys2-base-i686-20150916.tar.xz/download
http://sourceforge.net/projects/msys2/files/Base/x86_64/msys2-base-x86_64-20150916.tar.xz/download

**Comment by rivy** [comment]
:+1:
