### ISSUE TITLE
minor flaws in MSYS2 perl

### ISSUE THREAD

**Issue by sav-ix** [Alexpux/MSYS2-packages#445]
Hi, everyone,

Got error while OpenSSL installation with MSYS2.

Used stuff:
- Windows 10,
- MinGW-W64 (5.3.0-<i686,x86_64),
- MSYS2 (4.3.42(4)-release-(x86_64-pc-msys)),
- OpenSSL-1.1.0-pre3-dev (git://github.com/openssl/openssl.git).

Error revealed while building OpenSSL `man` and `html` help files:

```
sh-4.3$ make install_docs
[snip]
installing man3/ssl.3
.3 => ssl.3
[note: in OpenSSL/GCC32r/share/man/ directory exists 409 files (3,44 MB), while should be 1 938 files (21,0 MB)]

sh-4.3$ make install_html_docs
[snip]
Can't open perl script "./util/mkdir-p": No such file or directory
installing html/CA.pl.html
/bin/sh: line 13: /c/libOPENSSL-1.1.0-dev/src/GCC32r/share/doc/openssl/html/apps/CA.pl.html: No such file or directory
/bin/sh: line 17: cd: /c/libOPENSSL-1.1.0-dev/src/GCC32r/share/doc/openssl/html/apps: No such file or directory
cp: cannot stat 'CA.pl.html': No such file or directory
.html => CA.pl.html
[snip]
```

OpenSSL developers pointed to the source of this error. Shell commands from OpenSSL sources directory should print:

```
sh-4.3$ perl util/extract-names.pl < doc/apps/CA.pl.pod
CA.pl
sh-4.3$ perl util/extract-names.pl < doc/ssl/ssl.pod
SSL
sh-4.3$ perl util/extract-names.pl < doc/ssl/SSL_connect.pod
SSL_connect
sh-4.3$
```

(as ActiveState and Strawberry Perl for Windows, Perl for Linux, etc. do), while they print empty strings:

```
sh-4.3$ perl util/extract-names.pl < doc/apps/CA.pl.pod

sh-4.3$ perl util/extract-names.pl < doc/ssl/ssl.pod

sh-4.3$ perl util/extract-names.pl < doc/ssl/SSL_connect.pod

sh-4.3$
```

Incorrect results printed if listed `.pod` files have Windows line endings; no such troubles if they have UNIX/OSX line endings.
If this is a flaw of MSYS2/PERL, whether could it be fixed?

Thanks

**Comment by sav-ix** [comment]
Found that described issue don't reproduce using recent MSYS2. I assume this issue could be closed.
Thank you.

**Comment by elieux** [comment]
Great! Thanks for reporting back.

Closing.
