### ISSUE TITLE
.bashrc file bug

### ISSUE THREAD

**Issue by usta** [Alexpux/MSYS2-packages#458]
Hello , i have found a bug in .bashrc file but couldn't find it in this repo.
Could you point me where it is so i can send a PR for the bug which i have found

**Comment by elieux** [comment]
```
$ pacman -Qo /etc/skel/.bashrc /etc/bash.bashrc
/etc/skel/.bashrc is owned by filesystem 2015.04-3
/etc/bash.bashrc is owned by filesystem 2015.04-3
```

**Comment by usta** [comment]
Thank you. Could you please check #459

**Comment by elieux** [comment]
I sent a response there. Closing this issue.
