### ISSUE TITLE
Something that worked with cmake from cmake.org and MSYS doesn't work with MSYS2

### ISSUE THREAD

**Issue by xaduha** [Alexpux/MSYS2-packages#485]
Used these to compile [pkcs11-proxy](https://github.com/Absolight/pkcs11-proxy)
mingw-get-setup.exe
msys-base-2013072300-msys-bin package
cmake-3.4.3-win32-x86.exe

using cmake -G "MSYS Makefiles" in msys.bat environment it works without issues.

Can't really call it a regression, since it's a different project and you don't even support "MSYS Makefiles" option as far as I know, but maybe someone will look into it out of interest.

**Comment by Alexpux** [comment]
Why not "MSYS Makefiles" work? We always use it. See any our PKGBUILD for cmake builded project:
https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-openjpeg2/PKGBUILD#L49

**Comment by xaduha** [comment]
Right you are, I was confused about that.

So I managed to generate Makefiles using "MSYS Makefiles" and managed to compile by adding "#include <sys/time.h>" to gck-rpc-daemon-standalone.c, but now I get a stackdump when I try to run it with the target library ([vcki.dll](http://www.ncryptoki.com/download.aspx)).

I'll try with 32bit MSYS2, maybe it's caused by that, because it worked with 32bit MSYS previously.

**Comment by xaduha** [comment]
Nope, didn't help.

```
./pkcs11-daemon.exe vcki.dll

Segmentation fault (core dumped)
```

**Comment by xaduha** [comment]
Without adding `#include <sys/time.h>` it goes like this

```
$ make
[  9%] Building C object CMakeFiles/pkcs11-daemon.dir/gck-rpc-daemon-standalone.obj
/C/msys32/pkcs11-proxy-master/gck-rpc-daemon-standalone.c: In function ‘main’:
/C/msys32/pkcs11-proxy-master/gck-rpc-daemon-standalone.c:71:2: error: unknown type name ‘fd_set’
  fd_set read_fds;
  ^
/C/msys32/pkcs11-proxy-master/gck-rpc-daemon-standalone.c:125:3: warning: implicit declaration of function ‘FD_ZERO’ [-Wimplicit-function-declaration]
   FD_ZERO(&read_fds);
   ^
/C/msys32/pkcs11-proxy-master/gck-rpc-daemon-standalone.c:126:3: warning: implicit declaration of function ‘FD_SET’ [-Wimplicit-function-declaration]
   FD_SET(sock, &read_fds);
   ^
/C/msys32/pkcs11-proxy-master/gck-rpc-daemon-standalone.c:127:3: warning: implicit declaration of function ‘select’ [-Wimplicit-function-declaration]
   ret = select(sock + 1, &read_fds, NULL, NULL, NULL);
   ^
/C/msys32/pkcs11-proxy-master/gck-rpc-daemon-standalone.c:136:3: warning: implicit declaration of function ‘FD_ISSET’ [-Wimplicit-function-declaration]
   if (FD_ISSET(sock, &read_fds))
   ^
CMakeFiles/pkcs11-daemon.dir/build.make:86: recipe for target 'CMakeFiles/pkcs11-daemon.dir/gck-rpc-daemon-standalone.obj' failed
make[2]: *** [CMakeFiles/pkcs11-daemon.dir/gck-rpc-daemon-standalone.obj] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pkcs11-daemon.dir/all' failed
make[1]: *** [CMakeFiles/pkcs11-daemon.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
