### ISSUE TITLE
perl: patch perl-5.22.0-msys2.patch breaks ExtUtils::CBuilder module

### ISSUE THREAD

**Issue by mabreedlove** [Alexpux/MSYS2-packages#492]
The patch (perl-5.22.0-msys2.patch) introduces the "msys" configuration type into the build.  Consequently, trying to build modules which rely on CBuilder functioning properly will fail as a check is performed to find its build environment file which resolves to /usr/share/perl5/core_perl/ExtUtils/CBuilder/Platform/msys.pm

This file naturally does not exist.  As a workaround, I have been making a copy of the cygwin.pm file and altering the lines:

```
package ExtUtils::CBuilder::Platform::cygwin;
$ExtUtils::CBuilder::Platform::cygwin::VERSION = '0.280221';
```

To:

```
package ExtUtils::CBuilder::Platform::msys;
$ExtUtils::CBuilder::Platform::msys::VERSION = '0.280221';
```

Which has not shown any issues.  It would be easy to handle this on packaging, but I'm open to other suggestions.

**Comment by Alexpux** [comment]
Fixed in perl 5.22.1
