### ISSUE TITLE
multiple pacman installed libraries have invalid cmake links

### ISSUE THREAD

**Issue by SimLeek** [Alexpux/MSYS2-packages#496]
when using msys to install packages with pacman, some of the cmake files in those packages (vtk and one other, ...glib? ...zlib?) including a non-existent directory called "building" before everything else when trying to link to other files. This means cmake can't compile these packages.

pacman: Pacman v4.2.1-503-g62b54-dirty - libalpm v10.0.1
vtk: mingw-w64-x86_64-vtk 6.3.0-2
gcc: mingw-w64-x86_64-gcc 5.3.0-2
cmake: mingw-w64-x86_64-cmake 3.4.1-1 ; mingw-w64-x86_64-extra-cmake-modules 5.18.0-1

**Comment by Alexpux** [comment]
Move this to mingw-packages.

**Comment by SimLeek** [comment]
moved.
