### ISSUE TITLE
winpty also converts URIs to DOS paths

### ISSUE THREAD

**Issue by wiiaboo** [Alexpux/MSYS2-packages#505]
`winpty mpv.com /c/test/video.mkv`
converts path to C:\test\video.mkv as expected, but
`winpty mpv.com http://example.com/video.mkv`
converts URI to http:\example.com\video.mkv`

Would it be possible to not convert URIs or at least add some option to winpty to not convert any path?

**Comment by elebeaup** [comment]
#411

**Comment by elebeaup** [comment]
#411

**Comment by chhe** [comment]
Try using `mpv.exe` instead of `mpv.com` as a workaround.

**Comment by wiiaboo** [comment]
The point would be using `mpv.com`. `mpv.exe` turns terminal off.

**Comment by wiiaboo** [comment]
Fixed by https://github.com/Alexpux/MSYS2-packages/pull/587/commits/f6440fbde4b9df9a2ce89e45b65abda1c1f9e7f3.
