### ISSUE TITLE
error: duplicated database entry 'coreutils'

### ISSUE THREAD

**Issue by sskras** [Alexpux/MSYS2-packages#509]
Today I tried upgrading my Msys2, got an error:

```
$ pacman -Syu
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
:: Starting full system upgrade...
error: duplicated database entry 'coreutils'
resolving dependencies...
looking for conflicting packages...

Packages (1) coreutils-8.25-1

Total Installed Size:  21.82 MiB
Net Upgrade Size:       0.60 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                     [#####################] 100%
(1/1) checking package integrity                   [#####################] 100%
(1/1) loading package files                        [#####################] 100%
(1/1) checking for file conflicts                  [#####################] 100%
error: failed to commit transaction (conflicting files)
coreutils: /usr/bin/base32.exe exists in filesystem
coreutils: /usr/share/man/man1/base32.1.gz exists in filesystem
Errors occurred, no packages were upgraded.
```

**Comment by Alexpux** [comment]
well I don't see collisions in pacman database:
````
pkgfile -uu
pkgfile base32.exe
````

Files present only in one package. So it can be that you build and install something yourself into system without pacman.

**Comment by s4kr4s** [comment]
> So it can be that you build and install something yourself into system without pacman.

Well, no.  I use it for running some programs only, to name a few:
```
bsdtar
curl
cvs
elinks-git
file
gawk
grep
vim 7.4.1468-1
w3m 0.5.3-1
wget 1.17.1-3
xz 5.2.1-1
```
Can it be due to a file corruption caused by temporal disconnects of network (shared) folder where all my roaming profile resides?  We have this awful issue at work.  It occured during last few days.

**Comment by Alexpux** [comment]
if you know that you not install anything yourself, you can pass "--force" to pacman to skip this issue

**Comment by s4kr4s** [comment]
> you can pass "--force" to pacman to skip this issue

Thanks, probably I will.  But at first I would like to find out which Msys2 file may contain the duplicate entry.  I'd then try to return it's content to some previous state.  Can you point me?  Sorry for my lazines.

This would absolutely prove our storage system being at fault and the only reason of this.  Hence my question.

**Comment by sskras** [comment]
I left that employer altogether with their network setup.  So I am unable to find out the exact culprit.
