### ISSUE TITLE
update-core not working anymore

### ISSUE THREAD

**Issue by jpsdr** [Alexpux/MSYS2-packages#524]
Hello.
Since the last core system update very recently, update-core command is not working anymore.

**Comment by elieux** [comment]
It was replaced by functionality in pacman. Our wiki was updated to reflect that. Just use `pacman -Syuu`. If core packages update, follow instructions and repeat.

**Comment by s4kr4s** [comment]
@elieux, excuse my noobness but isn't the project going to merge `-Suu` option with `-Su` (as in original pacman) ?  So as to keep differences between both implementations minimal.

**Comment by elieux** [comment]
What do you mean? The [upstream pacman manual page](https://www.archlinux.org/pacman/pacman.8.html#_sync_options_a_id_so_a) also mentions differences between `-Su` and `-Suu`.

**Comment by White-Tiger** [comment]
the main page wasn't updated to reflect this change however.. (the one most people will use/see)
https://msys2.github.io/

My usual problem with MSYS2 was, that after every update, "update-core" were missing and I had to run `pacman -S bash pacman pacman-mirrors msys2-runtime` to get it back.
Hope pacman got improved in this regard and it's more reliable from now on.

**Comment by mati865** [comment]
@White-Tiger `Pacman v4.2.1-516-g52073-dirty - libalpm v10.0.1` if most recent version of pacman. You had `Pacman v4.2.1-273-gfa50-dirty - libalpm v9.0.1` because you were downgrading pacman to restore `update-core` which was deprecated. If you are unsure if everything is ok you can force downloading latest database and updating/downgrading packages with `pacman -Syyuu`.
If everything is fine you will see this output:
```
pacman -Syyuu
:: Synchronising package databases...
 mingw32                  272.1 KiB   538K/s 00:01 [#####################] 100%
 mingw32.sig               96.0   B  0.00B/s 00:00 [#####################] 100%
 mingw64                  271.7 KiB   774K/s 00:00 [#####################] 100%
 mingw64.sig               96.0   B  0.00B/s 00:00 [#####################] 100%
 msys                     133.3 KiB  1269K/s 00:00 [#####################] 100%
 msys.sig                  96.0   B  0.00B/s 00:00 [#####################] 100%
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do
```

**Comment by White-Tiger** [comment]
I wasn't downgrading anything myself.. I've always been using update-core as "suggested" but it also deleted itself after every update... (before it got officially removed)
By running `pacman -S bash pacman pacman-mirrors msys2-runtime` I've simply forced a reinstall of all core components which was mostly needed to get `update-core` working again..

And yesterday, I've just run `update-core` and let it do its stuff, restarted MSYS2 (by clicking the close button) and then used `pacman -Syuu` which didn't touch any core files and only updated MinGW and other stuff.
After all that, I've been stuck at the old `Pacman v4.2.1-273-gfa50-dirty - libalpm v9.0.1`.
Running `pacman -S bash pacman pacman-mirrors msys2-runtime` just yields the usual errors
```
:: Processing package changes...
error: cannot remove /usr/bin/msys-2.0.dll (Permission denied)
(1/4) reinstalling msys2-runtime
warning: warning given when extracting /usr/bin/msys-2.0.dll (Could not unlink)
error: cannot remove /usr/bin/bash.exe (Permission denied)
(2/4) reinstalling bash
warning: warning given when extracting /usr/bin/bash.exe (Could not unlink)
(3/4) reinstalling pacman-mirrors
error: cannot remove /usr/bin/pacman.exe (Permission denied)
(4/4) reinstalling pacman
warning: warning given when extracting /usr/bin/pacman.exe (Could not unlink)
```
and to really update pacman, I had to run a copy of it, so it was able to replace the original

**Comment by elieux** [comment]
> the main page wasn't updated yet to reflect this change, however.. (the one most people will use/see) https://msys2.github.io/

Yes, we're waiting with that change until we release new installers. With the current installers, you have to run `update-core` at least once.

> is it normal to have `pacman -V` say [...]

It's a known issue. The internal version number doesn't correspond to the actual version.

> error: cannot remove /usr/bin/msys-2.0.dll (Permission denied)

This is wrong. The runtime should be able to replace files even though they're in use. Is your MSYS2 installed on a FAT volume or on a volume with the Windows *Recycle Bin* disabled?
