### ISSUE TITLE
Git problem

### ISSUE THREAD

**Issue by GFdevelop** [Alexpux/MSYS2-packages#526]
I have this error after i have run the configuration command:
`$ git commit -m "test"

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'Gabriele@Gabriele-PC.(none)')`

**Comment by mingwandroid** [comment]
This is not an MSYS2 problem. Please follow the instructions that git has prompted you with..
