### ISSUE TITLE
Fail to install gem for ruby 2.3.0

### ISSUE THREAD

**Issue by wrightsg** [Alexpux/MSYS2-packages#528]
I am not able to install gems for the latest MSYS2 ruby package which uses ruby 2.3.0 (installed after running pacman -S ruby in the MSYS shell).

Example

> gem install xml-simple

Results in the following error message

> /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- win32/resolv (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/resolv.rb:971:in `default_config_hash'
        from /usr/lib/ruby/2.3.0/resolv.rb:989:in `block in lazy_initialize'
        from /usr/lib/ruby/2.3.0/resolv.rb:982:in `synchronize'
        from /usr/lib/ruby/2.3.0/resolv.rb:982:in `lazy_initialize'
        from /usr/lib/ruby/2.3.0/resolv.rb:360:in `block in lazy_initialize'
        from /usr/lib/ruby/2.3.0/resolv.rb:358:in `synchronize'
        from /usr/lib/ruby/2.3.0/resolv.rb:358:in `lazy_initialize'
        from /usr/lib/ruby/2.3.0/resolv.rb:518:in `fetch_resource'
        from /usr/lib/ruby/2.3.0/resolv.rb:512:in `each_resource'
        from /usr/lib/ruby/2.3.0/resolv.rb:493:in `getresource'
        from /usr/lib/ruby/2.3.0/rubygems/remote_fetcher.rb:99:in `api_endpoint'
        from /usr/lib/ruby/2.3.0/rubygems/source.rb:47:in `api_uri'
        from /usr/lib/ruby/2.3.0/rubygems/source.rb:86:in `dependency_resolver_set'
        from /usr/lib/ruby/2.3.0/rubygems/resolver/best_set.rb:24:in `block in pick_sets'
        from /usr/lib/ruby/2.3.0/rubygems/source_list.rb:98:in `each'
        from /usr/lib/ruby/2.3.0/rubygems/source_list.rb:98:in `each_source'
        from /usr/lib/ruby/2.3.0/rubygems/resolver/best_set.rb:23:in `pick_sets'
        from /usr/lib/ruby/2.3.0/rubygems/resolver/best_set.rb:29:in `find_all'
        from /usr/lib/ruby/2.3.0/rubygems/resolver/installer_set.rb:152:in `find_all'
        from /usr/lib/ruby/2.3.0/rubygems/resolver/installer_set.rb:55:in `add_always_install'
        from /usr/lib/ruby/2.3.0/rubygems/dependency_installer.rb:474:in `resolve_dependencies'
        from /usr/lib/ruby/2.3.0/rubygems/commands/install_command.rb:239:in `install_gem'
        from /usr/lib/ruby/2.3.0/rubygems/commands/install_command.rb:300:in `block in install_gems'
        from /usr/lib/ruby/2.3.0/rubygems/commands/install_command.rb:296:in `each'
        from /usr/lib/ruby/2.3.0/rubygems/commands/install_command.rb:296:in `install_gems'
        from /usr/lib/ruby/2.3.0/rubygems/commands/install_command.rb:203:in `execute'
        from /usr/lib/ruby/2.3.0/rubygems/command.rb:308:in `invoke_with_build_args'
        from /usr/lib/ruby/2.3.0/rubygems/command_manager.rb:169:in `process_args'
        from /usr/lib/ruby/2.3.0/rubygems/command_manager.rb:139:in `run'
        from /usr/lib/ruby/2.3.0/rubygems/gem_runner.rb:55:in `run'
        from /usr/bin/gem:21:in `<main>'

~~The same happens when using the mingw32 shell/ruby.~~

These issues were not present in a different MSYS2 installation of mine which still uses the ruby package including ruby 2.1.5p273.

**Comment by mati865** [comment]
Looks like you have ruby 2.3.0-1, similar bug https://github.com/Alexpux/MSYS2-packages/issues/515
I cannot reproduce it using ruby 2.3.0-2 on fresh msys2
```
$ pacman -Ss ruby |grep msys
msys/ruby 2.3.0-2 [installed]
msys/ruby-docs 2.3.0-2

```
Use following commands:
```
pacman -Syyuu    #You might be asked to close shell after update, do it
pacman -Su
pacman -S ruby
```
And see if it is resolved.

**Comment by wrightsg** [comment]
This solved the problem, thank you!

I tried using the command you mentioned before, but without using "pacman -Syyuu".

It pacman -Su not sufficient to perform a system update?

**Comment by mati865** [comment]
`pacman -Sy` downloads packages database
`pacman -Syy` forces to download database, normally you don't need to use it, but when something goes wrong it's quite handy
`pacman -Su` updates packages using local database (which can be updated with `pacman -Sy`)
`pacman -Suu` updates packages using local database but allows downgrading (ex. 

> 1. There is xyz 1.0-1 package in repo
> 2. Package xyz 2.0-1 just landed in repo
> 3. You see xyz doesn't work after update and report it to the bugtracker,
> 4. Package xyz 1.0-1 is restored
> 5. `pacman -Su` won't downgrade because 2.0-1 > 1.0-1 so you must use `pacman -Suu' which will update/downgrade to lastest version in database)
As you can see it can be combined into 1 command like `pacman -Syyuu` or `pacman -Syuu`
`pacman -S <pkgname>'  install package <pkgname>

You should use `pacman -Syuu` when you want to update msys2.
