### ISSUE TITLE
after filesystem update cmd and msys shell are started

### ISSUE THREAD

**Issue by mati865** [Alexpux/MSYS2-packages#537]
On Windows 10 after updating filesystem shortcut from Menu Start (*shell.bat) opens cmd and msys shell
![msys2](https://cloud.githubusercontent.com/assets/1174646/14282107/27dcb094-fb3d-11e5-809d-9a2175072d96.png)

Reverting to `filesystem-2016.03-2` fixes issue.

**Comment by Karlson2k** [comment]
What happened if .bat file is started directly by Windows Run command (Win-R)?

**Comment by Karlson2k** [comment]
What happened if .bat file is started directly by Windows Run command (Win-R)?

**Comment by mati865** [comment]
When started from explorer or Windows Run it's fine.

**Comment by Karlson2k** [comment]
How did you create shortcut in Start Menu?

**Comment by Alexpux** [comment]
it created by installer

**Comment by Karlson2k** [comment]
I want to make sure that failed shortcut was created by installer.
This behavior comes from `exit /b`, which should works fine if .bat started correctly.

**Comment by mati865** [comment]
It was created by installer `msys2-x86_64-20150512.exe `.

**Comment by Karlson2k** [comment]
@mati865, thanks! Will check it in 4 hours, as soon as I'll get access to my dev machine.

**Comment by Karlson2k** [comment]
Something wrong with GitHub. Can create pull request for https://github.com/Alexpux/MSYS2-packages/compare/master...Karlson2k:install_fixes_01

**Comment by Karlson2k** [comment]
@mati865 Fix is coming. If you don't want to reinstall MSys2 with newer installer, just replace `/A /Q /K` switches with `/A /Q /C` (only one letter changed).

**Comment by mati865** [comment]
Issue resolved.
@Karlson2k thank you for fast fix.

**Comment by wuhanck** [comment]
I also meet this issue. I downgrade to filesystem-201603-2. It is fine. filesystem-201604-1 doesn't work.
The hot-fix is working but I am curious what change make the difference. 
Thanks

**Comment by mati865** [comment]
@wuhanck check this comment https://github.com/Alexpux/MSYS2-packages/issues/537#issuecomment-205987373

**Comment by wuhanck** [comment]
@mati865 Thanks. I have modify the shortcuts. I just want to know if it is a designed behavior between filesystem-201603-2 and filesystem-201604-1.

**Comment by mati865** [comment]
@wuhanck Best explanation: https://i.imgur.com/HTisMpC.jpg

**Comment by perlun** [comment]
Thanks! This fixed it for me. 👏
