### ISSUE TITLE
Starting Shell session leaves cmd.exe terminal running

### ISSUE THREAD

**Issue by ian-abbott** [Alexpux/MSYS2-packages#542]
Since `filesystem 2016.04-2` was installed, starting an MSYS2 Shell or a MingW-w64 Win{32,64} Shell session via the appropriate `.bat` file, leaves a `cmd.exe` terminal window running in addition to the mintty (or alternative) terminal window that runs the Bash shell.

It seems to be caused by the `exit /b %ERRORLEVEL%` commands in `start_shell.cmd` after the `start` commands that start the terminal session. Presumably, it has to wait for the started terminal session to exit in order to retrieve the `%ERRORLEVEL%` value.

Replacing the `exit /b %ERRORLEVEL%` commands that follow the `start` commands with a simple `exit` seems to fix the problem.

**Comment by elieux** [comment]
I've got `filesystem 2016.04-2`, but the command prompt window for `start_shell.cmd` disappears before the mintty window appears. Currently testing on Windows Server 2012 R2.

Are you running the file "as administrator"? Anything else that may account for the differing observations?

Does this happen to anyone else?

**Comment by mati865** [comment]
https://github.com/Alexpux/MSYS2-packages/issues/537

**Comment by ian-abbott** [comment]
Thanks for the hint, @mati865. Closing as a dupe.
