### ISSUE TITLE
Shortcuts spawn persistent cmd.exe for every terminal

### ISSUE THREAD

**Issue by melak47** [Alexpux/MSYS2-packages#543]
The installed shortcuts for the different shells all do something like:
`C:\Windows\System32\cmd.exe /A /Q /K C:\msys64\msys2_shell.bat`

Recently, these batch files seem to have been refactored into a shared `start_shell.cmd`, 
but there also seems to have been a change in behavior, since now the same shortcuts spawn a persistent cmd window.
This happened when I followed the setup instructions, which upgraded mintty to `mintty-1~2.2.3-1`.

I simply changed my shortcuts to use `/C` instead:

> /C      Carries out the command specified by string and then terminates
> /K      Carries out the command specified by string but remains

**Comment by mati865** [comment]
Duplicate https://github.com/Alexpux/MSYS2-packages/issues/537 https://github.com/Alexpux/MSYS2-packages/issues/542

**Comment by melak47** [comment]
@mati865 When will a new installer that includes the fix be published? Until then, doing an upgrade is going to break this for everyone...

**Comment by mati865** [comment]
I don't know ask @Alexpux .
