### ISSUE TITLE
jsoncpp install dir

### ISSUE THREAD

**Issue by EchoOfSoul** [Alexpux/MSYS2-packages#548]
install with pacman -S jsoncpp
`"include"` directory not under `"/usr"`
how to make it under `"/usr"` not in `"/"` ?

`/include/jsoncpp`
should be
`/usr/include/jsoncpp`

**Comment by Alexpux** [comment]
Need fix build system for jsoncpp seems

**Comment by EchoOfSoul** [comment]
try with
`-DCMAKE_INSTALL_PREFIX=/usr`
`-DINCLUDE_INSTALL_DIR=/usr/include`
`-DLIBRARY_INSTALL_DIR=/usr/lib`
>-- Install configuration: "release"
-- Installing: /usr/lib/pkgconfig/jsoncpp.pc
-- Installing: /usr/lib/cmake/jsoncpp/jsoncppConfig.cmake
-- Installing: /usr/lib/cmake/jsoncpp/jsoncppConfig-release.cmake
-- Installing: /home/x/xx/jsoncpp-1.7.2/build-i686/libjsoncpp.dll.a
-- Installing: /usr/bin/msys-jsoncpp-1.dll
-- Installing: /home/x/xx/jsoncpp-1.7.2/build-i686/libjsoncpp.a
-- Installing: /usr/include/json/allocator.h
-- Installing: /usr/include/json/assertions.h
-- Installing: /usr/include/json/autolink.h
-- Installing: /usr/include/json/config.h
-- Installing: /usr/include/json/features.h
-- Installing: /usr/include/json/forwards.h
-- Installing: /usr/include/json/json.h
-- Installing: /usr/include/json/reader.h
-- Installing: /usr/include/json/value.h
-- Installing: /usr/include/json/version.h
-- Installing: /usr/include/json/writer.h

unfortunately it's like forcing path `/usr` not using variable `${var}`
like `-DCMAKE_INSTALL_PREFIX="${pkgdir}"`

**Comment by Alexpux** [comment]
No. Completely wrong. Going to fix it myself

**Comment by EchoOfSoul** [comment]
ok, thanks
