### ISSUE TITLE
broken path after filesystem package update 

### ISSUE THREAD

**Issue by malaguna** [Alexpux/MSYS2-packages#552]
After upgrade, using `pacman -Syu` msys2 does not recognize windows path and I can't invoke programs defined in user path. Also, `mingw-w64 win 64 shell` does not close windows command prompt as it used to do, now both windows (mintty and windows cmd) remains open.

I am using Windows 10, and filesystem package version is `filesystem-2016.04-3`.

**Comment by Alexpux** [comment]
Open bat file in notepad and see commented lines.

**Comment by malaguna** [comment]
Thanks, now it recognizes well windows path, but windows cmd remains open.

**Comment by Alexpux** [comment]
This is describes in other github issue. In short you need modify properties of shortcut replacing "/K" switch with "/C"

**Comment by malaguna** [comment]
Thank you very much!
