### ISSUE TITLE
Command prompt does not close automatically after `pacman -Su`

### ISSUE THREAD

**Issue by tomty89** [Alexpux/MSYS2-packages#559]
I just did a fresh installation with msys2-x86_64-20160205.exe, ran update-core and pacman -Su. After pacman -Su, the command prompt no longer close automatically, though closing it manually does not close the msys shell:
<img src="https://ptpb.pw/3pNK.PNG" />
<img src="https://ptpb.pw/shSE.PNG" />

**Comment by mati865** [comment]
https://github.com/Alexpux/MSYS2-packages/issues/537
