### ISSUE TITLE
pacman -V shows wrong version

### ISSUE THREAD

**Issue by elieux** [Alexpux/MSYS2-packages#566]
#524 and https://sourceforge.net/p/msys2/mailman/message/34976975/ and possibly others reported this. The problem is probably with the git merges where `git describe --abbrev=4 --dirty | sed **s/^v//` from `Makefile.am` files doesn't show the right tag.

**Comment by Alexpux** [comment]
It fixed by https://github.com/Alexpux/MSYS2-packages/commit/4540b609ed1c5c7d071bca7acf60f2255bca0a74
Wait new commits to repo to rebuild pacman

**Comment by Alexpux** [comment]
Today new pacman uploaded builded with stable release

**Comment by elieux** [comment]
Verified. Thanks, Alexey.

For visitors: you'll need to use `pacman -Syuu` to install the correct version.
