### ISSUE TITLE
Qt-static wrong dependencies?

### ISSUE THREAD

**Issue by JDarthenay** [Alexpux/MSYS2-packages#572]
Trying to see how works the Qt installer framework, I read I had to use a static build of Qt. I was happy to see there is one in MSYS2 packages.

So I decided to install mingw64/mingw-w64-x86_64-qt5-static. It comes with its dependency mingw64/mingw-w64-x86_64-qtbinpatcher.

I found a small Qt program example on the web and tried to build it (QtHello.cpp). I ran qmake, then mingw32-make, compiling was unsuccessful. I realized some headers were not directly in headers directory but in a sub-folder "widgets" searched on the web, found that I had to add "QT += widgets" in project file QtHello.pro, ran qmake and mingw32-make again, and now I have linking errors:
>D:/Prog/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -ldbus-1
>D:/Prog/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -ljasper
>D:/Prog/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lwebp
>D:/Prog/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lsicuind
>D:/Prog/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lsicuucd
>D:/Prog/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lsicudtd
>Makefile.Debug:64: recipe for target 'debug\QtHello.exe' failed

I have searched in hard drive, I have no libdbus.a. Someone told me in MSYS2 mailing list those files are included in the dynamic Qt build.

Also there is a weird path in the -L options of the generated Makefile.release and Makefile.debug. My MSYS2 is installed in "D:\Prog\msys64" so I don't know the hell where those "-LC:\building\msys64\mingw64\lib" come from.

So now, I am wondering. Have I done something wrong? Shouldn't those lib*.a files be present in Qt-static package or in one of its dependencies? Do I need to install 5Gb packages more to be able to use the static Qt package?

As an attachment I provide my QtHello project files.
[QtHello.zip](https://github.com/Alexpux/MSYS2-packages/files/235046/QtHello.zip)

**Comment by mati865** [comment]
I've just added your files to Qt Creator and compiled it both shared and static.
Here is static 64-bit build: [QtHello.zip](https://github.com/Alexpux/MSYS2-packages/files/235081/QtHello.zip)

**Comment by JDarthenay** [comment]
Well, thanks, that should prove the Hello World source I grabbed was fine, but I fear you did not understand my three questions.

**Comment by Alexpux** [comment]
Wrong repository for this issue

**Comment by JDarthenay** [comment]
I don't understand. Why did you close this Issue? Why isn't it the good repository?

**Comment by Alexpux** [comment]
Because Qt5 is is from MINGW-packages not MSYS2-packages
