### ISSUE TITLE
32bits g++ -static is broken

### ISSUE THREAD

**Issue by JDarthenay** [Alexpux/MSYS2-packages#576]
Hello

I try to build a program both in 32-bits with mingw32\bin\g++.exe and in 64-bits with mingw64\bin\g++.exe using options "-static -static-libgcc -static-libstdc++". The 64-bits executable runs perfectly, while the 32-bits executable keeps requiring libgcc_s_dw2-1.dll to run. Also I don't understand why I have a libgcc_s_dw2-1.dll only in folder msys64\mingw32\bin and not in folder msys64\mingw64\bin.

Please repair.

Regards,

**Comment by elieux** [comment]
The 32-bit and 64-bit versions differ in exception handling, 32-bit uses DW2, 64-bit uses SEH. `libgcc_s_dw2-1.dll` is related to DW2 and therefore not part of the 64-bit mingw-w64 gcc.

I just wanted to clarify. I'll leave the bug itself to someone else (or to some other time).

**Comment by JDarthenay** [comment]
This name confuses me: is that DLL necessary for C programs only? I mean I built a pure C DLL without "-static", could it be because linking with it I have this problem?

**Comment by mati865** [comment]
GCC is "C" compiler, G++ is "C++" compiler so I don't know why it's name would confuse you.
Both C and C++ 32-bit programs use DW2.

**Comment by JDarthenay** [comment]
My apologies! And thanks for answering me.
It seems this time the bug was, as we often say, between the chair ans the screen. So, after rebuilding correctly SDL_gfx.dll I could get rid of this nasty dll dependency.
Issue solved.
