### ISSUE TITLE
 filesystem-2016.05-2  broken

### ISSUE THREAD

**Issue by wuhanck** [Alexpux/MSYS2-packages#623]
After upgrade to filesystem-2016.05-2, msys2 get broken.
I can not open the shell.
Then I use fresh-new-installation-of-msys2-x86_64-20160205, the same result.

**Comment by fracting** [comment]
@wuhanck What Windows version are you testing?

Are you able to start a cmd, cd to the directory of msys2, and manually run `usr/bin/mintty.exe --exec /usr/bin/bash -l`?

**Comment by mati865** [comment]
@wuhanck Have you modified shortcuts as you were asked to?
Here on Win 10 x64 everything is ok.

**Comment by wuhanck** [comment]
@fracting 
usr/bin/mitty.exe --exec /usr/bin/bash -l
doesn't work. Path error.

But
usr\bin\mintty.exe --exec /usr/bin/bash -l
DO WORK.

@mati865 
On Win 10 x86_64 too.

**Comment by wuhanck** [comment]
@mati865 
I modified the shortcuts and the shell just flash and disappear.
It looks like some path issue. \ or / or someting else?

**Comment by mati865** [comment]
@wuhanck 
Use Windows paths in shortcuts.
```
Target: "D:\msys64\msys2_shell.cmd -msys

Start in "D:\msys64\
```

**Comment by wuhanck** [comment]
@mati865 
I think the orginal shortcut parameter is more reasonable.
When something goes wrong, there is at least one shell remaining. The modified one will get some quick flash...
I have degraded to filesystem-2016-03-2 and everything is OK.
I won't change the shortcut parameters to workaround it now. I think it is OK to just be with filesystem-2016-03-2.

**Comment by dimztimz** [comment]
There should be a way the update procedure to update the shortcuts too. I only saw a message to close the terminal windows. To solve the issue I had to manually snoop around (I remembered there was a shortcut bug previously with cmd.exe /K and /C mixed up).

**Comment by wuhanck** [comment]
I update filesystem. And find out the kind prompts.
It works.
Thx, guys. @mati865
