### ISSUE TITLE
The installer needs updated (pacman update causes links to be broken)

### ISSUE THREAD

**Issue by malignantmanor** [Alexpux/MSYS2-packages#625]
The links in the start menu link to msys2_shell.bat which gets deleted in the update. The new shortcuts for the 64 bit version seem to be
msys2_shell.cmd -mingw32
msys2_shell.cmd -mingw64
msys2_shell.cmd -msys

**Comment by mati865** [comment]
Would you like to try new installer https://msys2.github.io?

**Comment by malignantmanor** [comment]
Thanks. I only tried the 64-bit installer. It had the correct shortcuts.

**Comment by mati865** [comment]
Unfortunately new installer introduces new issue.
You have to manually create mingw32 and mingw64 dirs in /msys64 or add --force to pacman when installing first i686 or x86_64 mingw package.
