### ISSUE TITLE
Current installer/installation instructions are broken

### ISSUE THREAD

**Issue by NathanDunfield** [Alexpux/MSYS2-packages#633]
Following the instructions at http://msys2.github.io/ on a clean Windows 10 machine, I got the following error after completing Step 6 and trying to bring up a MSYS2 window via the Start menu:

'C:\msys64\msys2_shell.bat' is not recognized as an internal or external command,
operable program or batch file.

I believe this is likely caused by commit 2c4e6d7289 and that a new binary installer needs to be made to fix this.

**Comment by huhlig** [comment]
Steps to reproduce.
1. Download http://repo.msys2.org/distrib/x86_64/msys2-x86_64-20160205.exe
2. Run previously downloaded file
3. Run pacman -Syuu
4. Profit?

**Comment by dimkanewtown** [comment]
Any workaround available?

**Comment by DavidEGrayson** [comment]
@dimkanewtown Please see the warning printed by the filesystem package when it is upgraded.  You can see the warning here:

https://github.com/Alexpux/MSYS2-packages/blob/master/filesystem/filesystem.install

The warning says:

>      WARNING: the shell starting scripts have been unified. Please update your
>      shortcuts to the following targets, otherwise they will STOP WORKING:
>
>          * MSYS2_ROOT\msys2_shell.cmd -mingw32
>          * MSYS2_ROOT\msys2_shell.cmd -mingw64
>          * MSYS2_ROOT\msys2_shell.cmd -msys\n\n'

**Comment by dimkanewtown** [comment]
Yep, should've been reading onscreen messages more closely. Thanks!

**Comment by mati865** [comment]
Would you like to try new installer https://msys2.github.io?

**Comment by NathanDunfield** [comment]
I tried out the new installer and it completely fixes this issue.  Closing ticket.

**Comment by mati865** [comment]
Unfortunately new installer introduces new issue.
You have to manually create `mingw32` and `mingw64` dirs in `/msys64` or add `--force` to pacman when installing first `i686` or `x86_64` mingw package.

**Comment by elieux** [comment]
@mati865, is it due to this issue? elieux/msys2-launcher#1

**Comment by mati865** [comment]
@elieux, @Alexpux probably fixed it already https://github.com/Alexpux/MSYS2-packages/commit/730cd21da93909393fadaba51b05150e0f672e1b but he cannot release new installer until he returns.
