### ISSUE TITLE
Request package: argp

### ISSUE THREAD

**Issue by myd7349** [Alexpux/MSYS2-packages#643]
Hello, everyone! How can I install `argp` package?

Neither
>pacman -S libargp

nor

> pacman -S argp

works.

Any idea?
Thanks!

**Comment by DavidEGrayson** [comment]
argp is part of the [GNU C library](https://www.gnu.org/software/libc/manual/html_node/Argp.html) and for systems that don't have it, you can get it as a module in [gnulib](https://www.gnu.org/software/gnulib/MODULES.html#module=argp).  I think you'll need to use gnulib if you want argp on MSYS2.

**Comment by myd7349** [comment]
@DavidEGrayson Thanks for your kind help. The standalone implementation of argp really helps. I also found a replacement of `gnulib`'s libargp early this day on GitHub: [portable libargp](https://github.com/alexreg/libargp).

I have already tried
>pacman -S gnulib

>pacman -S mingw-w64-i686-gnulib

None of them work, however.

**Comment by DavidEGrayson** [comment]
gnulib is not designed to be distributed in a package manager.

**Comment by myd7349** [comment]
@DavidEGrayson Thanks! :smile:
