### ISSUE TITLE
Bash update 4.3.046 breaks PS1 environment variable

### ISSUE THREAD

**Issue by ukhf-jm** [Alexpux/MSYS2-packages#653]
After updating bash, user's prompt is set to `PS1=\s-\v\$` whereas previously it was set to `PS1="\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[35m\]$MSYSTEM\[\e[0m\] \[\e[33m\]\w\[\e[0m\]\n\$"`.
Fairly easy to fix if you know where to look although new users may struggle.

What else may have been affected by the update?
Compiling in the Win64 MinGW-w64 shell appears to still work fine but it's not clear what files the bash update changed and how they changed.
Would this have broken prompts for people who had customised theirs?

**Comment by ukhf-jm** [comment]
Also, workaround to get prompt back to how it was is to add:
```
export PS1="\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[35m\]$MSYSTEM\[\e[0m\] \[\e[33m\]\w\[\e[0m\]\n\$"
```
to the end of your .bashrc file. This is found at C:\msys64\home\[username] assuming you installed the 64bit version in the default directory.

**Comment by ukhf-jm** [comment]
So, there was a change in /etc/bash.bashrc where this:
```
# Set a default prompt of: user@host, MSYSTEM variable, and current_directory
PS1='\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[35m\]$MSYSTEM\[\e[0m\] \[\e[33m\]\w\[\e[0m\]\n\$ '
```
was changed to this:
```
# Warnings
unset _warning_found
for _warning_prefix in '' ${MINGW_PREFIX}; do
    for _warning_file in ${_warning_prefix}/etc/profile.d/*.warning{.once,}; do
        test -f "${_warning_file}" || continue
        _warning="$(command sed 's/^/\t\t/' "${_warning_file}" 2>/dev/null)"
        if test -n "${_warning}"; then
            if test -z "${_warning_found}"; then
                _warning_found='true'
                echo
            fi
            if test -t 1
                then printf "\t\e[1;33mwarning:\e[0m\n${_warning}\n\n"
                else printf "\twarning:\n${_warning}\n\n"
            fi
        fi
        [[ "${_warning_file}" = *.once ]] && rm -f "${_warning_file}"
    done
done
unset _warning_found
unset _warning_prefix
unset _warning_file
unset _warning

# If MSYS2_PS1 is set, use that as default PS1;
# if a PS1 is already set, use that;
# otherwise set a default prompt
# of user@host, MSYSTEM variable, and current_directory
if test -n "${MSYS2_PS1}"
    then PS1="${MSYS2_PS1}"
    elif test -z "${PS1}"
        then PS1='\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[35m\]$MSYSTEM\[\e[0m\] \[\e[33m\]\w\[\e[0m\]\n\$ '
fi
```

**Comment by PhilipOakley** [comment]
@ukhf-jm Thank you for the analysis. I authoured the minor fix #651  to a previous fix that broke the Git for Windows SDK's bash title bar settings part of the PS1. (more details on that link)

Any input on putting together a proper fix that covers typical user settings would be gratefully recieved (I'm an engineer who mainly works on Windows so the fine details of bash set ups is not something I normally deal with ;-)

**Comment by yuriks** [comment]
I'm also affected by this. It seems like this change was originally made to support Git4Windows settings its own PS1. However, where was that previous prompt set from? It shouldn't be possible for anything to run before the system-wide profile files. Is Git for Windows setting the PS1 via an exported environment variable?

**Comment by PhilipOakley** [comment]
@yuriks, No (original==G4W?). This (my small #651) change was because the previous patch 6e6310d had broken the G4W SDK. These two commits must be taken as a pair, and each of the different backstories surfaced and considered, including @renatosilva's original rationale (the logic back then may have been incomplete).

**Comment by ukhf-jm** [comment]
Just tried a fresh install again and can confirm prompt is as expected after updating bash. Thank you @Alexpux , @Karlson2k and @PhilipOakley

**Comment by Karlson2k** [comment]
@ukhf-jm Thanks for report!
