### ISSUE TITLE
pacman 5.0.1-1 is considered older than previous release

### ISSUE THREAD

**Issue by FraGag** [Alexpux/MSYS2-packages#655]
Commit 46945ff878ab550c0ecf0203fe41466625ab9e3e changed the package version from `5.0.1.6416.4ee6fd4-1` to `5.0.1-1`. `5.0.1-1` is considered older than `5.0.1.6416.4ee6fd4-1`, so pacman doesn't propose installing that version when performing a system upgrade. My local version is `5.0.1.6403.520736d-1`, which exhibits the problem, though I believe `5.0.1.6416.4ee6fd4-1` would as well.

```
:: Starting core system upgrade...
warning: pacman: local (5.0.1.6403.520736d-1) is newer than msys (5.0.1-1)
warning: terminate other MSYS2 programs before proceeding
resolving dependencies...
looking for conflicting packages...

Packages (3) filesystem-2016.07-1  msys2-runtime-2.5.2-2  msys2-runtime-devel-2.5.2-2

Total Download Size:    5.80 MiB
Total Installed Size:  29.58 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n]
```

**Comment by elieux** [comment]
Did you find #566 when you were looking for reported issues? It mentions both the solution and reasons for this.

Generally speaking: Sometimes the package versions in the binary repositories are decremented. The recommended system update command for newer installations is `pacman -Syuu`, as per [our updating instructions](https://sourceforge.net/p/msys2/wiki/MSYS2%20installation/), which will also enable downgrades.

**Comment by FraGag** [comment]
On Arch Linux, when a package is downgraded in one of the main repos (core, extra, community), or when the version changes in a way that would be considered older by pacman's version comparison rules, the epoch is also incremented so that users don't have to do `pacman -Syuu`. This happened, for instance, with `wpa_supplicant`, [which was rolled back from 2.4 to 2.3](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/wpa_supplicant&id=7562b98bd83fe5bce43e6952e0e922e7791e18b5).

Arch Linux recommends using `pacman -Syu`, not `pacman -Syuu` to perform a system upgrade. Shouldn't MSYS2 work the same way?
