### ISSUE TITLE
Cannot install git - Perl packages generate errors that each file already "exists in filesystem"

### ISSUE THREAD

**Issue by db0451** [Alexpux/MSYS2-packages#678]
I am trying to install git so that I can clone the gtkmm sources and rebuild my own DLLs, until the packages are updated for GCC 6.1, as currently I get the error that DllMain is not found in libgtkmm and libgdkmm DLLs

however when I try to install msys2/git I am blocked by all of the errors in the attached txt file. Apparently the dependency Perl packages are trying to overwrite files that already exist, and Pacman will not let them.

I don't care if files are overwritten, as long as Perl does what it needs to do in the background. So is there a way to force the installation to continue? Or does this indicate something else broken about my installation?

thanks

[git.txt](https://github.com/Alexpux/MSYS2-packages/files/456540/git.txt)

**Comment by Alexpux** [comment]
Seems you have broken installation or you have installed this files yourself in system.
Pass "--force" to pacman to solve this

**Comment by db0451** [comment]
Thank you! I didn't know about --force. It's installed now :-)
