### ISSUE TITLE
can't run msys2_shell.cmd on xp: CancelSynchronousIo could not be located

### ISSUE THREAD

**Issue by brunoqc** [Alexpux/MSYS2-packages#687]
Win XP 32-bit.

The procedure entry point CancelSynchronousIo could not be located in the dynamic link library KERNEL32.dll

![image](https://cloud.githubusercontent.com/assets/24027/18750480/410a732a-80a9-11e6-8556-583b640909bc.png)

I installed using msys2-base-i686-20160921.tar.xz. The installer from https://msys2.github.io/ doesn't work (I get the same CancelSynchronousIo error during the installation).

**Comment by Alexpux** [comment]
Recent MSYS2 do not support Win XP anymore

**Comment by brunoqc** [comment]
Thanks.

**Comment by mati865** [comment]
@brunoqc, recent Cygwin update dropped Win XP support, and MSYS2 has no option but follow it.

@Alexpux, I think it would be good idea to put big warning at https://msys2.github.io.

**Comment by brunoqc** [comment]
@mati865, it's nice to know cygwin is also affected. Thanks!

A warning would be nice.
