### ISSUE TITLE
aspell fails to install

### ISSUE THREAD

**Issue by sheijk** [Alexpux/MSYS2-packages#689]
I'm seeing errors when installing aspell. I did the following steps

1. Install msys32
2. Update pacman as the instructions at https://msys2.github.io/ say (pacman -Sy; pacman -Syu; pacman -Su)
3. Tried to install aspell using `pacman -S mingw32/mingw-w64-i686-aspell`

Installation fails with the following output:

```
$ pacman -S mingw32/mingw-w64-i686-aspell
resolving dependencies...
looking for conflicting packages...
warning: dependency cycle detected:
warning: mingw-w64-i686-gcc-libgfortran will be installed before its mingw-w64-i686-gcc-libs dependency

Packages (8) mingw-w64-i686-expat-2.2.0-1  mingw-w64-i686-gcc-libgfortran-6.2.0-2
             mingw-w64-i686-gcc-libs-6.2.0-2  mingw-w64-i686-gettext-0.19.7-1
             mingw-w64-i686-gmp-6.1.1-1  mingw-w64-i686-libiconv-1.14-5
             mingw-w64-i686-libwinpthread-git-5.0.0.4733.ae160b2-1
             mingw-w64-i686-aspell-0.60.7.20131207-2

Total Download Size:    5.93 MiB
Total Installed Size:  31.97 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 mingw-w64-i686-gmp-6.1.1-1-any   470.3 KiB   230K/s 00:02 [##############################] 100%
 mingw-w64-i686-libwinpthrea...    37.9 KiB   164K/s 00:00 [##############################] 100%
 mingw-w64-i686-gcc-libgfort...   272.5 KiB   282K/s 00:01 [##############################] 100%
 mingw-w64-i686-gcc-libs-6.2...   627.6 KiB   291K/s 00:02 [##############################] 100%
 mingw-w64-i686-libiconv-1.1...   602.2 KiB   233K/s 00:03 [##############################] 100%
 mingw-w64-i686-expat-2.2.0-...   120.5 KiB   420K/s 00:00 [##############################] 100%
 mingw-w64-i686-gettext-0.19...     3.1 MiB   234K/s 00:14 [##############################] 100%
 mingw-w64-i686-aspell-0.60....   746.3 KiB   232K/s 00:03 [##############################] 100%
(8/8) checking keys in keyring                             [##############################] 100%
(8/8) checking package integrity                           [##############################] 100%
(8/8) loading package files                                [##############################] 100%
(8/8) checking for file conflicts                          [##############################] 100%
error: failed to commit transaction (conflicting files)
mingw-w64-i686-gmp: /mingw32 exists in filesystem
mingw-w64-i686-libwinpthread-git: /mingw32 exists in filesystem
mingw-w64-i686-gcc-libgfortran: /mingw32 exists in filesystem
mingw-w64-i686-gcc-libs: /mingw32 exists in filesystem
mingw-w64-i686-libiconv: /mingw32 exists in filesystem
mingw-w64-i686-expat: /mingw32 exists in filesystem
mingw-w64-i686-gettext: /mingw32 exists in filesystem
mingw-w64-i686-aspell: /mingw32 exists in filesystem
Errors occurred, no packages were upgraded.
```
I'm getting similar issues with msys64, only that the path and package names are slightly different (as expected)

**Comment by sheijk** [comment]
System is a Windows 10 64-bit with anniversary update

**Comment by mati865** [comment]
It's a bug with new installer.
When installing first mingw32 or mingw64 package you have to use `pacman -S --force <package_name>` to create `/mingw32` directory.
After that you can install packages without issues.

**Comment by sheijk** [comment]
This worked, thanks a lot!

**Comment by avih** [comment]
> It's a bug with new installer.

While the solution is simple, the bug is quite bad for unsuspecting users.

I just installed and removed msys2 few times before suspecting something might broken with msys2 itself (also having to kill a stray `pacman.exe` process before being able to uninstall - which closing the terminal when it instructed me to did not do).

If fixing this bug is hard, I'd suggest to at least adding a red bold comment at the download page ( http://msys2.github.io/ ) about this issue and its solution.

**Comment by Alexpux** [comment]
Bug is already fixed. New installers will be in few days.

**Comment by moura464** [comment]
@sheijk 
$ pacman -S mingw32/mingw-w64-i686-aspell
resolvendo dependências...
procurando por pacotes conflitantes...

Pacotes (9) mingw-w64-i686-expat-2.2.3-1  mingw-w64-i686-gcc-libs-7.2.0-1
            mingw-w64-i686-gettext-0.19.8.1-2  mingw-w64-i686-gmp-6.1.2-1
            mingw-w64-i686-libiconv-1.15-1
            mingw-w64-i686-libwinpthread-git-5.0.0.4850.d1662dc7-1
            mingw-w64-i686-mpc-1.0.3-2  mingw-w64-i686-mpfr-3.1.5.p10-1
            mingw-w64-i686-aspell-0.60.7.20131207-3

Tamanho total download:    6,03 MiB
Tamanho total instalado:  31,87 MiB

:: Continuar a instalação? [S/n] S
:: Obtendo pacotes...
 mingw-w64-i686-gmp-...   471,7 KiB   289K/s 00:02 [#####################] 100%
 mingw-w64-i686-mpfr...   272,5 KiB   280K/s 00:01 [#####################] 100%
 mingw-w64-i686-mpc-...    62,3 KiB  46,9K/s 00:01 [#####################] 100%
 mingw-w64-i686-libw...    40,8 KiB  76,2K/s 00:01 [#####################] 100%
 mingw-w64-i686-gcc-...   632,9 KiB   319K/s 00:02 [#####################] 100%
 mingw-w64-i686-libi...   615,9 KiB   318K/s 00:02 [#####################] 100%
 mingw-w64-i686-expa...   130,4 KiB   227K/s 00:01 [#####################] 100%
 mingw-w64-i686-gett...     3,1 MiB   484K/s 00:07 [#####################] 100%
 mingw-w64-i686-aspe...   742,5 KiB   336K/s 00:02 [#####################] 100%
(9/9) verificando chaves no chaveiro               [#####################] 100%
(9/9) verificando integridade do pacote            [#####################] 100%
(9/9) carregando arquivos do pacote                [#####################] 100%
(9/9) verificando conflitos de arquivo             [#####################] 100%
(9/9) verificando espaço em disco disponível       [#####################] 100%
:: Processando alterações do pacote...
(1/9) instalando mingw-w64-i686-gmp                [#####################] 100%
(2/9) instalando mingw-w64-i686-mpfr               [#####################] 100%
(3/9) instalando mingw-w64-i686-mpc                [#####################] 100%
(4/9) instalando mingw-w64-i686-libwinpthread-git  [#####################] 100%
(5/9) instalando mingw-w64-i686-gcc-libs           [#####################] 100%
(6/9) instalando mingw-w64-i686-libiconv           [#####################] 100%
(7/9) instalando mingw-w64-i686-expat              [#####################] 100%
(8/9) instalando mingw-w64-i686-gettext            [#####################] 100%
(9/9) instalando mingw-w64-i686-aspell             [#####################] 100%
