### ISSUE TITLE
msys2 unusable in Windows 10 x64 insider build 14931

### ISSUE THREAD

**Issue by ncihnegn** [Alexpux/MSYS2-packages#690]
Keep getting errors like

> paste.exe: **\* fatal error - cygheap base mismatch detected - 0x180326400/0x1186400.
> But not every process.

Reinstall, downgrade to msys2-base-x86_64-20160205, it doesn't get better.
But msys2 runs fine on a different copy of Windows 10 with stable build on the same machine.

I know this is low priority since it is a prerelease build of Windows.
So I would appreciate if there are some guidance for me to look into this myself.
Thanks.

**Comment by legends2k** [comment]
I second this, I'm affected by this too.

**Comment by mati865** [comment]
Probably Cygwin bug.
You can try Cygwin, if it works then it's MSYS2 issue.

**Comment by ncihnegn** [comment]
Just tested Cygwin, it is broken, too.
So this is an upstream issue.

**Comment by mati865** [comment]
So you can close this issue and report it to Cygwin.

**Comment by tkelman** [comment]
No one on the cygwin list is being very helpful on this. We can try reporting it to msft and see if they care that they broke cygwin.

**Comment by mingwandroid** [comment]
Considering they employ @dscho, and Git for Windows is based on MSYS2, one would hope they care a little!

**Comment by tkelman** [comment]
Ah did not know @dscho worked there. I haven't tested to see if the standalone git for windows is also broken, I usually use cygwin's git (which is having intermittent failures, but is not as frequently as make and cmake). But it would be best to escalate this to someone in the right team before this goes out as a mass deployment update to everyone. Here's the stalled cygwin thread if you have any ideas how to debug these fork issues http://cygwin.1069669.n5.nabble.com/Advice-for-debugging-heap-mismatches-Win10-Insider-build-14926-td129984.html

**Comment by ncihnegn** [comment]
It seems Build 14946 fixes this.

**Comment by dscho** [comment]
@ncihnegn thanks for testing!

**Comment by tkelman** [comment]
Can confirm 14946 has not exhibited the issue.

**Comment by Patlamgoc** [comment]
Please check another possibly related issue of mine, and mind your antiviruses ;)

https://github.com/jb-alvarado/media-autobuild_suite/issues/402

**Comment by tkelman** [comment]
That's already on a well-established list of software known to cause issues with Cygwin (and derivatives like MSYS2 using the same basic posix emulation layer and fork implementation) - https://cygwin.com/faq/faq.html#faq.using.bloda

Note that BLODA interactions are not necessarily version-of-Windows dependent, whereas this particular issue clearly started happening to me the very first time I tried to run `make` or `cmake` in Cygwin after I updated from Windows 10 Insider build 14915 to build 14926, and persisted until I updated to build 14946 after which it has not happened again on otherwise-the-same system.

**Comment by Patlamgoc** [comment]
I am not an expert but even restarting the machine can sometimes help as DLL and/or EXE base reallocations are less likely on a freshly started environment. May a fresh installation have also helped a tidier memory and increased your mileage? I deeply suspect security related applications also.

**Comment by tkelman** [comment]
I have my cygwin install on an exception list for every antivirus I've ever used. A more recent thread on the cygwin mailing list suggests repeated loading/unloading of dlls was resulting in unexpected behavior that cygwin flagged, so it was likely a bug in Windows itself. Hopefully a temporary one given it only appeared on a range of insider builds, and unless it comes back we don't really need to worry about it any more.

**Comment by Patlamgoc** [comment]
Yes, in fact I've had no problems with AVG and Panda even I've not excluded cygwin family but if you've chekched my original issue, it seems Avira is doing aggressive things like sandboxing everything at first place and think afterwards even they're excluded in all ways, even disabling the realtime protection completely doesn't  help :) I think they tried to be very near to kernel to increase detection rate but in some cases it backfires badly.

AFAIU, native Windows code generally does not complain of BASE changes but *nix implementations break often.

I'll also upgrade my 14931 ASAP whenever it appears in my language, probably in few days, and will see what happens. I'll report back if I find something remarkable.

**Comment by Patlamgoc** [comment]
Ok, I confirm 14946 solved my issues also, it seems antivirus just causes the problem to surface in my case.

**Comment by Karna829** [comment]
msys2 installer does not run on my windows 10 x64 "msys2-i686-20180531.exe" , I even tried "msys2-x86_64-20180531.exe" .Please do the needful
