### ISSUE TITLE
git package is broken (msys/git 2.9.1-1)

### ISSUE THREAD

**Issue by jibaer** [Alexpux/MSYS2-packages#692]
The git package is broken. In the tar there are many symlinks that can no be created on win. So the installed git is unusable.

**Comment by Alexpux** [comment]
As I remember broken links only for MAN files. Other is ok.

**Comment by jibaer** [comment]
Even the links for all the exe-files are broken...

**Comment by Alexpux** [comment]
It can be broken if you unpack it with windows utils. If you use msys utilities - it unpack it correctly.

**Comment by jibaer** [comment]
i did the install with pacman, and got many errors. And yes i've done it on external disk with FAT. If the FAT-fs is a problem then there should be a note about this... At this moment some packages work, and other doesnt.

**Comment by Alexpux** [comment]
MSYS2 not work on FAT partitions properly because packages have hadlinks for files that not supported on FAT fs.

**Comment by lazka** [comment]
msys2.org currently states "MSYS2 can't be installed on FAT* partitions.", so I guess this is solved.
