### ISSUE TITLE
gnulib find "sys/time.h and signal.h" from cygwin patch

### ISSUE THREAD

**Issue by ghost** [Alexpux/MSYS2-packages#697]
these packages "coreutils, gettext, gnutls, inetutils, lftp, libpipeline, man-db, wget" add this patch "[0.19.7-gnulib-cygwin25.patch](https://gitweb.gentoo.org/repo/proj/prefix.git/diff/sys-devel/gettext/files/0.19.7-gnulib-cygwin25.patch?id2=405d661f15dd4f47a4bb3659d2904f28ed72eb56&context=40&ignorews=1)" gettext

**Comment by PiotrVV** [comment]
lftp version 4.7.3 already has this patch.
