### ISSUE TITLE
mingw32.exe conflicts with toolchain installation

### ISSUE THREAD

**Issue by MitchBradley** [Alexpux/MSYS2-packages#699]
Starting from a fresh install of msys2, followed by "pacman -Syuu", I then tried to install mingw-w64-i686-toolchain.  After downloading, the install failed with errors like:

error: failed to commit transaction (conflicting files)
mingw-w64-i686-libiconv: /mingw32 exists in filesystem
...

The file "/mingw32.exe" is preventing the creation of a subdirectory "/mingw32/".  When I renamed /mingw32.exe to /mingw-32.exe, the toolchain installation succeeded.  I then had to rename /mingw32.ini to /mingw-32.ini to make mingw-32.exe work.

The same thing happens with the x86_64 toolchain, conflicting with /mingw64.exe.

**Comment by mati865** [comment]
Duplicate https://github.com/Alexpux/MSYS2-packages/issues/689

**Comment by MitchBradley** [comment]
It is indeed a duplicate; closing
