### ISSUE TITLE
pacman -U  command seems broken

### ISSUE THREAD

**Issue by BazelFaron** [Alexpux/MSYS2-packages#703]
steps i've done before get the error:
1)Installed the most recent version of mingw64 and msys2
2)Added to PATH:
C:\msys64\usr\bin;
C:\mingw64\bin;
C:\mingw64\x86_64-w64-mingw32\bin
3)I've downloaded all the mingw64 packages from the [mingw-packages]( https://github.com/Alexpux/MINGW-packages ) repo.

Now errors i got:

the folowing command pacman -U mingw-w64-x86_64-gnutls-3.5.4-1-any.pkg.tar.xz
brings me the error:
..............
mingw-w64-x86_64-libiconv: '/mingw64' exists in filesystem
mingw-w64-x86_64-gmp: '/mingw64'  exists in filesystem
..............etc
however:
1) if i search into C:/mingw64 for any file with the name contains 'gnu' it gives me nothing means it's not installed.
2) There is no any mingw64 folder in my C:\msys64 folder
3) Also if i rename the C\mingw64 to something like C:\aaaa and run again the command i get
the error .... . '/mingw64'  exists in filesystem

P.S. i've alrdy read all avaible FAQs, wiki, stackoverflow and stuff without any result, so the last hope to make things work is to ask here. Any help is highly appreciated.

**Comment by Alexpux** [comment]
Please read previous issue to not open the same many times.
https://github.com/Alexpux/MSYS2-packages/issues/702

**Comment by BazelFaron** [comment]
okay,sorry, thanks for the really quick reply!! It works!
