### ISSUE TITLE
Running node from vim complains about tty

### ISSUE THREAD

**Issue by timmyL17** [Alexpux/MSYS2-packages#705]
Hi,

I'm trying to use the syntastic plugin for vim for syntax checking of files. For javascript, I'm trying to use jshint, which uses node.js. When I run node from the msys2 terminal, everything seems fine:

$ node -p -e "Boolean(process.stdin.isTTY)"
true
However, when I try to run node from inside vim:

:echo system('node')
It prints the error stdin is not a tty . So the syntax checking through syntastic won't work correctly.

When I was using cygwin 2 months ago, calling node from inside vim worked perfectly. I switched to msys2 because it was faster and smaller than cygwin. Is there a fundamental difference between the two that is causing this issue?

This problem has existed since I installed msys2 over a month ago, so I don't think it is due to the recent vim 8 version update this past week.

Thanks.

**Comment by timmyL17** [comment]
Also, in an up to date Archlinux system, this works correctly. So it seems to be specific to msys2.

**Comment by forgottenswitch** [comment]
Node is a mingw package, which means it uses win32 runtime, which ignores MSYS2 stdin/out/err,
thinking they are just \*-pty-* pipes.
The msys2 and cygwin runtimes (msys2.dll) check for the "-pty-" and handle `isatty()`, etc. correctly.

So you either need to run vim in cmd.exe, or install a nodejs compiled in Msys2 shell.
(Either making a new package or just from source).

**Comment by timmyL17** [comment]
Thanks for the explanation. I tried building it from source in an MSYS2 shell, but there were a bunch of errors out of the box. I'll try looking more in depth if I have time in the future.
