### ISSUE TITLE
build aspell errors -_fileno and _O_BINARY

### ISSUE THREAD

**Issue by twsam03** [Alexpux/MSYS2-packages#710]
When makepkg for aspell, found eror in

prog/compress.c : 28
and
prog/prezip.c : 42
both has under definition

`# define SETBIN(fno)  _setmode( _fileno( fno ), _O_BINARY )` 

that cause compile error. 

MSYS toolchain has no **_O_BINARY** defined , need to change to **O_BINARY**

and 
**_fileno** does not exist in libraries, need to change to **fileno**

**Comment by Alexpux** [comment]
Seems you try to build spell with MSYS compiler instead MINGW-W64
