### ISSUE TITLE
dependency issues

### ISSUE THREAD

**Issue by WsbPro** [Alexpux/MSYS2-packages#725]
When installing mingw-w64-x86_64-gcc using pacman like this:
$ pacman -S mingw-w64-x86_64-gcc
found the fllowing mistake:

warning: dependency cycle detected:
warning: mingw-w64-x86_64-gcc-libgfortran will be installed before its mingw-w64-x86_64-gcc-libs dependency

Then if ignore this warning and continue the installation, the dependency cycle will force the pacman to stop.
Is there a solution for this problem?

**Comment by Alexpux** [comment]
Need to check PKGBUILD why it happen.

**Comment by mati865** [comment]
I think mingw-w64-gcc-libs should **not** depend on `"${MINGW_PACKAGE_PREFIX}-gcc-libgfortran"`.

**Comment by Alexpux** [comment]
yeah. That's true

**Comment by WsbPro** [comment]
Thank you guys.
I'm new to msys2 and pacman on archlinux. So is there another way to install mingw-w64 gcc and g++ on msys2 without using this command?

**Comment by Alexpux** [comment]
Right now just ignore this warning and be happy

**Comment by mati865** [comment]
@WsbPro, for now just use `pacman -S mingw-w64-x86_64-toolchain` it will install all GCC tools.

**Comment by Alexpux** [comment]
This is another issue. https://github.com/Alexpux/MSYS2-packages/issues/702

**Comment by Alexpux** [comment]
New MSYS2 installers uploaded today to fix last described issue

**Comment by WsbPro** [comment]
Thank you sir, I'll test the installer right away.
