### ISSUE TITLE
clang/gcc c++ binary incompatiblity

### ISSUE THREAD

**Issue by oget** [Alexpux/MSYS2-packages#727]
The llvm-3.8 version that is currently provided does not support the c++ ABI tags that are produced by the gcc-5+. This makes it impossible to link clang-compiled c++ binaries to gcc-compiled libraries that have the new c++11 tags. 

llvm-3.9 is supposed to fix this problem. Please see
http://llvm.org/releases/3.9.0/docs/ReleaseNotes.html

Are there any plans to update llvm in the repos?
Thanks.

**Comment by TBBle** [comment]
clang 4.0 is now in the repository.

**Comment by elieux** [comment]
Thanks for noticing.
