### ISSUE TITLE
stdout is not a tty

### ISSUE THREAD

**Issue by jb-alvarado** [Alexpux/MSYS2-packages#740]
Hello,
in the past I always was able to pipe ffmpeg output to another program. But now not any more. I get the message: **stdout is not a tty**

I use this command for example:

`ffmpeg -re -i "input.mpeg" -f null /dev/null 2>&1 | awk '{print}'`

or:
`ffmpeg -i "input.mpeg"  -f matroska - | ffplay -`

In Windows cmd this is not a problem. 

You have any idea, what is happen here?

Regards

jb_

**Comment by lazka** [comment]
Maybe this? https://sourceforge.net/p/msys2/wiki/Porting/#standard-streams-in-mintty

**Comment by forgottenswitch** [comment]
Sorry, the reference is unrelated as long as winpty works not.

**Comment by jb-alvarado** [comment]
Ok I found a very wired solution. When ffmpeg is outside from the msys2 installation environment it works, or when I putt .exe at the end (ffmpeg.exe) it works also in the msys2 environment.
It can also be, that this issue belong to Windows 10, because I can not reproduce this in Windows 7.
 
Is this a bug from msys2? When not we can close here.

**Comment by wiiaboo** [comment]
If you're using ffmpeg/mpv from the media-autobuild_suite, it creates a helper script that calls ffmpeg/mpv with winpty. To not use that you need to explicitely use ffmpeg.exe or mpv.com.

**Comment by jb-alvarado** [comment]
Thank you wiiaboo for that information! It comes not to my mind, that there is a helper script.
