### ISSUE TITLE
Update mingw64 6.2.0 rev1

### ISSUE THREAD

**Issue by davidwed** [Alexpux/MSYS2-packages#760]
Please upgrade the mingw64 gcc package from Version 6.2.0 rev0 to 6.2.0 rev1, this will resolve several compiler errors especially for the WxWindows Lib.

https://sourceforge.net/projects/mingw-w64/

**Comment by mingwandroid** [comment]
That is not how msys2 works. We build from source and don't fetch binaries from other projects.

If you know the specific commits that fix your issues then please identify them.

**Comment by davidwed** [comment]
Hi,

thanks for the fast respond.

That's good, did you build the source from the main mingw-w64 repo ? ( 
git://git.code.sf.net/p/mingw-w64/mingw-w64 ).

Thanks in advanced.

Am 28.11.2016 18:35 schrieb Ray Donnelly:

**Comment by mati865** [comment]
Let's clear it a bit:
Latest `mingw-w64` is 5.0.0 but we build it from master git branch so it's even more recent.
Latest `GCC` is 6.2.0 and it doesn't use rev versioning.

**Comment by joeparkerz** [comment]
So how do I install gcc-6.2 with pacman?

**Comment by mati865** [comment]
https://github.com/Alexpux/MINGW-packages/wiki/Creating-MINGW-packages#createport-software-and-compile-it-in-mingw32-or-mingw64-subsystem

**Comment by davidwed** [comment]
Hi,

I've seen that you update the mingw64 package to the actually master 
branch of the mingw64 project. Now the WxWidgets library compiles 
without errors.

Thanks

Am 01.12.2016 16:08 schrieb Mateusz Mikuła:
