### ISSUE TITLE
CMake was unable to find a build program corresponding to "MSYS Makefiles"

### ISSUE THREAD

**Issue by OortJacek** [Alexpux/MSYS2-packages#769]
I have a build problem on WIN10.
I updated msys using pacman

```
jdrewniak@W299 MINGW64 /c/msys64/home/jdrewniak/workspace/kicad/build/release
$ cmake -DCMAKE_BUILD_TYPE=Release -G "MSYS Makefiles" -DCMAKE_PREFIX_PATH=/c/msys64/mingw64/ -DCMAKE_INSTALL_PREFIX=/c/msys64/mingw64/ -DDEFAULT_INSTALL_PATH=/c/msys64/mingw64/ -DKICAD_SCRIPTING=ON -DKICAD_SCRIPTING_MODULES=ON -DKICAD_SRIPTING_WXPYTHON=ON ../../
CMake Error: CMake was unable to find a build program corresponding to "MSYS Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMake was unable to find a build program corresponding to "MSYS Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_AR was not found, please set to archive program.
-- Configuring incomplete, errors occurred!
```

I have tried `-DCMAKE_PREFIX_PATH=/mingw64` also.

I had this problem on my other computer but somehow I managed this but I don't know how. 
So this command works fine on my first computer. 
```
cmake -DCMAKE_BUILD_TYPE=Release -G "MSYS Makefiles" -DCMAKE_PREFIX_PATH=/mingw64 -DCMAKE_INSTALL_PREFIX=/mingw64/ -DDEFAULT_INSTALL_PATH=/mingw64 -DKICAD_SCRIPTING=ON -DKICAD_SCRIPTING_MODULES=ON -DKICAD_SRIPTING_WXPYTHON=ON ../..
```

It is very cunfusing that I have same problem now. 
[CMakeCache.txt](https://github.com/Alexpux/MSYS2-packages/files/641654/CMakeCache.txt)

**Comment by mati865** [comment]
Probably you have no compiler installed.
For 64 bit:
`pacman --needed -S mingw-w64-x86_64-gcc` 
or
`pacman --needed -S mingw-w64-x86_64-toolchain`

**Comment by elieux** [comment]
I think you're missing `make` which is best installed by `pacman --needed -S base-devel`. You may also need to install the toolchain, as @mati865 says.

**Comment by OortJacek** [comment]
@elieux Yes, that was make - but I was sure that **make** from **mingw-w64-x86_64-make** will satisfy dependencies for cmake

**Comment by elieux** [comment]
It won't. First, the make from mingw-w64-x86_64-make is not `make.exe` but rather `mingw32-make.exe` and second, it has its own generator in CMake. Compare [MSYS Makefiles](https://cmake.org/cmake/help/v3.0/generator/MSYS%20Makefiles.html) and [MinGW Makefiles](https://cmake.org/cmake/help/v3.0/generator/MinGW%20Makefiles.html).

**Comment by skmunter** [comment]
Thank you so much this saved me after a day of time wasted

**Comment by RotterAxel** [comment]
Is it just me or is the process of compiling C code fucking convoluted as shit?

**Comment by Joymaker** [comment]
Particularly on Windows, because the C++ ecosystem is not native.  You’ve got Microsoft’s own tools (MSVC) vs MSYS2 vs MinGW each trying to provide that environment, and everybody in package-land seems to be making different assumptions about the tools to use.
