### ISSUE TITLE
Couldn't compute FAST_CWD pointer

### ISSUE THREAD

**Issue by cfis** [Alexpux/MSYS2-packages#787]
Starting with Windows 10 preview build 15002 (https://blogs.windows.com/windowsexperience/2017/01/09/announcing-windows-10-insider-preview-build-15002-pc/), using msy2 results in this error message being printed upon startup and doing various operations (such as git pull):

`Cygwin WARNING:
  Couldn't compute FAST_CWD pointer.  This typically occurs if you're using
  an older Cygwin version on a newer Windows.  Please update to the latest
  available Cygwin version from https://cygwin.com/.  If the problem persists,
  please see https://cygwin.com/problems.html`

Looks like Cygwin fixed this here:

https://cygwin.com/git/gitweb.cgi?p=newlib-cygwin.git;a=commitdiff;h=e5cadbfdcdd8b06932a9503b3c72511b68f03a60

Would be great to get a new msys2 version at some point to fix this.

Thanks!

**Comment by mati865** [comment]
Look here https://github.com/Alexpux/MSYS2-packages/pull/786

**Comment by cfis** [comment]
Fantastic - I'll close this ticket then (sorry that I didn't see that).
