### ISSUE TITLE
mintty updated in the git repository but binary build is missing

### ISSUE THREAD

**Issue by andreygursky** [Alexpux/MSYS2-packages#790]
Hi @elieux,
you've updated mintty a month ago (https://github.com/Alexpux/MSYS2-packages/commit/6ee5777f30a9e804286cedbe2679fe01c08948c9) but missed to trigger the build?

**Comment by Alexpux** [comment]
All packages in repository are building and uploading manually by me when I have time for it.

**Comment by andreygursky** [comment]
Thanks for clarifying.

Before to ask, I've read following in the MINGW-Packages readme:
> Please note: Not all the packages in this repository are built and accessible from the MSYS2 MINGW64 repo right away, after merging changes to the git repository it can take a few days until compiled and built packages are accessible in the repo.

And since significantly more than just few days passed, I've opened this issue. Could you please add similar to the MSYS2-Packages readme (replacing "few days" with something meaningful)?
