### ISSUE TITLE
dependency on getent seems missing on msys update

### ISSUE THREAD

**Issue by h-c-mueller** [Alexpux/MSYS2-packages#799]
I just  
upgraded filesystem (2016.07-2 -> 2017.02-1)
upgraded msys2-runtime (2.6.1-2 -> 2.6.1-3) 
and noted on shell start
"-bash: getent: command not found"
It seems a dependency to getent was missing.
PS: This is the way I assume snmishra noticed #798, which is now closed. Same happend to me. 
Thanks!

**Comment by dvhh** [comment]
reinstalled `getent` and that fixed the issue

    pacman -S getent

**Comment by filnet** [comment]
`pacman -S libargp getent` fixed it for me.

**Comment by elieux** [comment]
I made a fix so that it will first check if `getent` is available. Once filesystem v2017.02-2 is uploaded, there should be no more new reports of this. :)

**Comment by elieux** [comment]
We need a way to update people to the latest set of packages in `base` when they run `pacman -Syu`.

**Comment by mkae** [comment]
Shouldn't `libargp getent` be declared at least optional dependencies?

**Comment by Alexpux** [comment]
Optional for what?
libargp is dependency of getent now

**Comment by mkae** [comment]
Ah, okay, I missed that thanks.

Well, I meant that `getent` could be an optional dependency for bash, as the latter tries to call it in its `.bashrc`.

**Comment by elieux** [comment]
Just a note, @mkae, the `bash.bashrc` file comes from the `filesystem` package.

**Comment by Alexpux** [comment]
I'm upload new filesystem and getent packages.
