### ISSUE TITLE
Current msys2-runtime upgrade needs libargp

### ISSUE THREAD

**Issue by Uni-** [Alexpux/MSYS2-packages#803]
I upgraded the core, and met this error:

![a](https://cloud.githubusercontent.com/assets/1371115/22494779/b90f109c-e87d-11e6-81ad-d6d12615371d.png)

Then I installed the libargp package manually.

![b](https://cloud.githubusercontent.com/assets/1371115/22494786/caf7a51c-e87d-11e6-864e-e9675bf81ee4.png)

I think libargp must be installed with msys2-runtime dependency. How can I help it?

**Comment by Alexpux** [comment]
This is not msys2-runtime dependency. It dependency for getent. Fix already in git repo. New packages will be today later.

**Comment by Uni-** [comment]
I missed #798. Thank you folks for every day.
