### ISSUE TITLE
Run IRSSI on MSYS2 with Perl 5.24 failed #657

### ISSUE THREAD

**Issue by duytrung** [Alexpux/MSYS2-packages#817]
Hi,

I tried to use the IRSSI in MSYS2 for windows using "pacman -S irssi" to install. The installation was successful but I could not run the program as it said the file perl dll was not loaded. Perl was installed in the MSYS2 but newer version. How can I link the newer dll to irssi.

The issue was referenced at: https://github.com/irssi/irssi/issues/657

Thanks

**Comment by Alexpux** [comment]
Upload irssi 1.0.1
