### ISSUE TITLE
tig:  msys-readline6.dll: cannot open shared object file

### ISSUE THREAD

**Issue by the-nic** [Alexpux/MSYS2-packages#818]
When running tig I get the following error
`C:/msys64/usr/bin/tig.exe: error while loading shared libraries: msys-readline6.dll: cannot open shared object file: No such file or directory`

I guess this is related to the upgrade to readline-7.0, probably only a new `pkgrel` number required?

**Comment by mati865** [comment]
Yes, you should try rebuilding it.

**Comment by Alexpux** [comment]
Fixed https://github.com/Alexpux/MSYS2-packages/commit/8cf3a43d484a75e1a62a9fe9b358ddd6d7d8f24d
