### ISSUE TITLE
Packages are lacking versioned dependency to msys2-runtime

### ISSUE THREAD

**Issue by Rondom** [Alexpux/MSYS2-packages#819]
Recently both `pacman` (5.0.1-2) and `msys2-runtime` (2.7.0-1) got new versions. 

Upgrading just pacman using pacman broke pacman, because it was built against the new msys2-runtime. Looking through the repository I see that many packages are lacking a version for their dependencies.

Now that pacman can handle the upgrade of msys2-runtime gracefully (by restarting), I am wondering whether it would be possible to use package dependencies to prevent people from shooting themselves in the foot like I did.

(I have read https://github.com/msys2/msys2/wiki/MSYS2-installation#iv-general-package-management and cannot find anything that made me expect that I did anything that is known to be broken.)

**Comment by Alexpux** [comment]
MSYS2 is rolling release system so you cant just partially update packages. You always need update all packages.

**Comment by elieux** [comment]
We are only able to support latest versions of everything. This is the consequence of the rolling-release/bleeding-edge model we adopted from Arch Linux. Verifying and adding dependency version constraints would require additional work-time that we can't afford to spend on this.

Thanks for reporting. I updated the wikipage to mention partial upgrades are unsupported.

You may be interested in a [discussion about 'stable' repositories](https://sourceforge.net/p/msys2/mailman/msys2-users/thread/b09d09d7-62cf-7dd5-6249-122e37d886b3%40emmenlauer.de/) on our mailing list.

**Comment by Rondom** [comment]
I see, thanks for the response and updating the documentation.
