### ISSUE TITLE
Upstream changes to newline handling in sed/awk/etc.

### ISSUE THREAD

**Issue by Mistuke** [Alexpux/MSYS2-packages#822]
A recent change in the upstream packages `sed`, `awk` etc change the behaviour of how the tools handle newline characters by switching from text mode to binary mode for input.

This is disastrous for Windows as it means `$` no longer matches end of line. So all scripts are potentially broken. See https://ghc.haskell.org/trac/ghc/ticket/13315

The proposed solution on the cygwin mailing list of using `dos2unix` everywhere is non-trivial and requires massive amount of code changes to deal with this.

using `text` mounts partially solves the problem for files read from disk, but does not fix the issue when piping data. As such, can these patches be reverted for MSYS2? It seems like it's not the desired behaviour we want or expect on Windows.

Testcase:

older MSYS2:

```
Core@CI-01 MINGW64 ~
$ printf "hello world\r\n234" | sed -e 's/world$/irc/g'
hello irc
234
Core@CI-01 MINGW64 ~
$ printf "hello world\n234" | sed -e 's/world$/irc/g'
hello irc
234
```

new MSYS2:

```
Core@CI-02 MINGW64 ~
$ printf "hello world\r\n234" | sed -e 's/world$/irc/g'
hello world
234
Core@CI-02 MINGW64 ~
$ printf "hello world\n234" | sed -e 's/world$/irc/g'
hello irc
234
```

**Comment by elieux** [comment]
We had success patching `sed` back to reading in text mode. It'll be uploaded soon, I hope.

**Comment by Mistuke** [comment]
Thanks, I can confirm that this now works again!
