### ISSUE TITLE
bzr 2.7 broken with python 2.7.12

### ISSUE THREAD

**Issue by Ede123** [Alexpux/MSYS2-packages#826]
When pulling/updating or similar the following error is thrown:
`TypeError: first argument must be string or compiled pattern`

Upstream bug report:
https://bugs.launchpad.net/bzr/+bug/1644003

Upstream patches
http://bazaar.launchpad.net/~bzr-pqm/bzr/2.7/revision/6621
http://bazaar.launchpad.net/~bzr-pqm/bzr/2.7/revision/6622

**Comment by mingwandroid** [comment]
Thanks for doing the research, and thanks @mati865 for doing the PR. Would it be possible for you to start looking into making PRs yourself though?

**Comment by Ede123** [comment]
Sorry, but I hit this bug while being busy with something else.
I hope it's fine if I don't drop everything to create a PR ASAP in that case...

**Comment by mingwandroid** [comment]
Of course!
