### ISSUE TITLE
Missing dependency on mingw-w64-x86_64-gettext for mingw-w64-x86_64-make

### ISSUE THREAD

**Issue by glandium** [Alexpux/MSYS2-packages#828]
After a fresh install of msys2, and installing `mingw-w64-x86_64-make`, running `mingw32-make` fails because of missing `libintl-8.dll`, which comes in `mingw-w64-x86-64-gettext`.

**Comment by TBBle** [comment]
On examination, this is actually an issue for Alexpux/MINGW-packages, and has been reported there as Alexpux/MINGW-packages#2233

**Comment by lazka** [comment]
assuming this is #2233 and that has been fixed -> closing
