### ISSUE TITLE
mingw-w64-x86_64-make-4.2.1-1 is corrupted

### ISSUE THREAD

**Issue by zdm** [Alexpux/MSYS2-packages#830]
Hi.
After update to mingw-w64-x86_64-make-4.2.1-1 mingw32-make.exe stop working. I think, that this file is corrupted in package. I have tried many times but got the same result.

```
d:\devel\msys2\mingw64\bin>.\mingw32-make.exe --help

d:\devel\msys2\mingw64\bin>.\mingw32-make.exe fake-string

d:\devel\msys2\mingw64\bin>.\mingw32-make.exe

d:\devel\msys2\mingw64\bin>
```

**Comment by zdm** [comment]
As you can see, i returns nothing and not working totally.

**Comment by TBBle** [comment]
Same report as #842

**Comment by elieux** [comment]
Thanks for noticing. I advise @zdm to look at the other ticket.
