### ISSUE TITLE
The chipmunk package is far out of date!

### ISSUE THREAD

**Issue by ninepillars** [Alexpux/MSYS2-packages#851]
chipmunk package is needed for some game engines, such as cocos2d-x.

current version in msys2 is 6.2, but the newest version should be 7.0! with many new functions.

**Comment by mingwandroid** [comment]
You filed this in the wrong place, chipmunk is a MINGW-package.

**Comment by mingwandroid** [comment]
Moved to: https://github.com/Alexpux/MINGW-packages/issues/2352
