### ISSUE TITLE
cmake hang

### ISSUE THREAD

**Issue by EchoOfSoul** [Alexpux/MSYS2-packages#860]
This happened in my system alone or were there other ppl who are also experiencing this problem as well?
I just do
`cmake ..`
and just hang can't do anything except shut mintty down through task

**Comment by mingwandroid** [comment]
Can you use `procmon` to see what files got accessed? You probably should share the `CMakeLists.txt` file in the parent folder too.

**Comment by EchoOfSoul** [comment]
It's only on my `cmake-3.6.2-1-i686` is hang. `mingw-w64-i686-cmake-3.7.2-2` work just fine.
using MSYS or mingw32 shell have the same effect `hang`
```
Modules:
- msys-lzo2-2.dll
- cmake.exe
- msys-2.0.dll
- msys-asn1-8.dll
- msys-iconv-2.dll
- msys-bz2-1.dll
- msys-crypto-1.0.0.dll
- msys-curl-4.dll
- msys-archive-13.dll
- msys-z.dll
- msys-gssapi-3.dll
- msys-stdc++-6.dll
- msys-krb5-26.dll
- msys-wind-0.dll
- msys-expat-1.dll
- msys-heimbase-1.dll
- msys-com_err-1.dll
- msys-gcc_s-1.dll
- msys-sqlite3-0.dll
- msys-ssl-1.0.0.dll
- msys-ssh2-1.dll
- msys-crypt-0.dll
- msys-roken-18.dll
- msys-heimntlm-0.dll
- msys-hx509-5.dll
- msys-lzma-5.dll
- msys-nettle-6.dll
- KernelBase.dll
- kernel32.dll
- ntdll.dll
```
any `CMakeLists.txt` i use jst hang. I pick this simple example :
```
cmake_minimum_required(VERSION 2.8.9)
project (hello)
add_executable(hello helloworld.cpp)
```

**Comment by EchoOfSoul** [comment]
> autorebasebase1st.bat

solf my problems

**Comment by basicmaster** [comment]
I'm affected by the same problem. What is `autorebasebase1st.bat` and how did it solve the issue?

**Comment by crazybytes** [comment]
My msys2 ran under mingw32/mingw64/msys2 hangs sometimes when i use tar xf <file>
Also installing with svn it hangs, cannot kill, only close window.
Then svn remains in background.

**Comment by orgads** [comment]
Happens to me too, with cmake 3.15.5 and latest msys32 (doesn't happen on msys64).

**Comment by orgads** [comment]
@EchoOfSoul / @Alexpux : Please reopen.

**Comment by orgads** [comment]
Happened now with ninja too. I redirected the output to a file, and noticed the following message at its end:

```
      0 [main] cmake 3030 child_info_fork::abort: \??\C:\msys32\usr\bin\msys-idn2-0.dll: Loaded to different address: parent(0xBF0000) != child(0x1300000)
```

**Comment by Alexpux** [comment]
@orgads close all msys2 shells and run autorebase.bat

**Comment by orgads** [comment]
Yup, that fixed it. I also needed to kill all the bash, cmake, make and ninja processes before executing autorebase.

Thanks!
