### ISSUE TITLE
winpty + gdb = readline_callback_read_char() called with no handler!

### ISSUE THREAD

**Issue by tico-tico** [Alexpux/MSYS2-packages#873]
Pretty easy to reproduce:

`$ winpty gdb`

`(gdb) target exec ls`
`(gdb) run`

```
Starting program: /usr/bin/ls
[New Thread 10412.0x1720]
readline: readline_callback_read_char() called with no handler!
      6 [main] gdb 15304 cygwin_exception::open_stackdumpfile: Dumping stack trace to gdb.exe.stackdump
```

Another one (more interesting):

`$ winpty gdb /mingw32/bin/gcc`
`(gdb) run`
```
Starting program: /mingw32/bin/gcc.exe
[New Thread 19220.0x4ce0]
readline: readline_callback_read_char() called with no handler!
      5 [main] gdb 17860 cygwin_exception::open_stackdumpfile: Dumping stack trace to gdb.exe.stackdump
gcc.exe: fatal error: no input files
```

**BUT**

`$ winpty gdb /mingw32/bin/gcc`
Press UP/DOWN keys several times.
`(gdb) run`
```
Starting program: /mingw32/bin/gcc.exe
[New Thread 11736.0x5d38]
gcc.exe: fatal error: no input files
```
No problem with *readline*.

It's on MSYS2 32-bit. I haven't checked on x64.

**Comment by wrightsg** [comment]
I'm seeing the exact same behavior in 64-bit environment.

**Comment by tico-tico** [comment]
I don't get it, how is my *readline* issue with *gdb 7.11.1* from the **MSYS2** rep related to your issue with *python*, wrong *winpty*'s path and *gdb 7.12.1* from the **MINGW** rep?

**Comment by wrightsg** [comment]
First, I'm getting the same output as you when running the `target exec ls` command from `gdb` from the mingw64 environment, i.e.

```
(gdb) target exec ls
(gdb) run
Starting program: /usr/bin/ls
[New Thread 10848.0x3878]
readline: readline_callback_read_char() called with no handler!
      0 [main] gdb 15108 cygwin_exception::open_stackdumpfile: Dumping stack trace to gdb.exe.stackdump
```

I realized that depending on whether I call `gdb` or `winpty gdb` for some reason a different `gdb` is selected (in the first case gdb from mingw64 environment and in the second case from msys environment). As far as I remember this used to work fine previously (?).

As you didn't provide your output from `gdb` or `winpty gdb` I thought that you might be having the same/similar problem. Note sure from which environment you're calling `gdb` though. msys or mingw32?

**Comment by tico-tico** [comment]
Ah, now i understand.

> Not sure from which environment you're calling gdb though. msys (msys2.exe) or mingw32 (mingw32.exe)?

I thought it's quite obvious since the name of this repo is **MSYS2-packages**. There is another one for mingw32/64 environment.

**Comment by michalfapso** [comment]
Thanks for the great tip, now I use the absolute path for gdb and it works with winpty again:
`winpty /mingw64/bin/gdb main.exe`
