### ISSUE TITLE
Seg fault in /mingw64/bin/enchant

### ISSUE THREAD

**Issue by postiffm** [Alexpux/MSYS2-packages#900]
Latest msys2 fresh install today on Windows 7 64-bit.

$ gdb /mingw64/bin/enchant
...
Reading symbols from C:/msys64/mingw64/bin/enchant...(no debugging symbols found)...done.
(gdb) set args -v
(gdb) run
Starting program: C:\msys64\mingw64\bin\enchant.exe -v
[New Thread 5964.0x1834]
@(#) International Ispell Version 3.1.20 (but really Enchant 1.6.1)
[Inferior 1 (process 5964) exited normally]
(gdb) set args test.txt
(gdb) run
Starting program: C:\msys64\mingw64\bin\enchant.exe test.txt
[New Thread 1532.0xec8]
[New Thread 1532.0x9d0]
[New Thread 1532.0x1a3c]
[Thread 1532.0x9d0 exited with code 0]
[Thread 1532.0x1a3c exited with code 0]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000007747fe54 in ntdll!RtlUnicodeToMultiByteSize ()
   from C:\Windows\SYSTEM32\ntdll.dll
(gdb) bt
#0  0x000000007747fe54 in ntdll!RtlUnicodeToMultiByteSize ()
   from C:\Windows\SYSTEM32\ntdll.dll
#1  0x00000000774f4489 in ntdll!RtlLogStackBackTrace ()
   from C:\Windows\SYSTEM32\ntdll.dll
#2  0x000000007749797c in ntdll!TpAlpcRegisterCompletionList ()
   from C:\Windows\SYSTEM32\ntdll.dll
#3  0x000007feff4510c8 in msvcrt!free () from C:\Windows\system32\msvcrt.dll
#4  0x000000006494309d in ?? () from C:\msys64\mingw64\bin\libwinpthread-1.dll
#5  0x0000000067c411e2 in ?? () from C:\msys64\mingw64\bin\libaspell-15.dll
#6  0x0000000067c412f4 in ?? () from C:\msys64\mingw64\bin\libaspell-15.dll
#7  0x0000000077452ac1 in ntdll!LdrShutdownProcess ()
   from C:\Windows\SYSTEM32\ntdll.dll
#8  0x00000000774528d0 in ntdll!RtlExitUserProcess ()
   from C:\Windows\SYSTEM32\ntdll.dll
#9  0x000007feff4599e2 in msvcrt!_wcstoui64 ()
   from C:\Windows\system32\msvcrt.dll
#10 0x00000000004014cd in ?? ()
#11 0x000000000040151b in ?? ()
#12 0x00000000772259cd in KERNEL32!BaseThreadInitThunk ()
   from C:\Windows\system32\kernel32.dll
#13 0x000000007745a561 in ntdll!RtlUserThreadStart ()
   from C:\Windows\SYSTEM32\ntdll.dll
#14 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Program also dies if run from a Windows/DOS cmd prompt.

Please let me know what else I can do to help you debug this.

Maybe another clue? 
$ gedit
(gedit.exe:6300): libpeas-WARNING **: Failed to load module 'spell': 'C:\msys64\mingw64\lib\gedit\plugins\libspell.dll': The specified module could not be found.
(gedit.exe:6300): libpeas-WARNING **: Error loading plugin 'spell'

**Comment by Alexpux** [comment]
Wrong repo

**Comment by mati865** [comment]
And it doesn't crash any more.
