### ISSUE TITLE
FindBoost Fails because mingw-w64-boost is version 1.63 but msys/cmake is 3.6.2

### ISSUE THREAD

**Issue by jralls** [Alexpux/MSYS2-packages#905]
CMake 3.6.2 supports only boost 1.61 and earlier; CMake 3.7.2 added support for boost 1.63.

**Comment by mati865** [comment]
Use `mingw-w64-i686-cmake` or `mingw-w64-x86_64-cmake`. They are at 3.8.1 version.

**Comment by jralls** [comment]
Thanks, but msys/cmake should still be brought up to date or removed.

**Comment by TBBle** [comment]
The msys cmake package is version 3.10.2 as of https://github.com/Alexpux/MSYS2-packages/commit/6923305c7137310270c0eb3c8ebb8138e14a0d22#diff-272ceadb8458515b2ae4b5630a6029cc so this issue can probably be closed.

**Comment by jralls** [comment]
OK.

**Comment by mingwandroid** [comment]
> Thanks, but msys/cmake should still be brought up to date or removed

Strongly disagree, and also, MSYS2 is an open source project so if you care about something being too old then bring it up to date and make a PR rather than telling other people how to spend their time.

**Comment by jralls** [comment]
> Strongly disagree, and also, MSYS2 is an open source project so if you care about something being too old then bring it up to date and make a PR rather than telling other people how to spend their time.

I appreciate the sentiment, but I have [other](https://github.com/gnucash.org) [open-source](https://git.gnome.org//browse/gtk-osx) projects that consume most of my time. It's an interdependent ecosystem that would collapse if PRs were the only way to raise issues.
