### ISSUE TITLE
About osgearth for Qt

### ISSUE THREAD

**Issue by zebrainncu** [Alexpux/MSYS2-packages#907]
Hi Alexpux
I want to do something on Qt.
Here is the problem.
After I run pacman -S mingw-w64-x86_64-osgearth in msys2, I try to run  
cmd in Msys2
osgviewer /usr/share/osgearth/maps/openstreetmap.earth

result as below:
D:\msys64\mingw64\bin\osgviewer.exe: No data loaded
Error reading file D:/msys64/usr/share/osgearth/maps/openstreetmap.earth: read error (Could not find plugin to read objects from file "D:/msys64/usr/share/osgearth/maps/openstreetmap.earth".)

And I found the osgearth directory is Empty under /usr/share.

What else need to do?

**Comment by Alexpux** [comment]
Wrong repo.
