### ISSUE TITLE
missing `texi2dvi` script in MSYS2 packages

### ISSUE THREAD

**Issue by sav-ix** [Alexpux/MSYS2-packages#912]
Hello, everyone,

For [GMP-6.1.2](https://gmplib.org/download/gmp/gmp-6.1.2.tar.bz2) builds using MSYS2+mingw-w64 on Windows got error:
```
sh-4.4$ ./configure && make
[snip]
sh-4.4$ make install-pdf
[snip]
Making install-pdf in doc
make[1]: Entering directory '/c/libGMP-6.1.2/build/doc'
TEXINPUTS=".:$TEXINPUTS" \
MAKEINFO='/bin/sh /c/libGMP-6.1.2/build/missing makeinfo   -I .' \
texi2dvi --pdf --batch  --build-dir=gmp.t2p -o gmp.pdf  \
gmp.texi
/bin/sh: texi2dvi: command not found
make[1]: *** [Makefile:456: gmp.pdf] Error 127
make[1]: Leaving directory '/c/libGMP-6.1.2/build/doc'
make: *** [Makefile:956: install-pdf-recursive] Error 1
```
The [standard solution](https://stackoverflow.com/questions/17652698/texi2dvi-command-not-found) for missing `texi2dvi` script ([1](https://www.ctan.org/pkg/texi2dvi-latest), [2](https://www.gnu.org/software/texinfo/manual/texinfo/html_node/Format-with-texi2dvi.html)) to install `texinfo` package didn't solve this issue.
Could you tell:
- wasn't `texi2dvi` included to MSYS2 packages because of some reason (size, TeX dependence, etc.)?
- would it be fixed in future MSYS2 releases?

Alexander

**Comment by sav-ix** [comment]
Tested to run
```
./configure && make && make install
```
for [texinfo-6.3.tar.gz](https://ftp.gnu.org/gnu/texinfo/texinfo-6.3.tar.gz) (currently used in MSYS2) and [texinfo-6.5.tar.gz](https://ftp.gnu.org/gnu/texinfo/texinfo-6.5.tar.gz) (most recent available) sources.
In both cases all tasks finished successfully and all `texinfo` scripts were installed into MSYS2 installation directory. Then `texi2dvi` and `texindex` became available for use, and GMP pdf documentation was built successfully.
Taking into account the above, seems there is no need in any changes to `texinfo` sources, in order to port it to MSYS2. The source of this issue could be:
```
for ff in makeinfo pod2texi texi2any; do
```
condition in file [texinfo/PKGBUILD](https://github.com/Alexpux/MSYS2-packages/blob/master/texinfo/PKGBUILD), which doesn't cover `texi2dvi` and `texindex` scripts.

**Comment by albfan** [comment]
@sav-ix is correct here. Why we are avoiding to install those scripts?

**Comment by cbrt64** [comment]
`texi2dvi`, `texindex`, etc. are installed separately from package texinfo-tex since [70df0d9a](https://github.com/Alexpux/MSYS2-packages/commit/70df0d9ac1b01a4f61cb9f50df6388148484c91f).

**Comment by albfan** [comment]
@sav-ix translate: pacman -S texinfo-text is what you need. In the future, use pkgfile to check what package provides a file you're looking for

    $ pkgfile texi2dvi

should find for you the package that provides whatever file you're looking for

NOTE: You need to install pkgfile first

I think you can close this issue.

**Comment by sav-ix** [comment]
@cbrt64, @albfan, thank you for tips.
Just installed `texinfo-tex` package, and error not reproduced. Would use `pkgfile` next time I need to find missing files.
Closing this issue as resolved.
