### ISSUE TITLE
Vim makepkg failed

### ISSUE THREAD

**Issue by azarashichop** [Alexpux/MSYS2-packages#934]
In progress of 'makepkg', some errors appears.
os_unix.c: In function 'mch_call_shell':
os_unix.c:4919:31: error: expected identifier before '=' token  
        || (wait_pid == pid && WIFEXITED(status)))  
                               ^
os_unix.c:4919:31: warning: excess elements in union initializer
        || (wait_pid == pid && WIFEXITED(status)))
                               ^~~~~~~~~
os_unix.c:4919:31: note: (near initialization for '(anonymous)')
In file included from os_unixx.h:28:0,
                 from os_unix.c:38:
os_unix.c:4919:31: error: expected identifier before ')' token
        || (wait_pid == pid && WIFEXITED(status)))
                               ^
os_unix.c:5045:10: error: expected identifier before '=' token
      if (WIFEXITED(status))
          ^
os_unix.c:5045:10: warning: excess elements in union initializer
      if (WIFEXITED(status))
          ^~~~~~~~~

How we abort it?

**Comment by elieux** [comment]
Same problem as mintty/mintty#668. I need to make that patch. :)

**Comment by azarashichop** [comment]
@elieux 
Thank you replying!

**Comment by azarashichop** [comment]
By following [your post](https://cygwin.com/ml/cygwin-patches/2017-q3/msg00002.html), I modified 2 files (/usr/include/string.h and /usr/include/sys/wait.h).
And now, I succeed in building & installing vim package!
Thank you!

**Comment by elieux** [comment]
The fix is present in `msys2-runtime` v2.8.2.
