### ISSUE TITLE
mutt.h:60:10: fatal error: pwd.h: No such file or directory  when compiling mutt 1.8.3 on msys2

### ISSUE THREAD

**Issue by sanqz** [Alexpux/MSYS2-packages#963]
mutt.h:60:10: fatal error: pwd.h: No such file or directory  when compiling mutt 1.8.3 on msys2

**Comment by elieux** [comment]
Do you have packages from the `base-devel` and `msys2-devel` groups installed?

```
$ pacman -Fs pwd.h
...
msys/msys2-runtime-devel 2.6.0-1
    usr/include/pwd.h
...
```

**Comment by sanqz** [comment]
$ pacman -Fs pwd.h
mingw32/mingw-w64-i686-postgresql 9.6.3-1
    mingw32/include/postgresql/server/port/win32/pwd.h
mingw64/mingw-w64-x86_64-postgresql 9.6.3-1
    mingw64/include/postgresql/server/port/win32/pwd.h
msys/msys2-runtime-devel 2.8.2-1
    usr/include/pwd.h

**Comment by elieux** [comment]
Do you have packages from the `base-devel` and `msys2-devel` groups installed?

**Comment by sanqz** [comment]
yes

**Comment by elieux** [comment]
Do you have this file? `/usr/include/pwd.h`

Please post complete steps to reproduce the error, including the build log. If it's large, use a pastebin service.

**Comment by sanqz** [comment]
Thanks for your reply.

here are the output and log

$ ls /usr/include/pwd.h -l
-rw-r--r-- 1 Zhang Zhang 2999 Jul 14 13:39 /usr/include/pwd.h


$ make
make  all-recursive
make[1]: Entering directory '/d/github/mutt-1.8.3'
Making all in m4
make[2]: Entering directory '/d/github/mutt-1.8.3/m4'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/d/github/mutt-1.8.3/m4'
Making all in po
make[2]: Entering directory '/d/github/mutt-1.8.3/po'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/d/github/mutt-1.8.3/po'
Making all in intl
make[2]: Entering directory '/d/github/mutt-1.8.3/intl'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/d/github/mutt-1.8.3/intl'
Making all in doc
make[2]: Entering directory '/d/github/mutt-1.8.3/doc'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/d/github/mutt-1.8.3/doc'
Making all in contrib
make[2]: Entering directory '/d/github/mutt-1.8.3/contrib'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/d/github/mutt-1.8.3/contrib'
Making all in imap
make[2]: Entering directory '/d/github/mutt-1.8.3/imap'
gcc -DHAVE_CONFIG_H -I. -I..  -I.. -I../intl -I/include -I../intl  -Wall -pedantic -Wno-long-long -g -O2 -MT auth.o -MD -MP -MF .deps/auth.Tpo -c -o auth.o auth.c
In file included from auth.c:27:0:
../mutt.h:60:10: fatal error: pwd.h: No such file or directory
 #include <pwd.h>
          ^~~~~~~
compilation terminated.
make[2]: *** [Makefile:408: auth.o] Error 1
make[2]: Leaving directory '/d/github/mutt-1.8.3/imap'
make[1]: *** [Makefile:868: all-recursive] Error 1
make[1]: Leaving directory '/d/github/mutt-1.8.3'
make: *** [Makefile:543: all] Error 2

I googled above error, someone said that msys2 can't use POSIX API which pwd.h belong to

I also install mutt from repo by pacman -S mutt, but it can't use because of missing lib

$ mutt
C:/msys64/usr/bin/mutt.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory

**Comment by elieux** [comment]
I cannot reproduce your issue, because you didn't write down all commands. Please include the URL where you got the source code and all commands before `make`.

**Comment by sanqz** [comment]
my steps
`wget ftp://ftp.mutt.org/pub/mutt/mutt-1.8.3.tar.gz`

`tar tzxv mutt-1.8.3.tar.gz`

`cd mutt-1.8.3`

configure options
` ./configure --enable-imap --enable-pop --with-ssl --enable-smtp --with-homespool=mailspool --enable-hcache --enable-debug --with-mailpath=/d/mail`

`make`

**Comment by elieux** [comment]
I tried these steps and it worked.  I had to install some packages:

`pacman -S --needed base-devel msys2-devel libgpgme-devel libsasl-devel libgdbm-devel ncurses-devel libgnutls-devel libidn-devel openssl-devel`

**Comment by elieux** [comment]
Can you show what `which gcc` says?

**Comment by sanqz** [comment]
$ which gcc
/mingw64/bin/gcc

**Comment by elieux** [comment]
That's the problem. How are you starting MSYS2? Instead of using the *MINGW64* shell, you need to use the *MSYS* shell. You can see the current shell in purple color in your prompt. You can also see it using `echo $MSYSTEM`.

If `gcc` still points to `/mingw64/bin/gcc` even in an *MSYS* shell, then maybe you have changed your `PATH` variable, in which case you need to change it back to default.

**Comment by sanqz** [comment]
it worked when I change my shell to mingw32, thank you very much

**Comment by elieux** [comment]
Please note that you are supposed to use the *MSYS* shell, not any of the *MINGW* ones.

**Comment by sanqz** [comment]
got it, thanks
