### ISSUE TITLE
msys2-installer license

### ISSUE THREAD

**Issue by projectgus** [Alexpux/MSYS2-packages#987]
Hi folks,

Are the scripts for msys2-installer in https://github.com/msys2/msys2-installer under any license?

Could they possibly be put under the same LICENSE as this repo?

(Looking to make an installer for an MSYS2-derived application, with a larger subset of packages included. Would be great to be able to leverage these scripts and re-release any changes.)

Thanks,

Angus

PS Apologies for posting in an unrelated repo, but Issues are disabled in the installer repo and @Alexpux is author of both so this seemed like the best place.

**Comment by mingwandroid** [comment]
From my perspective s co-author they are public domain if Alexey agrees.

**Comment by Alexpux** [comment]
@mingwandroid I'm agree

**Comment by ErichDonGubler** [comment]
@projectgus: Does @Alexpux's resolution satisfy you? Is there anything else you would like to discuss before this gets closed?

**Comment by projectgus** [comment]
No, I'm happy if those folks are happy. Thanks. :)
