### ISSUE TITLE
packge libcurl missing dependency

### ISSUE THREAD

**Issue by CCTV-1** [Alexpux/MSYS2-packages#999]
I'm sorry that my english is not very good.the following is basically a machine translation (:
When i update libcurl-devel to 7.55.1-1,recompile program link failed.
run `pkg-config --cflags --libs libcurl` result:
`-lcurl -lnghttp2 -lidn2 -liconv -lunistring -lssh2 -lssl -lz -lcrypto -lz -lssl -lcrypto -lssl -lz -lcrypto -lz -lgdi32 -lgssapi -lheimntlm -lkrb5 -lhx509 -lcom_err -lcrypto -lasn1 -lwind -lheimbase -lroken -lsqlite3 -lcrypt -lz`
but `pactree libcurl-devel | grep devel` result:
```
libcurl-devel
├─heimdal-devel
│ ├─libcrypt-devel
│ ├─libedit-devel
│ │ └─ncurses-devel
│ ├─libdb-devel
│ └─libsqlite-devel
├─libcrypt-devel
├─libmetalink-devel
│ └─libexpat-devel
├─libidn2-devel
├─libssh2-devel
│ ├─openssl-devel
│ │ └─zlib-devel
│ └─zlib-devel
├─openssl-devel
└─zlib-devel
```
does not exist libnghttp2-devel libunistring-devel libiconv-devel dependency.i installed it alone these packs compiled successfully.

in addition,`pkg-config --cflags --libs libcurl` result why there is repeat?

**Comment by Alexpux** [comment]
https://github.com/Alexpux/MSYS2-packages/commit/2d339de00699ffd0bb6819cfb96c440f0d8fbd6c
